### ISSUE TITLE
Support vertical alignment

### ISSUE THREAD

**Issue by wuranbo** [rust-lang/rustfmt#1103]
Could the rustfmt support vertically align as default? At least it can be configured not to break the vertically aligned code when try to format codes include them.

Many people love it.
https://shkspr.mobi/blog/2014/11/why-i-vertically-align-my-code-and-you-should-too/

And another support is the gofmt use vertical alignment https://golang.org/doc/effective_go.html#formatting .

**Comment by duesee** [comment]
There is an ongoing effort to find consensus about source code style in Rust. I'm also a fan of this style, so maybe you should try your luck here: https://github.com/rust-lang/rfcs/pull/1607

AFAIK rustfmt will stick to the style agreed on in the broader community.

**Comment by wuranbo** [comment]
Thank you @duesee , I already did it. And I saw the RFC, it is targeting to get 'the decision process for the coding style', and it also said at last we will get the recommended style, and rustfmt will impl it as default style, leave others configurable. So whether the vertically align is choiced to be the recommended style,  it can be implemented in rustfmt as a configuration.

**Comment by wuranbo** [comment]
And another support is the gofmt use vertical alignment https://golang.org/doc/effective_go.html#formatting .

**Comment by flosse** [comment]
Are there any updates?

**Comment by nrc** [comment]
> Are there any updates?

No, sorry. I would take a PR for this if there was a fairly complete implementation, but I don't have time to work on it myself and there is a lot of higher priority work (better support for the default options, basically) to point people at.

**Comment by synek317** [comment]
I guess there is still no update on this.

Is this still true?

> I would take a PR for this if there was a fairly complete implementation

If yes, I would like to at least try to implement this feature, I really miss it :upside_down_face:

**Comment by alexmozaidze** [comment]
It would actually be really cool if it worked on per "code block" basis like this:
```rust
// this would get vertically aligned
#[rustfmt::vertical_align]
const PLAYER_MONEY: f32 = 32.0;
const PLAYER_VERY_LOOOOONG_CONSTANT: u32 = 0;

// this would not since it's separated with a newline
const ENEMY_MONEY: f32 = 23.0;
const ENEMY_VERY_LOOOOONG_CONSTANT: u32 = 0;
```
so it would be possible to tell it what to and what not to align vertically.

**Comment by calebcartwright** [comment]
Closing as this issue is quite old and has outlived its relevancy.

The defaults were established many years ago and are not going change. However, those that prefer the vertical/visual layout can utilize existing options like [indent_style](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#indent_style) and [struct_field_align_threshold](https://rust-lang.github.io/rustfmt/?version=v1.4.38#struct_field_align_threshold).

There are certainly still gaps in places where vertical/visual alignment is only partially support and others not yet at all, but those are best tracked in their respective issues (e.g. #894). Anyone willing and interested in improving vertical/visual support should certainly feel free to do submit patches for review.
