### ISSUE TITLE
API that returns the ranges modified

### ISSUE THREAD

**Issue by nrc** [rust-lang/rustfmt#1173]
This would be an altered diff mode that returns the lines modified and the new lines, rather than a standard diff. Useful for embedding in IDEs.

**Comment by jugglerchris** [comment]
I'd like to have a go at this.  It looks to me like what's needed is another function a lot like `format_input()`, but which instead of taking an reference to a `T:Write` to write the output returns something like `Vec<(lineno, num_lines, Vec<String>)>` in the `Ok` path for the lines changed.  I guess the `WriteMode` in the `config` would be ignored, but it would do the same as with `WriteMode::Diff` except for the formatting of the result.

I don't think any visible change to the `rustfmt` binary is needed or makes sense (though maybe similar information returned as JSON might be useful if anything wants to run the `rustfmt` binary instead of using the library.

Am I thinking along the right lines?

**Comment by nrc** [comment]
Hi @jugglerchris it would be great if you could have a go at this! (I'm on parental leave right now, so will be a bit slow to respond). Ideally we would just add another write_mode, but I guess that might be difficult. If that doesn't work, then adding a new function as you suggest sounds good. It would be nice to share as much code as possible between  the new function and `format_input` as possible since `format_input` is a bit complex.

**Comment by jugglerchris** [comment]
I thought about a new write mode, but that doesn't directly help the RLS (which I understand is the motivating use case), since `format_input` can only return via the `Option<&mut T:Write>`.

I'll see if I can get something working and see how it goes!
