### ISSUE TITLE
--print-config minimal doesn't work as advertised

### ISSUE THREAD

**Issue by tchajed** [rust-lang/rustfmt#2758]
What I tried:
(1) `rustfmt --print-config minimal .rustfmt.toml`
(2) `rustfmt --print-config minimal .rustfmt.toml src/lib.rs`

What I expected:
Invocation (1) should have produced a minimal configuration in `.rustfmt.toml` based on settings from the current directory, without formatting anything.
Invocation (2) should have done something similar, but only incorporating `src/lib.rs`.

What actually happened:
The PATH following `--print-config minimal` is both the path to the minimal config and the file to run `rustfmt` on. So, the first complains the file doesn't exist; if it exists, it tries to format it and throws a syntax error. The second is the exact same, with an extra ignored argument.

Looking at the code, I think this feature is implemented, but the command line isn't parsed correctly; `--print-config minimal` needs to consume an additional argument which is just the path to the new config. If it were parsed correctly, the behavior would be surprising, since it would both format the code and print a config (when I would expect `--print-config` to not modify the source code).

Also, note that there are no tests for either `--print-config default` or `--print-config minimal`.

**Comment by glmdgrielson** [comment]
I want to add that it seems to work with the `default` option. (as in, `rustfmt --print-config default rustfmt.toml` works)

**Comment by gurgalex** [comment]
To confirm the desired behavior.

Given a default `rustfmt.toml` generated by `rustfmt --print-config default rustfmt.toml`

1. Upon running `rustfmt --print-config minimal min_rustfmt.toml` it would output
only the config options used when dry-run formatting (doesn't change input) the current program (from stdin?). It would output the minimal config to `min_rustfmt.toml`.

2. Upon running `rustfmt --print-config minimal min_rustfmt.toml src/main.rs src/lib.rs` do the same as (1), but instead of from stdin, it would only output the config options used when formatting `src/main.rs` and `src/lib.rs`. No changes to either file. The output would be to the file `min_rustfmt.toml`.


```
        --print-config [minimal|default] PATH
                        Dumps a default or minimal config to PATH. A minimal
                        config is the subset of the current config file used
                        for formatting the current program.
```

**Comment by gurgalex** [comment]
^ @topecongiro

**Comment by scampi** [comment]
@gurgalex As of 679c8d5f106e8442bf8c4a54609a63df9eb3863c your first use case wouldn't do what you described: rustfmt just ignores the minimal path if no files to format are given.
