### ISSUE TITLE
Move away from string::len for computing the length of a line

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3235]
In https://github.com/rust-lang/rustfmt/issues/3224 the computation of the line length was errored because it relied on `String::len`, which ultimately had negative impact on the comment refactoring. This issue is to track the places where that needs to be fixed.
This list may be extended as additional places that need fixing are found:
- [x] the `wrap_str` method
- [x] the `rewrite_comment` method

**Comment by wada314** [comment]
Hello, I'm interested in this line length problem because I'm a CJK language user.
If no one has started to work on this, can I try work for fixing this str::len issue in this EOY holiday season? 
I'm assuming I just need to replace str::len with the crate unicode_width's methods, there's no complications.

If possible I also want to add a rustfmt option to switch the treating of "ambiguous characters" (UAX#11 4.2), but that seems to be bit hard work because I need to drag around the Config struct everywhere calling `wrap_str` and `rewrite_comment`, so that should be low-priority.

**Comment by nrc** [comment]
> If no one has started to work on this, can I try work for fixing this str::len issue in this EOY holiday season?

That would be great, thank you!

> I'm assuming I just need to replace str::len with the crate unicode_width's methods, there's no complications.

I would start this way. It might cause complications or not be sufficient, but it will need doing.

**Comment by scampi** [comment]
duplicate of #6
