### ISSUE TITLE
[unstable option] version

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3383]
Tracking issue for version

**Comment by scampi** [comment]
original issue: https://github.com/rust-lang/rustfmt/issues/2877

**Comment by topecongiro** [comment]
I would like to rename this option and/or change it so that it won't take a major version number as its value. 

Currently (the version `1.x`) rustfmt supports `version = "One"` or `version = "Two"`. If we release 2.0, then `version = "One"` will be deprecated and `version = "Three"` will be supported. Now the problem: every user whose rustfmt.toml contains `version` needs to update their file to keep the behavior of rustfmt as what they expecet.

I will list some candidates below which I have in my mind. Suggestions for better wording are welcome!

- `version = ["stable"|"nightly"]`
- `version = ["current"|"latest"]`
- `ues_latest_format_style = [true|false]`

**Comment by karyon** [comment]
This will need to be re-decided for 1.x

**Comment by tukusejssirs** [comment]
> I will list some candidates below which I have in my mind. Suggestions for better wording are welcome!
>
> * `version = ["stable"|"nightly"]`
> * `version = ["current"|"latest"]`
> * `ues_latest_format_style = [true|false]`

I suggest to use the following values:
- `nightly`: latest nightly release;
- `current`: current/latest major stable release;
- `previous`: previous (last but one) major stable release:
  - this one might be removed, however, you might want to add a way to add this option, as currently we can use the previous major release;
- `${major}`: match major version number:
  - value could be required to be a string if you want to use a single data type for `version` option;
  - for example `1`, `2`.

In order to remove the maintaince burden, support of `nightly`, `current` and `previous` might be supported only.

**Comment by mickvangelderen** [comment]
I am curious why this issue was reopneend. Is it possible to provide the motivation for re-opening this issue @karyon?

**Comment by karyon** [comment]
The PR was merged to the abandoned 2.x branch (which was master for a while). In the current master, the `version` config still exists: https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#version.

Heh, funny that you found that. I put my email address into my profile, feel free to shoot me a message!

**Comment by tgross35** [comment]
This will likely be superceded in some way by `rustfmt` editions, correct?

**Comment by calebcartwright** [comment]
> This will likely be superceded in some way by `rustfmt` editions, correct?

Correct, this is going to be replaced by a new `style_edition` option as per [RFC 3338](https://rust-lang.github.io/rfcs/3338-style-evolution.html). `version=Two` will be the equivalent to `style_edition=2024`, `version=One` will be the equivalent to `style_edition=(2015|2018|2021)`, and `version` will be soft-deprecated for some period of time with a warning and automatic mapping to the equivalent `style_edition` value.

<hr />

If anyone finds any issues with the existing `version` option then feel free to report here until we get `style_edition` in place, but going to close this since we won't be proceeding with stabilizing `version`
