### ISSUE TITLE
rustfmt fails on Rust 2018 "path clarity" submodules

### ISSUE THREAD

**Issue by mjbshaw** [rust-lang/rustfmt#3427]
I originally reported this in [#2407](https://github.com/rust-lang/rustfmt/issues/2407#issuecomment-468937767), but on further reflection I think it deserves its own issue. `rustfmt` fails for Rust 2018 submodules that don't use `mod.rs` (because of [path clarity](https://doc.rust-lang.org/nightly/edition-guide/rust-2018/module-system/path-clarity.html#no-more-modrs)). Example:

```
$ mkdir foo
$ touch foo/bar.rs
$ echo 'mod bar;' > foo.rs
$ rustfmt --edition 2018 foo.rs
error[E0583]: file not found for module `bar`
 --> /private/tmp/demo/foo.rs:1:5
  |
1 | mod bar;
  |     ^^^
  |
  = help: name the file either bar.rs or bar/mod.rs inside the directory "/private/tmp/demo"
```

For clarity, the file structure is:

```
$ tree
.
├── foo
│   └── bar.rs
└── foo.rs
```

Here, `foo.rs` is the Rust 2018 equivalent of Rust 2015's `foo/mod.rs`.

**Comment by topecongiro** [comment]
The rustc parser uses [`Parser::directory`](https://github.com/rust-lang/rust/blob/c9f8304351ad4223e4f618e9a329b2b94776b25e/src/libsyntax/parse/parser.rs#L236) in order to choose on which file to look at when parsing `mod foo;`.
This value is changed automatically when parsing a whole crate, so rustfmt does not have to modify it manually. On the other hand, when formatting an internal file within a crate, rustfmt needs to configure this value by itself. Unfortunately, the field's visibility is `crate` and there is no setter method for it, so we need to fix rustc first.
