### ISSUE TITLE
Format empty dyn without trailing space

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#3709]
```rust
macro_rules! token {
    ($t:tt) => {};
}

fn main() {
    token!(dyn);
}
```

As of current master, in 2018 edition mode rustfmt applies the following diff:

```diff
-     token!(dyn);
+     token!(dyn );
```

I would prefer for there not to be a trailing space inserted. @topecongiro -- I believe this should fall under #3333.

Affects the `Token!` macro in Syn.

**Comment by KamWithK** [comment]
I would like to fix this.
I've had a look at #3333 however can't find token!(dyn) in the diffs

**Comment by topecongiro** [comment]
@KamWithK Thanks! IIRC all you need to do is to flip the order of these two function calls:

https://github.com/rust-lang/rustfmt/blob/3adfb08afe3cb6a8c055e581dea87808464d1381/src/macros.rs#L306-L309

When you create a PR, please do not forget to add a test :). Also, note that this issue is reproducible only when we are using edition 2018.

**Comment by KamWithK** [comment]
Hey, just wanted to let you know that I won't be able to work on this as a result of my lack of time right now
