### ISSUE TITLE
`cargo fmt --all -- --check` issues error for crate that is not part of either the workspace or the path dependencies.

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/rustfmt#3725]
https://dev.azure.com/tokio-rs/Tokio/_build/results?buildId=1748&view=logs

```text
Diff in /usr/share/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-codec-0.1.1/src/bytes_codec.rs at line 1:
-use bytes::{Bytes, BufMut, BytesMut};
-use tokio_io::_tokio_codec::{Encoder, Decoder};
+use bytes::{BufMut, Bytes, BytesMut};
 use std::io;
+use tokio_io::_tokio_codec::{Decoder, Encoder};
```

toolchain: nightly-2019-08-01, (Probably [nightly-2019-07-18 and later](https://github.com/tokio-rs/tokio/pull/1335#issuecomment-513527214), it didn't happen in [nightly-2019-07-17 or earlier versions](https://github.com/tokio-rs/tokio/blob/63377e2110657fbfb085269f221836245755bdde/rust-toolchain#L1))

**Comment by calebcartwright** [comment]
Think I know why this one is happening (unintended side effect of https://github.com/rust-lang/rustfmt/pull/3664)

tokio-codec is a member of the top level workspace, but it's also separately consumed from crates by other dependencies in the broader dependency tree as seen in the `cargo metadata` output.

The check used for the `All` strategy is incorrectly including those non-local dependencies because the non-local dependency name (`tokio-codec`) also happens to match the name of a workspace member. Augmenting that check should resolve this issue
