### ISSUE TITLE
await operator on async block gets unexpected indentation

### ISSUE THREAD

**Issue by Follpvosten** [rust-lang/rustfmt#3765]
Using the latest nightly, this:

```rust
async {
    // Do
    // some
    // work
}.await;
```

Gets formatted to this:

```rust
async {
    // Do
    // some
    // work
}
    .await;
```

I would expect it to either stay in place (because `}.await;` isn't really a long line) or move one line done, but without the indentation.

**Comment by topecongiro** [comment]
We should update `is_block_expr` so that it returns `true` when passed `ast::ExprKind::Async(..)`:
https://github.com/rust-lang/rustfmt/blob/ad5d9fba9b6d5482e504e4996e2aea54defb9ed6/src/utils.rs#L447

Also we should stop using the wildcard pattern(`_`) when matching against the ast node so that we don't get this kind of errors.
