### ISSUE TITLE
Remove unnessecary parentheses

### ISSUE THREAD

**Issue by the10thWiz** [rust-lang/rustfmt#3823]
(Feature Request)
The compiler provides warnings for unnecessary parentheses, so it should be possible to add a feature that removes them while formatting. This would probably need an option defined because not everyone would want to remove their parentheses.

Typically, the compiler reports a warning for `if`, `for` and `while` statements, as in each of these examples:
```
if (a == b) {
}
for (a in b) {
}
while (a < b) {
}
```

At first glance, this seems like a good first issue, and I would be interested in trying to implement this myself.

**Comment by joshtriplett** [comment]
This seems like something better done with a rustfix suggestion from `rustc`, rather than via rustfmt.

**Comment by the10thWiz** [comment]
What do you mean? `rustc` already suggests removing them (Using the 'Unnessecary Parathentheses` phrasing). I was hoping that `rustfmt` could automatically remove them. I would also expect the config option for this would default to off.

**Comment by sinkuu** [comment]
`cargo fix` can automatically apply the rustc suggestion already. There can be reasons to replicate the feature in rustfmt though (e.g. works for syntactically-valid but errneous codes).

```
/t/foo $ cat src/main.rs
fn main() {
    if (true) {
        println!("hello");
    }
}

/t/foo $ cargo fix
    Checking foo v0.1.0 (/tmp/foo)
      Fixing src/main.rs (1 fix)
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s

/t/foo $ cat src/main.rs 
fn main() {
    if true {
        println!("hello");
    }
}
```

**Comment by the10thWiz** [comment]
I was not aware of Rust fix until now. Thanks for letting me know. I suspect that it doesn't need to be replicated into rustfmt. The only use case I can see (because the cases where rust fix doesn't work prevent rustfmt from working, as far as I know), is automatically applying the fix in the context of a Github hook or similar. I believe that automatically running `cargo fix` is sufficient, so it doesn't seem necessary.

**Comment by heguihua** [comment]
I hope the Rust compiler would allow the "unnecessary parentheses", for some reason, it improves the readability.

**Comment by sinkuu** [comment]
You can put `#![allow(unused_parens)]` at your crate root.

**Comment by joshtriplett** [comment]
In the meantime, I think we can safely close this issue, in favor of the recommendation to use `cargo fix`.

**Comment by heguihua** [comment]
"cargo fix" dose not make sense to those compulsion :-), it removes the desired parenthesis!

The extra parenthesis is not harmful and it improves the readability, maybe we have to fork a Rust compiler and apply the fix? 

```
diff --git a/src/librustc_lint/unused.rs b/src/librustc_lint/unused.rs
index 9f293bdaa10..ded027d4603 100644
--- a/src/librustc_lint/unused.rs
+++ b/src/librustc_lint/unused.rs
@@ -331,7 +331,7 @@ impl<'a, 'tcx> LateLintPass<'a, 'tcx> for UnusedAttributes {
 
 declare_lint! {
     pub(super) UNUSED_PARENS,
-    Warn,
+    Allow,
     "`if`, `match`, `while` and `return` do not need parentheses"
 }
```

**Comment by weisunding** [comment]
Hi all, I forked the compiler and made the change, it works! let's have more optimizations to Rust.
https://github.com/weisunding/rust (master)

**Comment by sinkuu** [comment]
Sorry for continuing off-topic, but I'm curious why you need to change the default. With lint-levels externally changed, your code still generates warnings for others. What is wrong with `#![allow]` attribute?

(By the way, it may be a code smell that `if`s look better with parenthesis (i.e. too long expression). I'd rather factor out the condition.)

**Comment by weisunding** [comment]
Sorry for off-topic.

unused parentheses are definitely no side-effect, so it should be the compiler's default. why not "#![allow(unused_parens)]" attribute?  since the extra code is unnecessary.

I think the Rustacean are minimalist, you use **fn** instead of **function**, **pub** and not **bar**, so I have more to do, such as

statement
`let mut i = 100;`
 will be changed to
 `mut i = 100;`


and more to do, thanks for discussion, you hearted people! 😀

**Comment by topecongiro** [comment]
Closing https://github.com/rust-lang/rustfmt/issues/3823#issuecomment-558756746.

**Comment by mgeisler** [comment]
> In the meantime, I think we can safely close this issue, in favor of the recommendation to use `cargo fix`.

As a data point, I'm currently working on a project where I'm generating Rust code. This is part of [Android](https://source.android.com/) and `rustfmt` is readily available to me in the build environment — but Cargo is not since Android doesn't use Cargo to build its Rust code.

I realize this is non-standard in the Rust ecosystem, but all large companies end up using `rustc` directly instead of relying on Cargo. So from that point of view, it's attractive to put features like this into tools other than Cargo.

**Comment by calebcartwright** [comment]
Thanks for sharing your perspective @mgeisler. Understand where you're coming from, but that's still an insufficient argument to justify duplicating functionality in another tool. `rustfix` is definitely the best place for this type of feature, and as noted, is already available there.

I recognize that `rustfix` isn't available as an executable binary outside a `cargo` context (at least AFAIK), but if there's a need/desire for being able to use rustfix separate from cargo (which would be fair IMO) then I think that's best taken up as a feature request for the rustfix team at https://github.com/rust-lang/rustfix/

**Comment by mgeisler** [comment]
> Understand where you're coming from,

Thanks! The extra parenthesis is not a showstopper for me — we'll either disable the lints for the auto-generated files, or we'll  put in the extra effort to not generate unnecessary parenthesis. I only found this issue since it occurred to me that perhaps `rustfmt` could simplify things for us.

> but that's still an insufficient argument to justify duplicating functionality in another tool.

I would not suggest duplicating anything — I would move the code from `cargo fix` to `rustfmt`.

> `rustfix` is definitely the best place for this type of feature, and as noted, is already available there.

Actually, that's not at all clear to me :smile: When I think of `rustfmt`, I think of a tool which modifies and normalizes the AST. This often means adding/removeing braces and commas, so I would not at all be surprised to see it also add/remove  parenthesis.

On the other hand, my conceptual model of `cargo fix` is that it does much more complex and semantic operations on the AST. As an example, it has knowledge about differences between the editions and it can thus edit the code to move from one edition to the next. That is the kind of operation that I would not expect `rustfmt` to do since it's way outside the scope of "formatting".

> if there's a need/desire for being able to use rustfix separate from cargo (which would be fair IMO) then I think that's best taken up as a feature request for the rustfix team at https://github.com/rust-lang/rustfix/

Good point, I'll open an issue there to at least register this potential problem. I thing the problem will only grow in the future as more large companies integrate `rustc` into their build tools.

**Comment by calebcartwright** [comment]
> Actually, that's not at all clear to me smile When I think of rustfmt, I think of a tool which modifies and normalizes the AST. This often means adding/removeing braces and commas, so I would not at all be surprised to see it also add/remove parenthesis.
>
> On the other hand, my conceptual model of cargo fix is that it does much more complex and semantic operations on the AST.
> I would not suggest duplicating anything — I would move the code from cargo fix to rustfmt.

A good way to think about it is that rustfix is typically the "right" home for autofixing something the compiler complains about.

Yes, both operate on the AST, but we wouldn't want to remove rustfix's existing ability to fix a compiler lint and move that into a different tool (e.g. rustfmt) just because it's feasible to implement that feature in said tool, and that tool can be invoked independently of cargo
