### ISSUE TITLE
deprecate skip_children option

### ISSUE THREAD

**Issue by scampi** [rust-lang/rustfmt#3893]

**Comment by jsgf** [comment]
Why? We're actively using it to format individual files. Is there some other way to get this functionality?

**Comment by calebcartwright** [comment]
@jsgf - the new default behavior of `rustfmt` v2.0 will be to not format sub modules (`skip_children`) which is why the config option is being deprecated.

An `-r/--recursive` flag will be added, basically inverting things: rustfmt 2.0 will be disabled by default with an optional opt-in, wheras rusftmt 1.x is enabled by default with an optional opt-out

See also https://github.com/rust-lang/rustfmt/issues/3587

**Comment by jsgf** [comment]
Ok that's great!

**Comment by jeffomatic** [comment]
For folks that are using `rustfmt` for format-on-save workflows, and are aren't using either 2.0 or the nightlies, here's a script that will emulate `--skip-children`:

https://gist.github.com/jeffomatic/fa443170b856b1af5ca3aa67e0ea3e65

Hope ya'll don't mind me posting here. I found this thread after stumbling upon `rustfmt`'s somewhat surprising behavior of emitting formatted source of a file's dependencies.
