### ISSUE TITLE
Bumping syntax-ap crates fails due to reduced visiblities

### ISSUE THREAD

**Issue by josephlr** [rust-lang/rustfmt#3903]
I'm trying to fix https://github.com/rust-osdev/uefi-rs/pull/104#issuecomment-548789808.  Rustfmt needs a new engough `syntax` to support `"efiapi"`. I tired to do what https://github.com/rust-lang/rustfmt/pull/3870 did and bump `rustc-ap-syntax` to version `626`.

This caused a very large number of compiler errors. Some of them are caused by small changes like: https://github.com/rust-lang/rust/commit/742ec4b9bf7ae7d693da7fe75e5f974e0fafb9d0, which are easy enough to fix. However, others errors are caused by changes like https://github.com/rust-lang/rust/commit/c189565edc5c9fc516170885b3a3061b936205fb that make a bunch of `libsyntax`'s functionality private. 

What should I do here? Should the `libsyntax` commits be reverted in the main rust-lang/rust repo?

CC: @Centril

**Comment by calebcartwright** [comment]
This looks like it may be tricky. Do you know the first/earliest version of rustc-ap that supports `efiapi`?

IIRC rustfmt 1.4.9 is using 606 and the latest on master has been bumped to 610, but the visibility changes in 626 appear very problematic

**Comment by topecongiro** [comment]
@josephlr Thank you for the report. I am aware of the visibility issue, and was planning to fix the issue once he refactoring thing has settled. We need to re-export everything we need in the libsyntax, adding comments to make sure they won't become private or removed in the future.

**Comment by topecongiro** [comment]
cc https://github.com/rust-lang/rust/pull/65324.

**Comment by mati865** [comment]
@topecongiro IIUC this will block updating currently broken RLS.
If I'm correct this should be prioritised.

**Comment by est31** [comment]
@josephlr @mati865 if it helps you, the latest version that doesn't have https://github.com/rust-lang/rust/commit/c189565edc5c9fc516170885b3a3061b936205fb yet is 615, and the latest version that doesn't have https://github.com/rust-lang/rust/commit/742ec4b9bf7ae7d693da7fe75e5f974e0fafb9d0 either is 612.

efiapi was merged much later in https://github.com/rust-lang/rust/commit/2dd4e7320e620dc9a59423c55a7db3520ba8b553

**Comment by topecongiro** [comment]
@mati865 I do not think this is blocking the broken RLS as AFAIK RLS does not directly depend on rustc-ap-* crates.

**Comment by topecongiro** [comment]
For anyone interested in tackling this issue, here are the instructions:

1. Fork & clone this repo.
2. Edit `Cargo.toml` and bump the version of [rustc-ap-* crates](https://github.com/rust-lang/rustfmt/blob/cc0b060739612694a7bd33b2ab12912688c85198/Cargo.toml#L67-L82) to the latest version.
3. Run `cargo check`. You will see TONS of compiler errors. Fix them if possible. For unfixable ones, we need to update the rustc source code.
4. Fork & clone https://github.com/rust-lang/rust.
5. Update [libsyntax](https://github.com/rust-lang/rust/tree/master/src/libsyntax) so that rustfmt can access structs/functions and methods that it depends on. Add a comment on each one of them so that they won't get hidden in future development (e.g., `// Keep this public for external tools like rustfmt.`).
6. Send a PR to the rustc repo.
7. Wait for the PR to get merged & wait for the rustc-ap-* crates to be published. Note that regularly rustc-ap-* crates are published once a week (https://crates.io/crates/rustc-ap-syntax). 
8. Come back to the rustfmt repo, bump the version of rustc-ap-* crates and see if everything works. If not, go back to 5 😞

**Comment by topecongiro** [comment]
This is blocked by https://github.com/alexcrichton/rustc-auto-publish/issues/14. cc @calebcartwright.

**Comment by calebcartwright** [comment]
@rchaser53 are you working on this one too? (asking based on https://github.com/rust-lang/rust/issues/67653).

 I've got a good chunk of the changes made locally, mostly waiting to see how the new librustc_parse crate will become available. 

If you're further along though I'm happy to stop and let you take it, just want to make sure we aren't duplicating efforts!

**Comment by rchaser53** [comment]
Oh sorry😅
I have just started implementation, so I will stop it.

**Comment by calebcartwright** [comment]
@topecongiro - this can be closed with #4043 being merged

**Comment by calebcartwright** [comment]
Closed via #4043
