### ISSUE TITLE
Why would rustfmt change "multiple child in one line" to multiple lines?

### ISSUE THREAD

**Issue by CliffHan** [rust-lang/rustfmt#3957]
Before "cargo fmt":
```
    if !arc_manager.lock().unwrap().config.condition.function_enabled {
        return;
    }

```
The length was 72, and after "cargo fmt":
```
    if !arc_manager
        .lock()
        .unwrap()
        .config
        .condition
        .function_enabled
    {        
        return;
    }
```

**Comment by calebcartwright** [comment]
Hi @CliffHan - There are other factors rustfmt takes into consideration for formatting beyond just the line length.

Based on the rustfmt config options, there are additional width heuristics internally calculated which set an upper limit on the max length for things like attributes, functions, as well as chains like in your snippet. 

Even though the length of the chain in your snippet does not exceed the `max_width` config value, it is still being wrapped to multiple lines because the length exceeds the calculated max chain width allowed on a single line. 

If you'd really prefer to keep the original formatting of your chain on one line then you have a few options:
* increase the [`max_width`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#max_width) value in your rustfmt config file
* leverage the [`use_small_heuristics`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#use_small_heuristics) config option (try using `Off` or `Max`) which is used for those internal max calculations.
* have rustfmt ignore that block altogether via `#![rustfmt::skip]`:
```rust
   #![rustfmt::skip]
    if !arc_manager.lock().unwrap().config.condition.function_enabled() {
        return;
    }
```

**Comment by CliffHan** [comment]
Thanks for you explanation
