### ISSUE TITLE
How to downgrade rustfmt format?

### ISSUE THREAD

**Issue by nifker** [rust-lang/rustfmt#3997]
When I try to format a specific crate I get this error "Error: rustfmt version (1.4.11) doesn't match the required version (1.4.9)". But I cant seem to find any information on how I can use an older version of rustfmt.

**Comment by calebcartwright** [comment]
Do you know if that crate specifically needs v1.4.9? If not, the easiest approach would probably be to just remove the `required_version` option from the rustfmt.toml config file, or to change that value to 1.4.11.

If you do need to use a specific, older version then I suppose one way would be to grab rustfmt from crates.io (https://crates.io/crates/rustfmt-nightly) instead of via rustup. You'd probably want to first remove the component `rustup component remove rustfmt` before installing it from crates.io too

**Comment by nifker** [comment]
Yes it does. But version 1.4.9 seems not to be able to compible. https://paste.gg/p/anonymous/f5f8246ea2424bc78143eef1ad2bd6fd

**Comment by calebcartwright** [comment]
Are you trying to build rustfmt from source? If so make sure you include the `--locked` flag with cargo

**Comment by nifker** [comment]
Yes, but that doesn't solve the compilation error. Where are the binaries located?

**Comment by calebcartwright** [comment]
> Yes, but that doesn't solve the compilation error.

I guess the lockfile fix wasn't backported to 1.4.9 then. If you run `cargo update -p crossbeam-utils --precise 0.6.5` and then run a cargo build on the sources (with the `--locked` flag) then it should compile. 

> Where are the binaries located?

You should be able to get them from crates.io, linked in my previous response

**Comment by nifker** [comment]
Ill close this issue for now
