### ISSUE TITLE
rustfmt dies on this line of code

### ISSUE THREAD

**Issue by sanbox-irl** [rust-lang/rustfmt#4073]
Hello!

```rs
    let mut staff_card = foo.staff_card_hand.pick_out_card(&staff_card_name).ok_or_else(|| 
        format_err!("We didn't have a valid card, or the card we tried to play is something the player doesn't have!")
    );
```

Please especially note the ` ` after the `||`. Without that, this formats just fine.

Additionally, my rustfmt.toml is:

```toml
max_width = 110
edition = "2018"
```

Changing almost any part of the above sample causes it to format correctly. I cannot narrow it down any further -- it seems to have something to do with line length, or maybe even the shape of the call?

**Comment by calebcartwright** [comment]
When you say that rustfmt "dies", does that mean that rustfmt is giving you an error, or simply that the formatting is left unchanged?

**Comment by sanbox-irl** [comment]
Ah sorry for not being clearer -- It fails to format the entire file if that line is there

**Comment by sanbox-irl** [comment]
It does not hard crash or anything like that.

**Comment by calebcartwright** [comment]
There's a known existing issue in rustfmt wherein if the formatted result of any single chain element exceeds the value of `max_width` then rustfmt will fail to format the entire chain, maintaining the original snippet for the chain. 

However, that only applies to that individual chain, and the rest of the file should be formatted. 

Separately, I would've thought rustfmt would emit an error as a result of the empty trailing space in that case 🤔 

Are you able to share the broader file or example that shows rustfmt failing to format other items in the file?

With something like this, rustfmt will indeed ignore the chain (due to the issue discussed above) but the `foo` function formatting is still updated
```rust
fn main() {
    let mut staff_card = foo.staff_card_hand.pick_out_card(&staff_card_name).ok_or_else(|| 
        format_err!("We didn't have a valid card, or the card we tried to play is something the player doesn't have!")
    );
}

fn foo (  ) {  }
```

**Comment by calebcartwright** [comment]
Closing in favor of  #3863
