### ISSUE TITLE
doc website: stable options should indicate since when they're stable

### ISSUE THREAD

**Issue by majewsky** [rust-lang/rustfmt#4154]
I just saw this warning message:

```
$ cat rustfmt.toml
max_width = 100
chain_width = 80
$ rustfmt --edition 2018 src/main.rs
Warning: Unknown configuration option `chain_width`
```

This was surprising to me because, according to https://rust-lang.github.io/rustfmt/#chain_width, the `chain_width` option is stable. However, it appears that the documentation for `chain_width` was only added a few days ago in f1a44c5a32, i.e. after the release from which my rustfmt was built.

To avoid this confusion, it would be great if the doc website did not just say `Stable: yes` on stable options, but something like `Stable: since $VERSION` or `Stable: since $DATE`.

**Comment by calebcartwright** [comment]
Hi @majewsky, this actually due to the difference between what's been released and what hasn't (not stable vs. unstable). The Configuration options listed in https://github.com/rust-lang/rustfmt/blob/master/Configurations.md and http://rust-lang.github.io/rustfmt/ are reflective of the latest in source control, and not what's been published in a released version of rustfmt.

If you want to use `chain_width` today then you'll have to use rustfmt 2.0 and will have to build from source.

I'll add a note to these configuration pages to make that more clear, but the documentation of version/release specific config options is something we'll need to address as part of #4128 given the additional vectors. 

Going to close this and track in #4128
