### ISSUE TITLE
Change default for `use_try_shorthand` to true?

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rustfmt#4205]
Given that the `try!` macro [has been deprecated](https://github.com/rust-lang/rust/pull/62672/) since rustc 1.39.0 (~6 months ago), would it make sense to change the default for this to `true`? I see there's a 2.0 release upcoming — perhaps that's a decent time to make the change?

**Comment by topecongiro** [comment]
Sounds good to me.

**Comment by topecongiro** [comment]
Ah, sorry, I thought that the option is unstable, but it's already stabilized. In that case, I would rather keep the current behavior.

Thank you for your suggestion, but we will close this as won't fix.

**Comment by jhpratt** [comment]
That's why I'd suggested it as a possible change for 2.0, as I presume breaking changes are fine then?

**Comment by jhpratt** [comment]
@topecongiro Is my previous comment not the case? I would assume breaking changes are allowed in a semver-major version bump. If not, what's the purpose behind having a 2.0.0 release?

**Comment by jhpratt** [comment]
Reopening so the possibility of breaking changes in 2.0 can be addressed.

**Comment by jhpratt** [comment]
Looks like I'm not able to reopen this to address the previous point. @topecongiro can it please be addressed?

**Comment by topecongiro** [comment]
Sorry for the late reply. As you mentioned, it is possible to add breaking changes to 2.0 release (in fact, we are planning to make quite a few numbers of breaking changes).

I've reconsidered changing the default value of `use_try_shorthand`. I still think that the default value should be `false` by default.

There are mainly two reasons. One is that I would like to minimize the possibility of breaking the code or changing the semantic of the code when using the default configuration option. In this regard, converting the `try!` macro to the `?` operator may break the code against something like the following:

```rust
macro_rules! try {
    ($val:expr) => {
        println!("{:?}", $val);
    }
}

fn main() -> std::io::Result<()> {
    try!("hello, world");
    Ok(())
}
```

I understand that the code like this does not appear in practice, though I would like to be conservative here.

Also, I think that converting `try!` to `?` is often a one-time operation, rather than something that needs to be repeated. For historical reasons, rustfmt has this option, but in retrospect, this kind of conversion should be the responsibility of tools like `rustfix`.

Again, I wholeheartedly thank you for your comment and willingness to improve rustfmt. Your comment allowed me to rethink about this config option.
