### ISSUE TITLE
Direct AST usage?

### ISSUE THREAD

**Issue by piranna** [rust-lang/rustfmt#4217]
I know that rustc libsyntax API is unstable on purposse, but i'm trying to do a Code generator and can't find docs for It. My idea was to generate a Rust AST and later use rustfmt to do the final conversion to Rust code, but reading rustfmt code i can't find how to do It. I've seen projects like codegen and codespawn, but they are low level and incomplete regarding Rust syntax, and not only i would need to complete them but also doing the AST conversión myself. Is there any sample code or instructions about how and where inject an AST to rustfmt? And some sample about building a compatible AST would be nice too... :-)

**Comment by ayazhafiz** [comment]
I don't think there is a public API that takes an ast right now. The first entry point for an ast is in `src/formatting#format_file`, which takes an `ast::Crate`.

https://github.com/rust-lang/rustfmt/blob/2d0ea2f3341e5a79c4d8a3eb66f3108eace44d6b/src/formatting.rs#L154-L162

**Comment by calebcartwright** [comment]
Thank you for the question @piranna. My TL;DR answer would be to use something other than rustfmt for your use case. rustfmt is first and foremost a check/formatter of existing rust code, not a code generator.

Also note that libsyntax was split apart into several smaller mods within the rustc source tree some time back.

rustfmt uses several of the internal rustc modules, including the rustc parser to generate an AST (this is the very same AST used [internally within rustc](https://github.com/rust-lang/rust/tree/master/src/librustc_ast)) for the specified input file(s). Since expansion was moved out of the parser  we also have to use additional parser and, in some instances, expansion utils to load out-of-line mods (those defined in other files). 

The end result of that process is a mapping of file names to their corresponding [mod](https://docs.rs/rustc-ap-rustc_ast/660.0.0/rustc_ap_rustc_ast/ast/struct.Mod.html), as well as some crucial components (like the [SourceMap](https://docs.rs/rustc-ap-rustc_span/661.0.0/rustc_ap_rustc_span/source_map/struct.SourceMap.html)) that are generated by the parsing stage.

Those items are then used to generate and emit the corresponding formatting.

> Is there any sample code or instructions about how and where inject an AST to rustfmt

@ayazhafiz is correct, this is not possible today, so there is of course not any samples nor instructions.

rustfmt operates via the process I described above. I suppose it could be _technically_ possible for the rustfmt lib API to accept all of the inputs eumerated above and use those for formatting. However, doing so would likely require a non-trivial amount of new code as well as refactoring of existing code, and I'm not convinced it's worth the effort. 

> And some sample about building a compatible AST would be nice too... :-)

Sorry but this is really outside the scope of rustfmt. As far as references or samples you could try reviewing the source and/or docs for the AST mod itself and perhaps the parser code, but any such questions would be best addressed to the lang and/or compiler teams.

https://docs.rs/rustc-ap-rustc_ast/660.0.0/rustc_ap_rustc_ast/index.html
https://github.com/rust-lang/rust/tree/master/src/librustc_ast
https://github.com/rust-lang/rust/tree/master/src/librustc_parse


I'm inclined to close this as `wont-fix`, but cc @topecongiro for your thoughts

**Comment by topecongiro** [comment]
As far as I know, the current rustc frontend implementation is not designed with code-generation in mind, and it's a real pain to work with outside of the rustc. I suggest using alternative libraries like syn or ra-parse, and just call rustfmt against the output.

**Comment by calebcartwright** [comment]
I'm going to close this given the above discussion, though please let us know if you have any questions @piranna!
