### ISSUE TITLE
Comment removed between type name and =

### ISSUE THREAD

**Issue by ayazhafiz** [rust-lang/rustfmt#4244]
```rust
pub type Export /*: Bound */ = S1;
```

This is one where I think a comment *is* justified; today we do not enforce such bounds (i.e. the compiler does not check that the right-hand side of a `type` definition actually conforms to such a bound), and the compiler actually errors if you try to include it (because we don't want people to mistakenly think that such bounds are enforced).

But the comment here serves a useful purpose (about the *intent*, that we intend for this type definition to conform to the bound).

_Originally posted by @pnkfelix in https://github.com/rust-lang/rustfmt/issues/2781#issuecomment-629384358_

**Comment by calebcartwright** [comment]
For anyone interested in working on this, here are some of the relevant sections of the code:
rewrite_type
https://github.com/rust-lang/rustfmt/blob/2927e89b5194ecc887d61249eed9739ff1c3a3d5/src/formatting/items.rs#L1591-L1599

The dropping of the comment happens here on this line when the current formatting result is mashed together with the assignment operator. The individual elements of the item (the visibility, ident, generics, generic bounds, etc.) are formatted independently and then combined, but the comment is dropped because there's no checking for comments within the spans between. In this particular case that happens to be the span between the item's ident and the assignment operator, though more generally this would be the span between the assignment operator on the hi and the lo would be the end of the rightmost item element present
https://github.com/rust-lang/rustfmt/blob/2927e89b5194ecc887d61249eed9739ff1c3a3d5/src/formatting/items.rs#L1650

Note that the full span of the item can be found in the corresponding match arm in visitor.rs, which is needed for finding this between span before the assignment operator
https://github.com/rust-lang/rustfmt/blob/2927e89b5194ecc887d61249eed9739ff1c3a3d5/src/formatting/visitor.rs#L599-L611
