### ISSUE TITLE
JSON output for removing blank lines is wrong

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/rustfmt#4259]
Rustfmt version: `rustfmt 2.0.0-rc.2-nightly (e9b039ea 2020-06-03)`

If Rustfmt decides to remove a blank line, the JSON output says that actually nothing needs to change. Trivial repro:

```
 ~ cat foo.rs
fn foo() {

    let i = 0;
}
 ~ rustfmt --emit json foo.rs | jq
[
  {
    "name": "/Users/me/foo.rs",
    "mismatches": [
      {
        "original_begin_line": 2,
        "original_end_line": 2,
        "expected_begin_line": 2,
        "expected_end_line": 2,
        "original": "",
        "expected": ""
      }
    ]
  }
]
```

It seems fine at removing newlines in other cases:

```
 ~ cat foo.rs
fn foo() {
    let i =
    0;
}
 ~ rustfmt --emit json foo.rs | jq
[
  {
    "name": "/Users/timh/foo.rs",
    "mismatches": [
      {
        "original_begin_line": 2,
        "original_end_line": 3,
        "expected_begin_line": 2,
        "expected_end_line": 2,
        "original": "    let i =\n    0;",
        "expected": "    let i = 0;"
      }
    ]
  }
]
```

So I think the output should be something like this:

```
[
  {
    "name": "/Users/me/foo.rs",
    "mismatches": [
      {
        "original_begin_line": 2,
        "original_end_line": 3,
        "expected_begin_line": 2,
        "expected_end_line": 2,
        "original": "\n",
        "expected": ""
      }
    ]
  }
]
```

**Comment by Timmmm** [comment]
Here's another case that causes issues. It seems like there should be newlines that get stripped.

```
 ~ cat foo.rs
mod a;
mod c;
mod b;
mod d;
 ~ rustfmt --emit json foo.rs | jq
[
  {
    "name": "/Users/timh/foo.rs",
    "mismatches": [
      {
        "original_begin_line": 2,
        "original_end_line": 2,
        "expected_begin_line": 2,
        "expected_end_line": 2,
        "original": "mod c;",
        "expected": ""
      },
      {
        "original_begin_line": 4,
        "original_end_line": 4,
        "expected_begin_line": 3,
        "expected_end_line": 3,
        "original": "",
        "expected": "mod c;"
      }
    ]
  }
]
```

I think it's trying to reformat it alphabetically, like

```
mod a;
mod b;
mod c;
mod d;
```

But what you actually get is

```
mod a;
mod b;
mod c;mod d;
```

I think both instances of `"mod c;"` should actually be `"mod c;\n"`.

**Comment by calebcartwright** [comment]
Thanks for the report @Timmmm, and for giving the rustfmt 2.0-rc a test drive!

> I think it's trying to reformat it alphabetically, like

Yup, the default behavior is to reorder mods alphabetically, and this can controlled by the [reorder_modules](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#reorder_modules) configuration option.

> If Rustfmt decides to remove a blank line, the JSON output says that actually nothing needs to change. 

Not exactly. The fact that there's mismatches in the output is indicative that something _does_ need to be changed, it's just ambiguous what those changes are. I feel the question is really about how newline changes should be represented in the output, whether implicit/assumed given the line numbers, or explicitly.

It's clearly not explicit right now, and the scenarios you've shared here raise some good points about why IMO something should change. In addition to the removal of newline chars, it'd also be tricky to know from the json output when a newline is _inserted_, especially since rustfmt could be emitting different newline styles depending on the config. 

The json emit mode (which is also used with `--message-format json` from `cargo fmt`) is still unstable, so we'll want to get this sorted before stabilizing the json emit mode. Within the rustfmt maintainer team we've got a lot of higher priority items on our plates right now so it'd probably be a while before we can get around to this.

If anyone's interested and willing to try updating this that would be fantastic and we'd be happy to offer assistance!

The mismatch specification logic for the json emit mode can be found here:
https://github.com/rust-lang/rustfmt/blob/cf1f0cf10f8ecafda9ceda622c4a1d2b95636cad/src/emitter/json.rs#L57-L102

It may also be helpful to cross reference the [function that generates the visual output found with the `--check` mode](https://github.com/rust-lang/rustfmt/blob/master/src/emitter/rustfmt_diff.rs#L183).

**Comment by Timmmm** [comment]
Thanks for the hint! Turns out the fix was quite easy. :-)
