### ISSUE TITLE
Confusing indentation in match arm when a block is used as an expression

### ISSUE THREAD

**Issue by ohazi** [rust-lang/rustfmt#4277]
I wrote this:
```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => {
        match param.starts_with("0x") {
            true => usize::from_str_radix(&param[2..], 16),
            false => param.parse(),
        }
        .map(|parsed| ConId::Id(parsed))
        .map_err(|e| format!("con_id: {}", e))
    }
}
```

and rustfmt turned it into this:
```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => match param.starts_with("0x") {
        true => usize::from_str_radix(&param[2..], 16),
        false => param.parse(),
    }
    .map(|parsed| ConId::Id(parsed))
    .map_err(|e| format!("con_id: {}", e)),
}
```

Removing the enclosing braces from the `param => {...}` arm is fine, but the resulting indentation seems confusing, because the `.map` and `.map_err` calls are indented to the same level as the parent match arms. I would have expected something closer to this:
```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => match param.starts_with("0x") {
            true => usize::from_str_radix(&param[2..], 16),
            false => param.parse(),
        }
        .map(|parsed| ConId::Id(parsed))
        .map_err(|e| format!("con_id: {}", e)),
}
```

The same thing happens if I replace the `match` with an `if`:
```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => if param.starts_with("0x") {
        usize::from_str_radix(&param[2..], 16)
    } else {
        param.parse()
    }
    .map(|parsed| ConId::Id(parsed))
    .map_err(|e| format!("con_id: {}", e)),
}
```

So this seems to have something to do with using a block-like thing (`match ... {}`, `if ... {} else {}`) as an expression at the top of a match arm, which I guess isn't very common. 

Is this expected behavior? Normally I would expect at least one level of indentation until either the next match arm, or until some closing `}`,`)`,`,` symbols immediately above the next match arm. 

Playground link (match):
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0f0302f5d6d1431ea6769ffdddc996c1
Playground link (if):
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b1d111e43cbe3cf492f78cf6fd8bcdcb

**Comment by ayazhafiz** [comment]
I think this is reasonable to expect. For example, if the block is replaced with another expression, there is some indentation:

```rs
fn main() {
    match input {
        "__focused__" => Ok(ConId::Focused),
        param => fncall()
        .map(|parsed| ConId::Id(parsed))
        .map_err(|e| format!("con_id: {}", e)),
    }
}
```

goes to

```rs
fn main() {
    match input {
        "__focused__" => Ok(ConId::Focused),
        param => fncall()
            .map(|parsed| ConId::Id(parsed))
            .map_err(|e| format!("con_id: {}", e)),
    }
}
```

**Comment by calebcartwright** [comment]
Though I understand the subjective nature on this one, I feel like this is in alignment with the style guide. I also suspect it's really the chain items at play here more so than the match block. 

https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#match

The match arms are supposed to be single block indented and the closing `}` should be aligned as well, but your proposed/requested formatting would violate both of those and would not be in accordance with the style guide:

```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => match param.starts_with("0x") {
            true => usize::from_str_radix(&param[2..], 16),
            false => param.parse(),
        }
        .map(|parsed| ConId::Id(parsed))
        .map_err(|e| format!("con_id: {}", e)),
}
```

That style of indentation would also look rather odd in the absence of the chained calls

```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => match param.starts_with("0x") {
            true => usize::from_str_radix(&param[2..], 16),
            false => param.parse(),
        }
}

pub(crate) fn to_expr(&self) -> Option<&'a ast::Expr> {
    match self {
        OverflowableItem::Expr(expr) => Some(expr),
        OverflowableItem::MacroArg(macro_arg) => match macro_arg {
                MacroArg::Expr(ref expr) => Some(expr),
                _ => None,
            },
        _ => None,
    }
}
```

It's also expected that chain elements that follow a multiline element (and in this case the nested match expression is a chain parent item) that the subsequent chain elements are aligned to that element on their own line.

https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#multi-line-elements

@ayazhafiz - your example is not exactly the same because the chain parent can fit on a single line. You'd need a  parent element that would have to be formatted multilined as well. For example:

```rust
fn main() {
    match input {
        "__focused__" => Ok(ConId::Focused),
        param => fncall("foooooooooooooooooooooo", "barrrrrrrrrrrrrrrr", "bazzzzzzzzzzzz", "quxxxxxxxxxxxxxxxxx")
        .map(|parsed| ConId::Id(parsed))
        .map_err(|e| format!("con_id: {}", e)),
    }
}
```

becomes 

```rust
fn main() {
    match input {
        "__focused__" => Ok(ConId::Focused),
        param => fncall(
            "foooooooooooooooooooooo",
            "barrrrrrrrrrrrrrrr",
            "bazzzzzzzzzzzz",
            "quxxxxxxxxxxxxxxxxx",
        )
        .map(|parsed| ConId::Id(parsed))
        .map_err(|e| format!("con_id: {}", e)),
    }
}
```

**Comment by ayazhafiz** [comment]
Ah, good points @calebcartwright. Thank you for linking the style guide; I should have looked into that. I totally agree with your observations.

In particular, this example from the style guide demonstrates that the style is expected:

```rust
match foo {
    // A combinable expression.
    foo => a_function_call(another_call(
        argument1,
        argument2,
    )),
    // A non-combinable expression
    bar => {
        a_function_call(
            another_call(
                argument1,
                argument2,
            ),
            another_argument,
        )
    }
}
```

**Comment by ohazi** [comment]
Thanks, @calebcartwright -- Your observation that a lack of chained calls would put the closing brace in a weird position makes sense. However, I'm not sure I would expect the indentation to be the same with and without chained calls. 

Regarding:
> The match arms are supposed to be single block indented and the closing } should be aligned as well

Is it accurate to describe what I've written as a single block? I can see how `match ... {}` by itself could be described as a block. But as soon as you add the chained calls, I don't see it as a block anymore, I see it as a multi-line expression. The guide refers to a "*closing* brace," but it's not a closing brace if it's followed by chained calls and a comma. The fact that rustfmt inserts the comma also seems to suggest that this should be seen as a multi-line expression and not a block. 

I also take more issue with treating `if ... {} else {}` as a block here, because now the closing braces of *both* the `if` and the `else` end up at the same indentation level as the match arms. The closing brace of the `if {}` is arguably not the closing brace of the whole block, because it's followed by more stuff (namely, the `else {}`). But it would also be super weird to have the closing braces of the `if` and the `else` be at different indentation levels. 

---

I guess this boils down to "what is the intent of the language in the style guide?" From my reading, the *intended* goal seems to be to make the LHS of every match arm highly visible. 

This can be accomplished by indenting everything that isn't either a match arm or *one* line of terminating braces above a match arm. But if we're also putting non-terminating braces and chained calls at the same indentation level as the match arm, then I think we're starting to lose sight of that intended goal. 

Now, maybe I have it wrong, and that's not actually the goal. But if this is the goal -- then I think there may be a problem with either the text of the style guide, or with the behavior of rustfmt, because the current interpretation/behavior appears to allow for more clutter than I would otherwise expect.

**Comment by calebcartwright** [comment]
> Is it accurate to describe what I've written as a single block?

Block indentation is a term used throughout the style guide to refer to indentation, and should not be confused with a block code construct.

**Comment by ohazi** [comment]
> Block indentation is a term used throughout the style guide to refer to indentation, and should not be confused with a block code construct.

Okay, sorry, that makes sense. 

How should I interpret "closing }"?

**Comment by calebcartwright** [comment]
> How should I interpret "closing }"?

Not sure if I'm answering the right question, but my previous comment was a reference to the closing brace for the match expression. 

Within the AST for your snippet, the `"param"` arm of your top level match expression has a body that is itself a match expression and also has  multiple method call expressions (a chain). As such it's subject to the style requirements for both matches and chains; the requirements for matches can't be violated because of the chain, nor can the requirements for chains be violated because of the match.

As I mentioned before, match formatting tends to be one of the more subjective areas and I can understand the desire for the extra indentation to provide more visual distinction between match arms and the body of any one arm.

However, the formatting you are seeing is expected and correct as defined by the style guide.

rustfmt's defaults must adhere to the style guide which goes through an RFC process to establish the "official" style for Rust. If you'd really like to get formatting changed (specifically double block indentation for match arms and block idented closing brace either always or in certain situations) then I'd recommend submitting a proposal in the style guide repository.

**Comment by ohazi** [comment]
Okay, this makes more sense. Thanks.
