### ISSUE TITLE
Async gets removed from extern blocks.

### ISSUE THREAD

**Issue by rodrigorc** [rust-lang/rustfmt#4288]
**Describe the bug**

The `async` keyword is removed when used inside an `extern "C"` block.

Currently this is not valid in Rust, because in C there are no async functions. But when using `wasm-bindgen` it is processes from a macro, and the functions are actually Javascript, not C, and there there are JS promises. Anyway, even if it is not valid, the keyword should not be removed while formatting.

**To Reproduce**

Format the following code:
```rust
extern "C" {
    async fn foo();
}
```
And see how the `async` keword disappears.

**Expected behavior**

It should keep the `async` keyword.

**Meta**

- rustfmt version: 1.4.15-beta (530eadf 2020-06-02)
- From where did you install rustfmt?: Rustup
- How do you run rustfmt: From console: `rustfmt --edition 2018 test.rs`

**Comment by calebcartwright** [comment]
The root cause is that the fields from the `FnHeader` aren't leveraged in the format handling for functions in extern blocks so qualifiers like asyncness are dropped. I believe this was done intentionally given that such qualifiers are not valid Rust code (as you noted in the issue description), and rustfmt's focus on working with and formatting valid Rust code.

However, we could certainly tweak this to support maintaining the original qualifier, and it'd be up to users to remove their invalid usage of it (outside the wasm context) vs. rustfmt removing it for them.

The relevant code for anyone interested in working on this can be found here:

https://github.com/rust-lang/rustfmt/blob/144c9ec57583bbeae836f28e7c203f0ff5f3446c/src/formatting/items.rs#L3136-L3144

https://github.com/rust-lang/rustfmt/blob/144c9ec57583bbeae836f28e7c203f0ff5f3446c/src/formatting/items.rs#L237-L252

IMO the values set via `FnSig::new` still feel like a reasonable/correct set of defaults, especially considering that rustfmt's focus is on formatting valid rust code. Perhaps it could be augmented or another `from_*` function could be added for building a FnSig geared towards formatting foreign item fns and then leverage that (instead of `new`) accordingly.

**Comment by ayazhafiz** [comment]
Shoot, sorry @topecongiro, I had started working on this before you assigned yourself and failed to see your assignment. Feel free to close my PR if you'd like. Apologies for the duplication of work.
