### ISSUE TITLE
Regression, tail call formatting

### ISSUE THREAD

**Issue by KarlisZ** [rust-lang/rustfmt#4300]
Hi, rustfmt seems to format in a worse way than written in the book where in the book it specifically says that this is the way it should be formatted. Also this was supposedly fixed in 2017: https://github.com/rust-lang/rustfmt/issues/2112 Am i missing something?

**Input**

```
io::stdin()
    .read_line(&mut guess)
    .expect("Failed to read line");
```

**Output**

```
io::stdin().read_line(&mut guess).expect("Failed to read");
```

**Expected output**

```
io::stdin()
    .read_line(&mut guess)
    .expect("Failed to read line");
```

**Meta**

- rustfmt version: rustfmt 1.4.16-stable (939e164 2020-06-11)
- From where did you install rustfmt?: rustup

**Comment by calebcartwright** [comment]
hi @KarlisZ 

> rustfmt seems to format in a worse way than written in the book where in the book it specifically says that this is the way it should be formatted

Could you please provide a link to that within the book? The definitive, official style guide is defined [here](https://github.com/rust-dev-tools/fmt-rfcs) and supersedes other styling suggestions. 

Your provided snippet is a sequence of method call expressions (a chain) and is accordingly subject to the corresponding formatting requirements for chains.

The specific style information for chains can be found within the style guide here: https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#chains-of-fields-and-method-calls

Particularly note:

> Prefer formatting on one line if possible, and the chain is small.

The emitted formatting you are seeing is the correct and expected default formatting behavior because the chain is small enough to be formatted on one line. As such, I am going to close this issue.

Please do be aware however that in upcoming rustfmt 2.0 release will include a `chain_width` configuration that you will be able to leverage to better control this behavior, including being able to produce your desired formatting.

**Comment by KarlisZ** [comment]
It's here in the book: https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html#handling-potential-failure-with-the-result-type.

Here's the full quote:
```
When you call a method with the .foo() syntax, it’s often wise to introduce a newline and other whitespace to help break up long lines. We could have written this code as:

io::stdin().read_line(&mut guess).expect("Failed to read line");

However, one long line is difficult to read, so it’s best to divide it. Now let’s discuss what this line does.
```

**Comment by Carrybooo** [comment]
I agree with KarlisZ, we should have an option to chose if we want to format method calls on one line or not, as i learned with the official book too, and the book uses a new line for the .expect() at least, and i really find it more readable even if the whole line is _small_.
