### ISSUE TITLE
Multiline comments ending in " lead to creation of line with only spaces

### ISSUE THREAD

**Issue by C4K3** [rust-lang/rustfmt#4312]
**Input**

```rust
fn main() {
    /* " */
    println!("Hello, world!");
}
```

**Output**

```rust
fn main() {
    /* " */
    
    println!("Hello, world!");
}
```
(notice the blank line between the comment and the println, containing 4 spaces.

**Expected output**

Input unchanged.

**Meta**

- rustfmt version: `rustfmt 1.4.16-stable (939e164 2020-06-11)`
- From where did you install rustfmt?: rustup

**Comment by ayazhafiz** [comment]
This seems to happen iff the comment is a `/*` comment with exactly `"` as its comment.

Putting two such comments in sequence leads to another "fun" bug: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=70c8eb3ed7416f5101dd5297cdd8c005 🙂 

This is probably simple to fix since it seems to be such a specific case, but we should check if it's repro on master.

**Comment by C4K3** [comment]
It seems to be when it contains precisely one `"`. `/* abc " */` and `/* " abc */` both reproduce the issue.
