### ISSUE TITLE
Strange formatting with nested macro_rules! and long comment

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rustfmt#4325]
**Input**

```rust
macro_rules! bad {
    () => {
        macro_rules! inner {
            () => {
                // This needs to have a width of over 100 characters to trigger the issue 12345678901
                ("a", "B")
            };
        }
    };
}
```

**Output**

```
macro_rules! bad {
    () => {
        macro_rules! inner {
                    () => {
                        // This needs to have a width of over 100 characters to trigger the issue 12345678901
                        ("a", "B")
                    };
                }
    };
}
```

**Expected output**

```rust
macro_rules! bad {
    () => {
        macro_rules! inner {
            () => {
                // This needs to have a width of over 100 characters to trigger the issue 12345678901
                ("a", "B")
            };
        }
    };
}
```

**Meta**

- rustfmt version: `rustfmt 1.4.16-stable (939e164 2020-06-11)`
- From where did you install rustfmt?: rustup

Modifying the comment to be less than 100 characters causes rustfmt to leave the code unchanged.

**Comment by ayazhafiz** [comment]
The problem is that we bail on trying to format the inner code block if any formatted line comes out to >100 chars:

https://github.com/rust-lang/rustfmt/blob/ff57cc6293ce450380dbb6da6a1a3656dbae538d/src/formatting/util.rs#L101-L106

I'm not convinced this check is needed since we jump out early if retrieving the formatted snippet fails:

https://github.com/rust-lang/rustfmt/blob/ff57cc6293ce450380dbb6da6a1a3656dbae538d/src/formatting/util.rs#L81

And no system/idempotency tests are broken by removing this. In the most conservative case I think it is okay to make an exemption for macros here, since we can't do better anyway.
