### ISSUE TITLE
Extra indentation with comments in match arm.

### ISSUE THREAD

**Issue by prataprc** [rust-lang/rustfmt#4350]
**Describe the bug**
For the following macro:

```rust
macro_rules! mto_text_left {
    ($buf:ident, $n:ident, $pos:ident, $state:ident) => {{
        let cursor = loop {
            state = match iter.next() {
                None if $pos == DP::Start => break last_char_idx($buf),
                None /*some comment */ => break 0,
            };
        };
        Ok(saturate_cursor($buf, cursor))
    }};
}
```

`rustfmt --check` gives the following result:

```diff
Diff in ted/yz.rs at line 2:
     ($buf:ident, $n:ident, $pos:ident, $state:ident) => {{
         let cursor = loop {
             state = match iter.next() {
-                None if $pos == DP::Start => break last_char_idx($buf),
-                None /*some comment */ => break 0,
-            };
+                    None if $pos == DP::Start => break last_char_idx($buf),
+                    None /*some comment */ => break 0,
+                };
         };
         Ok(saturate_cursor($buf, cursor))
     }};
```
If the comment ``/* some comment */`` is removed, indentation works as expected. Also noticed that this happens only within macro-definitions.

**Meta**

- rustfmt version: ``rustfmt 1.4.18-nightly (c1e9b7b8 2020-06-13)``
- From where did you install rustfmt?:  ``rustup``
- How do you run rustfmt:  ``rustfmt --check``

**Comment by ayazhafiz** [comment]
The root cause of this is the same as in #3987. Briefly, the problem is that rustfmt drops the comments present in the macro when formatting it, so it falls back on the original parsed content.

The problem with this is that the parsed macro body string looks like

```
state = match iter.next() {
        None if $pos == DP::Start => break last_char_idx($buf),
        None /*some comment */ => break 0,
    };
```

which makes sense, because that's where the body starts/ends. But when rustfmt adds this text to the formatted result, it indents the body in a way it thinks is appropriate, which is to indent all lines so that the first line is also indented. This causes the extra lines to be indented more than they appear they should be.

Two options of solving this are

- fix passes where comments are dropped
- de-indent parsed macro bodies
