### ISSUE TITLE
rustfmt silently removes invalid syntax in attribute

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/rustfmt#4413]
**Describe the bug**

When given this code with invalid syntax:

```rust
#[derive(Debug, (PartialEq, Eq, Clone)]
pub struct Foo {
    bar: u32,
}
```

rustfmt silently converts it to 

```rust
#[derive()]
pub struct Foo {
    bar: u32,
}
```

**Expected behavior**

I think in this case rustfmr should give an error, or leave the invalid syntax as-is, instead of silently discarding it, potentially changing the meaning of your code without you noticing.

**Meta**

- rustfmt version: rustfmt 1.4.20-nightly (48f6c32 2020-08-09)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: via vscode rust-analyzer format-on-save, but also happens on the rust playground etc

**Comment by calebcartwright** [comment]
Thank you for reaching out @Dirbaio. Though rustfmt 1.4.20 does have this bug, the syntax error is indeed reported when running rustfmt (or cargo fmt) directly. We don't have any control over that output not being displayed in the editor on-save or on the playground. 

Additionally, this has already been fixed in the rustfmt source, with the original invalid syntax being left as-is, but it has not yet been released. I don't think we'll be able to sneak this into the 1.4.21 release, but will try to get it into the next one. 

Going to go ahead and close this as a fixed duplicate
