### ISSUE TITLE
Formatting doesn't work partially with significant nesting and long text line

### ISSUE THREAD

**Issue by nazar-pc** [rust-lang/rustfmt#4415]
**Describe the bug**

Formatting doesn't work around `match` in provided reduced example. Formatting for some other parts of the code around method definition works though. Removing at least one character from text string fixes something and formatting starts working again.

**To Reproduce**

```rust
impl Foo {
    pub fn new() -> Self {
        {
            foo.bar({
                {
                    match 1 { _
                        => {
                            if true
                            {
                                foo!("if you remove one character from this line formatting works   ");
                            }
                        }
                    }
                }
            })
        }
    }
}
```

**Expected behavior**

Formatting works on such file.

**Meta**

- rustfmt version: rustfmt 1.4.18-stable (8157a3f 2020-07-15), rustfmt 1.4.20-nightly (48f6c32 2020-08-09)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `rustfmt`, `cargo fmt`, via IDE

**Comment by calebcartwright** [comment]
Thank you for reaching out @nazar-pc. This is a duplicate (#3863) of a known/existing issues with formatting chains when one or more of the chain elements would exceed `max_width` when formatted. In these cases, rustfmt leaves the original formatting in place and defers to the developer to properly format, because any formatting rustfmt would apply would violate a rule (max width in this case)

Your snippet above contains a chain due to the `foo.bar(...` on line 4, and the string arg for `foo!` exceeds the max_width value of 100. When you remove a char from the string the length drops below the limit and so rustfmt can format.

If you are using rustfmt on nightly, then you can try enabling `format_strings = true` in your rustfmt config which will allow rustfmt to split the string to stay within the max_width limit. Otherwise you can try splitting the string yourself:

```rust
...
                                foo!(
                                    "if you remove one character from this line \
                                     formatting works  ",
                                );
```

I'm going to go ahead and close this, feel free to track #3863
