### ISSUE TITLE
failed to parse Real("...")

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#4418]
**Describe the bug**

This message sometimes (but not always) appears at the bottom of output after a parse error. It seems unintentional and maybe like some accidental debug logging.

```console
$  target/release/rustfmt src/openbrace.rs 
error: this file contains an unclosed delimiter
 --> /git/rustfmt/src/openbrace.rs:1:3
  |
1 | {
  | - ^
  | |
  | unclosed delimiter

error: expected item, found `{`
 --> /git/rustfmt/src/openbrace.rs:1:1
  |
1 | {
  | ^ expected item

failed to parse Real("/git/rustfmt/src/openbrace.rs")

$  target/release/rustfmt src/closebrace.rs 
error: unexpected closing delimiter: `}`
 --> /git/rustfmt/src/closebrace.rs:1:1
  |
1 | }
  | ^ unexpected closing delimiter

$  ▎
```

**To Reproduce**

Build rustfmt from master branch (currently 6646248ffce9741a748bc8f5aa25dec0d85ccb17). Write `{` to openbrace.rs and `}` to closebrace.rs. Run rustfmt on each as shown above. `failed to parse Real("...")` appears for openbrace.rs, though not for closebrace.rs. It should be for neither.

**Expected behavior**

Just the compiler-style diagnostics would be sufficient. `failed to parse Real("...")` should not appear also at the end.

**Comment by calebcartwright** [comment]
Thanks for the report! There were indeed two bugs here:

1. A typo/issue in how we we were using thiserror on the parsing error variant which was causing the spurious `failed to parse Real("...")` instead of the expected `failed to parse /home/caleb/dev/rustfmt-sandbox/....`
2. An unhandled rustc parser panic that was only hit with certain types of input in the entry point file (`closedbrace.rs` in your example)

> Just the compiler-style diagnostics would be sufficient. failed to parse Real("...") should not appear also at the end.

We actually do want to surface up the rustfmt operation error, including the parsing variants (just without the formatting bug). It's important because users can actually instruct rustfmt to disable the compiler diagnostics via certain config options, like [hide_parser_errors](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#hide_parse_errors), and we don't want to fail completely silently, and it's also useful for us in bug reports since there's a few different code branches that can have the compiler-style parser error emissions.
