### ISSUE TITLE
Error retrieving configuration options for older versions on Config site

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#4429]
To reproduce, go to the rustfmt configuration documentation site (https://rust-lang.github.io/rustfmt/) and change the version to v0.8.1 or v0.7, and observe the `Failed to get configuration options for this version, please select the version from the dropdown above.` message and empty option list.

![image](https://user-images.githubusercontent.com/13042488/93717131-5ec68e80-fb39-11ea-8e98-84deb397b077.png)

An ideal fix to this would identify and resolve the root cause of whatever is going on with this issue, although given how ancient the versions in question are (pre 1.0 release), it may be sufficient to just filter these out of the available version list. 

Also worth noting (and bonus points for fixing :smile:) the ``Failed to get configuration options....` error message remains on the page even after changing to a different version and the configuration options being successfully loaded

**Comment by meemaker** [comment]
😥😥

**Comment by gorogoroumaru** [comment]
The rustfmt configuration documentation site tries to fetch configuration options from "https://raw.githubusercontent.com/rust-lang/rustfmt/${this.version}/Configurations.md".
In v0.8.1 and v0.7, this page doesn't exist and fetching fails.

**Comment by jdollar** [comment]
Tossed up a push request to attempt a solution at this. Updated to pull the "Configuring Rustfmt" section of the README in the case of the older versions. 

Looks a little something like this:
![image](https://user-images.githubusercontent.com/5238576/94979830-37859f00-04f3-11eb-9bab-86ff1c65f5be.png)

So it includes some information on styling since it seems like all that was under the same section. I can look into removing that as well and just trimming it down to the items specific to configuring rustfmt there OR I would totally be fine just scrapping this and removing those two versions if the result is too underwhelming to everyone.

Hopefully that helps!

**Comment by calebcartwright** [comment]
Resolved via #4451
