### ISSUE TITLE
Feature request: use rustfmt as a library in build.rs

### ISSUE THREAD

**Issue by jsoo1** [rust-lang/rustfmt#4443]
Rustfmt cannot be used as a library in build.rs when the project is using the stable toolchain. 

It would be nice to be able to use rustfmt on generated code. My use case is files generated by the graphql_client crate but I am certain there are other cases.

**Comment by calebcartwright** [comment]
> It would be nice to be able to use rustfmt on generated code.

I'd actually discourage this. Most other generators will insert a `#![rustfmt::skip]` to the top of generated files so that consumers which also leverage rustfmt won't experience any formatting issues, and I'd strongly advise doing the same.

They actually did what you're describing in the winrt-rs project (albeit by running the rustfmt bin), and it's already been a source of confusion for those users. Worth noting that not everyone uses rustfmt, and some users won't even have it on their system. rustfmt can and will fail in other scenarios not strictly related to the formatting of your generated code, for example a user having an invalid rustfmt config file in their repo, and it's a subpar experience to have build failures in these cases due to the attempted formatting of generated code.

 Making a successful rustfmt run a compilation dependency is just not a good idea IMO

> Rustfmt cannot be used as a library in build.rs when the project is using the stable toolchain.

It's not possible to compile rustfmt on stable, as rustfmt has to use the internal rustc mods which themselves can only build on nightly. This is not going to change any time soon, and perhaps not ever. 

There's also ongoing discussions about changing rustfmt from a submod to a subtree due to the deep coupling on the compiler internals, and one impact of making such a change is that rustfmt would no longer be available to consume as a lib from crates.io anyway.

**Comment by calebcartwright** [comment]
Closing as building rustfmt on stable is not possible, and additional guidance as been provided above.
