### ISSUE TITLE
Cfg block containing only a comment duplicates the previous lines.

### ISSUE THREAD

**Issue by ExPixel** [rust-lang/rustfmt#4467]
**Describe the bug**

Formatting an empty `cfg` block with a comment causes `rustfmt` to duplicate the `cfg` line.

```rust
pub fn main() {
    #[cfg(feature = "std")]
    {
        // Comment
    }
}
```

gets formatted into

```rust
pub fn main() {
    #[cfg(feature = "std")]
    {
        [cfg(feature = "std")]
    { // Comment
    }
}
```

Everything works as expected if there is actual code in the block or if the block is empty so the issue isn't too bad. Just thought it was worth mentioning.

**To Reproduce**
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=161085030374989f3243ad8eeb0328f5

Running `rustfmt` on the playground should display the weird behavior.

**Expected behavior**
I expect the output to just be
```
pub fn main() {
    #[cfg(feature = "std")]
    {
        // Comment
    }
}
```

**Meta**

- rustfmt version: rustfmt 1.4.20-stable (48f6c32 2020-08-09)
- From where did you install rustfmt?: rustup
- How do you run rustfmt: `rustfmt` in `vim`

**Comment by calebcartwright** [comment]
Thanks for the report @ExPixel 

This is due to an upstream rustc bug that's subsequently been resolved, previously reported and discussed on the thread linked below. Closing as a duplicate, will go away after our next update.
https://github.com/rust-lang/rustfmt/issues/4452#issuecomment-705886282
https://github.com/rust-lang/rustfmt/issues/4452#issuecomment-706641620
