### ISSUE TITLE
Different formatting for Arithmetic and Logical Operators

### ISSUE THREAD

**Issue by davidBar-On** [rust-lang/rustfmt#4500]
In [tests/target/issue-831.rs](https://github.com/rust-lang/rustfmt/blob/2d6a968d52b13b75fc3799f50020a34efd480a28/tests/target/issue-831.rs#L1) a Logical operation in multiline expression is formatted as:
```rust
fn main() {
    let y = a.iter().any(|x| {
        println!("a");
    }) || b.iter().any(|x| {
        println!("b");
    }) || c.iter().any(|x| {
        println!("c");
    });
}
```

while formatting of a similar expression with Arithmetic operation in [tests/target/expr.rs ](https://github.com/rust-lang/rustfmt/blob/2d6a968d52b13b75fc3799f50020a34efd480a28/tests/target/expr.rs#L528) is formatted as:
```rust
fn issue_2802() {
    function_to_fill_this_line(some_arg, some_arg, some_arg)
        * a_very_specific_length(specific_length_arg)
        * very_specific_length(Foo {
            a: some_much_much_longer_value,
        })
        * some_value
}
```

**Why is the `||` operation added to the  `})` line, while the `*` is added in a new line?**  If this is in purpose, what is the logic behind the different formatting approaches?

**Comment by calebcartwright** [comment]
This formatting is correct. Yes, both snippets have binary expressions, but note that the first example has closures which have [their own formatting rules](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#closures).

Particularly of note for closures is the required indentation for closing braces to adhere to block formatting rules, while the rules for binary expressions require block indentations for the operators and sub exprs on a new line.

We couldn't indent the closing closure brace from your first snippet like below as that would violate closure formatting:

```rust
fn main() {
    let y = a.iter().any(|x| {
            println!("a");
        }) || b.iter().any(|x| {
       .......
```

and we couldn't put the binary operator and next subexpr on the next line without indentation like this (would break binop rules):
```rust
fn main() {
    let y = a.iter().any(|x| {
        println!("a");
    })
    || b.iter().any(|x| {
        println!("b");
    })
    || c.iter().any(|x| {
        println!("c");
    });
}
```

and if you tried to still put the op and subexpr chains on their own line with a block indentation you'd end up with something wild like this, which would in turn break other indentation rules
```rust
fn main() {
    let y = a.iter().any(|x| {
        println!("a");
    })
        || b.iter().any(|x| {
            println!("b");
        })
            || c.iter().any(|x| {
                println!("c");
            });
}
```

Remember that even though two top level expressions may be the same, the entire AST subtree impacts their respective formatting due to the respective rules which is why there's formatting differences when those top level expressions contain different elements.

**Comment by davidBar-On** [comment]
Thanks for the detailed repose.
