### ISSUE TITLE
Rustfmt deletes polarity of negative impl

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rustfmt#4566]
As of current master branch (fd9e7d3e932986a49254de3a7da857a29978d3cc):

<pre>
$ echo <b>'impl!Trait{}'</b> | CFG_RELEASE_CHANNEL=dev CFG_RELEASE=1.48.0 cargo +nightly run --bin rustfmt --features rustfmt
</pre>

Expected:

```console
impl !Trait {}
```

Actual:

```console
impl Trait {}
```

This syntax is accepted syntactically by rustc since 1.25.0. Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a0af137c2df7c45fe1571573ec6a8ad3

**Comment by calebcartwright** [comment]
That's an odd miss considering rustfmt wasn't "officially" released til 1.31.0 :thinking: 

I'm a bit behind on rustfmt PRs and issues but will try to take a look at this after work today

**Comment by calebcartwright** [comment]
Ah I see, this only occurs in the absence of a trait_ref (compare with `impl ! Trait for Foo{}`) as rustfmt has an internal assumption that there wouldn't be a negative polarity if there wasn't a trait_ref present.

While I'm not sure what the use case is for a negative impl without a `for type` (in fairness I'm very unfamiliar with negative impls), it's nevertheless valid syntax and there's no reason rustfmt should drop a negative polarity on an impl item.

Going to mark this as a good-first-issue in case others want to work on it, but please let me know if this is a blocker/higher urgency for you and I'll go ahead and resolve myself.

For anyone interested in working on this, you'll want to take a look at the `format_impl_ref_and_type` function in items.rs (src/formatting/items.rs).

Things are already taken care of when there is a trait ref:
https://github.com/rust-lang/rustfmt/blob/fd9e7d3e932986a49254de3a7da857a29978d3cc/src/formatting/items.rs#L967-L976

But in cases where there isn't then rustfmt is silently tossing the polarity string. In order to resolve this, we should probably incorporate a new check that looks for the combination of a negative polarity and the absence of a trait ref, and if true then ensure the polarity string (`!`) is included immediately preceding the type string.

Be sure to include the extra character in the budget computations to prevent any off-by-one issues with edgier cases that run up around the max_width limit, and then incorporate the check both for the case where the type string can fit on one line:
https://github.com/rust-lang/rustfmt/blob/fd9e7d3e932986a49254de3a7da857a29978d3cc/src/formatting/items.rs#L991-L1004

and the case where it has to be multilined
https://github.com/rust-lang/rustfmt/blob/fd9e7d3e932986a49254de3a7da857a29978d3cc/src/formatting/items.rs#L1006-L1019
