### ISSUE TITLE
Not formatting when it should

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rustfmt#4589]
**Describe the bug**

In https://github.com/rust-lang/rust/pull/79553#discussion_r541538233 something roughly equivalent to the following was not formatted to how to should:

```rust
enum Foo {
    Bar {
        foo_bar: bool,
        baz: u8 },
}
```

The `},` should be on a new line.

**To Reproduce**

Run `./x.py fmt` on the rust repo as of https://github.com/rust-lang/rust/commit/5bd9b60333b3dc0a51e7a5607cd1e0d537a9f718. The offending line is line 60 of compiler/rustc_mir_build/src/build/expr/as_place.rs.

**Expected behavior**

See "Describe the bug"

**Meta**

- rustfmt version: `rustfmt 1.4.27-nightly (580d826 2020-11-16)`
- From where did you install rustfmt?: The rust build system
- How do you run rustfmt: `./x.py fmt`

**Comment by calebcartwright** [comment]
Left a comment on the linked PR, but closing this as it seems the referenced nonformatting is due to the ignore configuration within the r-l/rust repo. 

If you run rustfmt directly, using stable, nightly, and/or rustfmt from source, you'll see it formatted fine both with the snippet in this issue description and the referenced snipped in the linked PR, demonstrable at the Playground link below.

Closing accordingly, but can certainly reopen if there turns out to be anything with rustfmt itself

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ce4aab0185308555b2e4eca4507c5114
