### ISSUE TITLE
Newlines added to macro_rules body since 1.4.28

### ISSUE THREAD

**Issue by betamos** [rust-lang/rustfmt#4595]
Formatting of this macro body has changed between 1.4.27 and 1.4.28, with default options:

**Previous**
```
#[macro_export]
macro_rules! Foo {
    () => { _ };
}
```

**Current**
```
#[macro_export]
macro_rules! Foo {
    () => {
        _
    };
}
```

I suppose this is covered by the stability guarantees of rustfmt with default options.

Unfortunately, I couldn't run a bisect further since I couldn't find a nightly toolchain that worked across the full range.

**Meta**

- rustfmt version: 1.4.28+
- From where did you install rustfmt?: rustup (1.4.27) and cargo make build-bin (1.4.28)
- How do you run rustfmt: rustfmt --check ./file.rs

**Comment by calebcartwright** [comment]
rustfmt was unable to format this entirely prior to 1.4.28 and up, take a look at this highly exaggerated version of your snippet for reference:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b91b965d68aefe2b4f61ff33d065b672

> I suppose this is covered by the stability guarantees of rustfmt with default options.

The stability guarantee doesn't preclude us from being able to fix bugs, nor upstream rustc changes making it possible for formatting rules to be applied for the first time. There's cases like this, particularly with macro defs of late (presumably due to the upstream tokenstream changes), where folks incorrectly think rustfmt is formatting some portion of their code because it looks right to them, only to discover later on that rustfmt is actually just now starting to format those portions of code.

Going to go ahead and close but let me know if you have any follow up questions

**Comment by betamos** [comment]
Awesome, thanks for the swift resolution.

> nor upstream rustc changes making it possible for formatting rules to be applied for the first time

Ah, this makes sense. Is creating an "exaggerated version" the best way to tell whether or not the formatter was used at all?

**Comment by calebcartwright** [comment]
> Ah, this makes sense. Is creating an "exaggerated version" the best way to tell whether or not the formatter was used at all?

With macros I find that tends to be the case, at least for a quick and easy test.

There's also the `error_on_unformatted` config option that can be turned on but it's unstable and doesn't flag every case where rustfmt fails to format and emits the original snippet associated with the corresponding span
