### ISSUE TITLE
Option to suppress all newline changes.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rustfmt#4686]
**Request:** An option to suppress all changes of newlines when formatting.

If this option is enabled then rustfmt will not add or remove newlines anywhere when formatting. All other formatting rules (indentation, spacing, etc) can be applied normally as long as they don't add or remove newlines to the file.

possible option name `prevent_newline_changes` (bikeshed).

**Comment by calebcartwright** [comment]
Could you elaborate on what specifically you mean by new lines? Are you scoping it to just the insertion/removal of blank lines, or broader expansion of formatting from single-line to multi-line and vice versa?

If the former, could you identify how it differs/where you see gaps with the existing [`blank_lines_lower_bound`](https://rust-lang.github.io/rustfmt/?version=v1.4.35&search=#blank_lines_lower_bound) and [`blank_lines_upper_bound`](https://rust-lang.github.io/rustfmt/?version=v1.4.35&search=#blank_lines_upper_bound) options?

**Comment by Lokathor** [comment]
I mean the broader version. No changes from single-line to multi-line or vice versa.

Put another way: `document_str.lines().count()` should be the same value before and after formatting.

**Comment by calebcartwright** [comment]
Sorry, but that runs counter to the objective of rustfmt to reformat everything in accordance with the Style Guide and would essentially require an entirely separate formatter.

Understand that some folks have a preference for the other style of code formatting which maintains/formats based on the existing hand-crafted coding style, but that's very much a non-goal for rustfmt

**Comment by calebcartwright** [comment]
Should also add that there have been some discussions about potentially extending rustfmt one day to optionally support formatting with an entirely different strategy. However, that's an extremely low priority, and it would have to be surfaced in a way that's completely different (potentially a separate binary, or a subcommand on `rustfmt`); it couldn't just be a simple config option added to the current ecosystem which is why I've closed this.
