### ISSUE TITLE
std use below mod+use not moved to std group

### ISSUE THREAD

**Issue by JakeWharton** [rust-lang/rustfmt#4767]
This may very well be me misunderstanding the semantics of these declarations again, but...

**Input**

```rust
use std::fs::File;
use std::io::stdin;

mod output;
use output::Config as OutputConfig;
use output::Output;
use std::error::Error;
```

**Output**

```rust
use std::fs::File;
use std::io::stdin;

mod output;
use std::error::Error;

use output::Config as OutputConfig;
use output::Output;
```

**Expected output**

```rust
use std::error::Error;
use std::fs::File;
use std::io::stdin;

mod output;
use output::Config as OutputConfig;
use output::Output;
```

**Meta**

- rustfmt version: 1.4.36-nightly (7de6968e 2021-02-07)
- From where did you install rustfmt?: cargo nightly

`.rustfmt.toml`:
```toml
imports_granularity = "Item"
group_imports = "StdExternalCrate"
```

**Comment by tommilligan** [comment]
I think this is displaying expected behaviour. The relevant implementation states (emphasis mine):

- If the next item is a `use` [...] extract it and any subsequent items **that have the same item kind** to be reordered [...]

So in other words, it'll apply the `StdExternalCrate` formatting, but only to `use` statements that are consecutive. Your example shows this nicely: in your original example, `mod output;` acts as a delimiter. Considering the two sets of `use` statements separately, both are regrouped to `StdExternalCrate` layout as expected.

However, I agree this is ambiguous from reading the option documentation, so I'll see if I can clarify that with a PR and a test case.

https://github.com/rust-lang/rustfmt/blob/272fb42f06479afb62a9503f181540101f67982a/src/reorder.rs#L314-L316
