### ISSUE TITLE
"Permission denied (os error 13)" on `cargo fmt`

### ISSUE THREAD

**Issue by micouy** [rust-lang/rustfmt#4777]
`cargo fmt` returns *Permission denied (os error 13)* since last `rustup update`. It happens with `rustfmt` on both `nightly` and `stable` (`cargo +stable fmt`, `cargo +nightly fmt`). `rustfmt <file>` works.

rustfmt version: `rustfmt 1.4.36-stable (7de6968e 2021-02-07)` / `rustfmt 1.4.36-nightly (7de6968e 2021-02-07)`

**Comment by calebcartwright** [comment]
Hi thanks for reaching out, but I feel like this almost certainly has to be an issue specific to your local system. 1.4.36 is the latest release which has been out for quite a while, so if there was a bug in rustfmt or in rustup it would've had widespread impact and been reported long ago.

Can you check to see which binaries are actually getting invoked on your system, and whether your user id has executable permissions to those?

**Comment by micouy** [comment]
```
$ cargo fmt --verbose

[bin (2018)] "<project location>/src/main.rs"
rustfmt --edition 2018 <project location>/src/main.rs
```

```
$ which rustfmt

<my user>/.cargo/bin//rustfmt
```

```
$ exa -l (which rustfmt)

.rwxr-xr-x <my user>/.cargo/bin/rustfmt
```

Is there something else I should check? Invoking `rustfmt` by itself works, maybe there is some issue with `cargo fmt` command?

**Comment by calebcartwright** [comment]
Can you also check the `cargo-fmt` executable?

**Comment by micouy** [comment]
```
$ which cargo-fmt
<my user>/.cargo/bin//cargo-fmt

$ exa -l (which cargo-fmt)
.rwxr-xr-x <my user>/.cargo/bin/cargo-fmt
```

`<my user>/.cargo/bin` is a link.

```
$ exa -l (<my user>/.cargo/)
drwxr-xr-x bin
```

**Comment by calebcartwright** [comment]
Thanks, but going to go ahead and close the issue.

Looks like the binary permissions are fine, so odds are that you've somehow ended up in a scenario where rustfmt is unable to read from and/or write back to the .rs or .toml files on your filesystem due to your permissions. One way to test the read vs write would be to change the emit mode (e.g. `cargo fmt -- --emit stdout`) 

Suppose it's also worth checking if you have the `RUSTFMT` environment variable set, as in the presence of that var `cargo fmt` will invoke the rustfmt bin specified there as well
