### ISSUE TITLE
Rustfmt removes line breaks in a macro rules 

### ISSUE THREAD

**Issue by fxdave** [rust-lang/rustfmt#4814]
**Input**

```rust
#[macro_export]
macro_rules! render_el_variants {
($render_output_builder:ident, { el $element:expr, $attrs:tt, $children:tt $(;)? }) => {{
        $crate::render_el!($render_output_builder, $element, $attrs, $children)
}};
}
```

**Output**

```rust
#[macro_export]
macro_rules! render_el_variants {
($render_output_builder:ident, { el $element:expr, $attrs:tt, $children:tt $(;)? }) => {{ $crate::render_el!($render_output_builder, $element, $attrs, $children) }};
}
```

**Expected output**

```rust
#[macro_export]
macro_rules! render_el_variants {
($render_output_builder:ident, { el $element:expr, $attrs:tt, $children:tt $(;)? }) => {{
        $crate::render_el!($render_output_builder, $element, $attrs, $children)
}};
}
```

**Meta**

- rustfmt version: rustfmt 2.0.0-rc.2-nightly
- From where did you install rustfmt?: rustup

**Comment by fxdave** [comment]
No, I don't have any rustfmt configurations.
I'm on the nightly toolchain. 
```rust
> rustup component add rustfmt
info: downloading component 'rustfmt'
info: installing component 'rustfmt'
info: using up to 500.0 MiB of RAM to unpack components
> cargo fmt --version
rustfmt 2.0.0-rc.2-nightly (8829e455 2021-03-27)
````

**Comment by calebcartwright** [comment]
Thanks that clarifies the version, but please note that's not coming from rustup. You must have installed rustfmt from source a while back using cargo which will be used over any rustup managed component.

I asked because I can't reproduce the issue you've reported with the released versions of rustup (which are all v1.x), though haven't tested on the unreleased 2.0 branch, nor the specific commit you built from back in March.

If your 2.0 install wasn't intentional you could always consider uninstalling it (`cargo uninstall rustfmt-nightly`) and just use the shipped/release versions. If your issue turns out to be reproducible on the _latest_ version of the unreleased 2.0 branch then we'll try to get it fixed, but may be a little while.

**Comment by fxdave** [comment]
It is 1.4.37-nightly now.
And it works well.
Thanks
