### ISSUE TITLE
cargo fmt gives gobbledegook errors about 'nightly' that cannot be fixed

### ISSUE THREAD

**Issue by martinellison** [rust-lang/rustfmt#4826]
If I try using some `cargo fmt` options such as `wrap_comments` or `format_code_in_doc_comments` it just gives me errors that do not mean anything, and which cannot be fixed.

Typical messages are "unstable features are only available in nightly channel" and "the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the 'nightly-x86_64-unknown-linux-gnu' toolchain" and "the 'rustfmt' binary, normally provided by the 'rustfmt' component, is not applicable to the 'nightly-x86_64-unknown-linux-gnu' toolchain".

Please fix this.

**Comment by calebcartwright** [comment]
Sounds like you're frustrated, sorry to hear that!

> it just gives me errors that do not mean anything, and which cannot be fixed.

I'm not entirely sure what you mean by this.

It's common within the Rust ecosystem for certain features to only be available on a nightly toolchain, and this is also true for some rustfmt configuration options (see https://github.com/rust-lang/rustfmt#configuring-rustfmt and/or https://rust-lang.github.io/rustfmt/ for more details).

If you try to use unstable options on stable then you'll get an error message from rustfmt to that effect. You must use a nightly toolchain to use unstable features, including unstable rustfmt configuration options.

> "the 'cargo' binary, normally provided by the 'cargo' component, is not applicable to the 'nightly-x86_64-unknown-linux-gnu' toolchain" and "the 'rustfmt' binary, normally provided by the 'rustfmt' component, is not applicable to the 'nightly-x86_64-unknown-linux-gnu' toolchain"

These are not errors coming from rustfmt, but likely from rustup due to issues with your install.

I'd advise ensuring that you have a recent nightly toolchain installed (e.g. `rustup install nightly`) and then be sure to use rustup to grab the rustfmt component (see https://github.com/rust-lang/rustfmt#on-the-nightly-toolchain and/or https://rust-lang.github.io/rustup/concepts/components.html#components). You can also use the `--allow-downgrade` flag with rustup to install the latest nightly toolchain where your desired set of components are all available, as sometimes on bleeding edge nightlies certain tools/components may be unavailable (e.g. `rustup toolchain install nightly --component rustfmt --allow-downgrade`)

If you're still seeing issues after going through the above steps I'd recommend reaching out the rustup team either via an issue in https://github.com/rust-lang/rustup or their channel on the Rust Discord Server.

I'm going to go ahead and close this but please let me know if you have any follow up questions!

**Comment by martinellison** [comment]
Thanks for writing all that.

I *was* very frustrated as the error messages and the documentation did not give me any way to fix the problem. I would think that other users would got the same issue in the same situation. I think that the best would be to add a sentence or so to the documentation to explain the situation.

As it was, given your explanation, I uninstalled nightly and then reinstalled it, and then `cargo +nightly fmt` ran without issue.
