### ISSUE TITLE
ClosingBraceStyle option needed 

### ISSUE THREAD

**Issue by gdennie** [rust-lang/rustfmt#4828]
Currently the closing brace occurs in the same column as the out block. While this seems symmetric and popular with other curly brace languages, it is leading to unnecessary visual clutter. An additional formatting option that would indent closing braces with their contained block wouldbe helpful. One benefit of such a formatting besides looking elegant and clearer is that code associated with the opening brace becomes visually a sub-heading for the entire block, as one expects.

For example:

```
fn mnz<X:Copy>(x: X) -> i32 {
    ....
    }

fn main() {
    if true {
        ....
        } 
    else {
        ....
        }

    while x {
        ....
        }
    ....
    }

fn mnz<A,B,C>(
    a: A,
    b: B,
    c: C,
    ) 
    -> Result<Option<i32>, String>
    where
        A: Copy,
        B: Display,
        C: Clone,
    {
    ....
    }

mod xyz {
    fn abc<T: Copy>(x: T) -> i32 {
        ....
        }
    ....
    }
```

**Comment by calebcartwright** [comment]
Thanks for reaching out with your request!

As you may already be aware, rustfmt's main job is to reformat input code according to the style codified in the [Style Guide](https://github.com/rust-dev-tools/fmt-rfcs), and that's why the closing braces are formatted they way they are.

rustfmt is still configurable nevertheless, largely to support some of the formatting decisions that cover the style topics large portions of the developer community find contentious (spaces vs. tabs, etc.). Generally speaking we're open to the inclusion of new configuration options, provided the default value still aligns with the Style Guide, but we do also have to consider whether the impact on the codebase and associated maintenance, bug surface, etc. is tolerable in the context of option and style it produces. For a wildly hyperbolic example, we wouldn't accept a new option that doubled the size and complexity of the codebase for a bespoke style that'd only be used by one or two developers because such a change would be far too much of a burden on rustfmt's main job.

I confess I'm not personally sold on the proposed style and associated benefits, and I think it would start to snowball in complexity with "downhill" formatting impacts pretty quickly, particularly in cases with chains and width limits/wrapping. As such this isn't something the rustfmt team will work on. However, if you or anyone else feels strongly enough to submit a PR with an implementation then we'll certainly review and take it under consideration (though whether or not it would be merged would be highly dependent on said implementation)

**Comment by gdennie** [comment]
Thank you for a thoughtful response.

I am still a newbie but `rustfmt` may be one of the way I will eventually contribute.
