### ISSUE TITLE
Unable to keep if-else in the same line in some cases?

### ISSUE THREAD

**Issue by MashPlant** [rust-lang/rustfmt#4846]
Before:

```rust
fn foo(b: bool) -> i32 {
    if b { 0 } else { 1 }
}

fn bar(b: bool) -> i32 {
    let ret = if b { 0 } else { 1 };
    ret
}
```

Formatted with the default configuration:

```rust
fn foo(b: bool) -> i32 {
    if b {
        0
    } else {
        1
    }
}

fn bar(b: bool) -> i32 {
    let ret = if b { 0 } else { 1 };
    ret
}
```

And I seems not able to keep the if-else in `foo` in the same line using any configuration keys.

My cargo and rustc version is `1.54.0-nightly`, and I am using the latest nightly rustfmt.

**Comment by calebcartwright** [comment]
Thanks for reaching out but going to close as there's no action to be taken on our end. If you'd like to keep that statement in `foo` then you'll either need to set `Version` to `Two` in your config file/cli config override, or utilize the skip attribute `#[rustfmt::skip]`.

This has been covered in a few previous issues, but to resummarize, the single-line support for expression statements in the last position of a block wasn't added until after the rustfmt 1.0 release. However, due to rustfmt's stability guarantee and inability to make breaking formatting changes, this isn't the default behavior, which is why you have to opt-in to it by changing `Version` to `Two`.
