### ISSUE TITLE
Could There Be Rustfmt Plugins for Allowing For Custom Macros to be Formatted?

### ISSUE THREAD

**Issue by zicklag** [rust-lang/rustfmt#4849]
Rust's `macro_rules!` macros are awesome for creating custom syntaxes in Rust, but one of the biggest disadvantages to a custom syntax is the lack of support ( totally understandably ) for formatting custom syntaxes. I was considering the use-case of creating a custom syntax similar to Vue.js single-file components, including an HTML-like syntax, but if there was no option for formatting such a syntax that would be a big disadvantage compared to the tooling provided by solutions like Vue and their editor plugins.

Would it be possible to create Rustfmt plugins, possibly using WASM, that would allow adding formatters for custom macro syntaxes? It seems like the API could be very simple:

- A plugin registers the macros that it knows how to format
- Rustfmt will feed the code for those macros to the formatter plugin
- The formatter plugin returns the formatted version of those macros

I might mess around with this in my freetime if there was some buy-in that this is something that could be accepted. Any ideas for better ways to solve this problem?

---

An alternative I considered was using IDE plugins to stack on top of rustfmt, but that would be sub-optimal and would require adding the formatting support to multiple IDE's instead of setting the plugin up with Rustfmt and automatically getting support for all IDEs that support Rustfmt.

---

**Edit:** This would also be useful for function-like proc macros with custom syntaxes, but rustfmt probably wouldn't have any way/reason/need to tell the difference between macro rules macros and proc macros.

**Comment by calebcartwright** [comment]
Thanks for sharing your well thought out suggestion! I'll go ahead with the bad news up front and say that this isn't something I'm willing to consider at this time so I am closing.

I realize that rustfmt's support for macros is quite poor today, and that the suggestion was made to specifically address that gap. However, the core goal of rustfmt is to reformat all code against the standard [Rust Style Guide](https://github.com/rust-dev-tools/fmt-rfcs) with the broader goal of having a consist style for Rust code across the ecosystem. rustfmt is not supposed to be a generalized _formatting platform_ to facilitate the application of other formatting paradigms.

Doing so would be a slippery slope, both because of the impact on the rustfmt maintenance/support, bug surface, etc. as well as for the inevitable subsequent use cases that would want to leverage such a plugin system beyond macros.

> Any ideas for better ways to solve this problem?

rustfmt utilizes the parsed AST provided by rustc for determining the formatted output to emit. This is somewhat oversimplified but in the case of encountering a mac call while traversing the tree, rustfmt will see if the associated tokens can be parsed and formatted as normal rust code; if so then the standard formatting rules for that parsed node are applied, otherwise rustfmt largely ignores and leaves the original in place.

The general consensus for improved macro formatting would be to do more work with the token streams directly as opposed to that current approach. No small task!

<hr />
Thanks again for reaching out!

**Comment by zicklag** [comment]
Thanks for the reply @calebcartwright ! I can see how that could be difficult and how it does sort of open a "philosophical" issue as to what `rustfmt`'s role is in the ecosystem. That makes sense.

That being the case I'll probably look around for tools that are a better match for, as you say, a formatting platform. That could have an integration for Rust and macros somehow. Thanks for a well-explained reply! :slightly_smiling_face:
