### ISSUE TITLE
Appropriate horizontal space 

### ISSUE THREAD

**Issue by burdges** [rust-lang/rustfmt#4859]
As a rule, type setting must tweak horizontal space for readability.  An example of rustfmt mangling horizontal space is reformating 
```
fut.await
.map(|s| JsValue::from_str(&amp;s))
.ok_or_else(|| JsValue::NULL)
```
as
```
fut.await.map(|s| JsValue::from_str(&s)).ok_or_else(|| JsValue::NULL),
```
There is nothing wrong with doing a one-liner here per se, but it requires a little horizontal space in the arguments, like
```
fut.await.map( |s| JsValue::from_str(&s) ).ok_or_else( || JsValue::NULL ),
```
It's unclear to me exactly what the rules for this should be, but it's clear when code is written to be read by the human eye or not.  I think roughly they should gauge the inner expression complexity using metric like adjacent parentheses, split the parse tree depth of the resulting targets, and then add symmetric horizontal space at the half way point.

**Comment by calebcartwright** [comment]
Thanks for sharing your perspective, but going to go ahead and close.

rustfmt's core job is to rewrite the input in order to comply with the standard [Rust Style Guide](https://github.com/rust-dev-tools/fmt-rfcs), with the specific rules for chains being codified [here](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#chains-of-fields-and-method-calls).

As one would expect with something as evocative as code style, there's never unanimous agreement on the "best" style, but that's largely why rustfmt focuses on formatting according to style guidance that went through extensive debate via RFC. It's deterministic and idempotent which is a necessity for the type of formatter rustfmt is; rustfmt cannot deal in ambiguity and "roughly" defined formatting rules.

You can utilize `chain_width` to control the max width a chain can be before it has to be wrapped, and the [`#[rustfmt::skip]`](https://github.com/rust-lang/rustfmt#tips) attribute if you want rustfmt to leave it alone. Your requested style is also not something I'm willing to support with a custom configuration option, both because it results in violating other style guide rules (e.g. calls) and seems far too bespoke to justify the maintenance and bug surface in the chain handling code given the significant complexity of dealing with chains.

**Comment by burdges** [comment]
Meh, `#[rustfmt::skip]` quite verbose since this happens lots.  I just run rustfmt only once or twice ever in a project and manually prune its output.

Can you turn off newline changes within chains all together throughout the project?  In mathematical code, one should break chains at mathematically significant points.  As an example, the line breaks here might represent a multi-scalar multiplication joining elliptic curve points which play different roles 
```
        proofs.iter().map( |proof| proof.Hr.decompress() )
            .chain(ps.iter().map( |p| Some(*p.output.as_point()) ))
```
so placing either `.map` on an equal footing is poor formatting, but human eyes see these breaks correctly.
