### ISSUE TITLE
Extra commas after nested, chained function calls

### ISSUE THREAD

**Issue by xpe** [rust-lang/rustfmt#4883]
With cargo-fmt 1.4.36 on macOS 11.4 using only default options...

Input file (using the clap crate):

```
fn main() {
    let matches = App::new("egg_sample")
        .subcommand(
            SubCommand::with_name("server").arg(
                Arg::with_name("address")
                    .short("a")
                    .long("address")
                    .help("server socket address")
                    .default_value("7890")))
        .get_matches();
}
```

This looks idiomatic to me. It also follows a very similar style as shown in the [clap documentation](https://docs.rs/clap/2.33.3/clap/).

I hoped (expected) that rustfmt would make no changes. However, here is the output:

```
fn main() {
    let matches = App::new("egg_sample")
        .subcommand(
            SubCommand::with_name("server").arg(
                Arg::with_name("address")
                    .short("a")
                    .long("address")
                    .help("server socket address")
                    .default_value("7890"),
            ),
        )
        .get_matches();
}
```

To my eyes (at least), there are two commas added unnecessarily:

1. the comma after `default_value`
2. the comma on the following line, after the `)`

Is rustfmt's change considered to be correct? If so, why?

Also, I read over the rustfmt config options, but I didn't find a good explanation for this behavior.

**Comment by calebcartwright** [comment]
> To my eyes (at least), there are two commas added unnecessarily:
> Is rustfmt's change considered to be correct? If so, why?

Thank you for sharing your perspective, but yes this is correct and as such I am going to close.

rustfmt's default output is entirely dictated by the Rust Style Guide, relevant here is the prescriptions for [function calls that have to be multilined due to width constraints](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#multi-line-calls). rustfmt is unconcerned with the formatting style of clap's documentation, or any other style for that matter; the trailing commas are correct in both places because they are respective trailing args to respective multiline function calls.

You can force rustfmt to remove/elide the commas by setting `trailing_comma=Never` in your config file/cli `--config` override (provided you're able to use nightly), though note that this option is used in other contexts as well.
