### ISSUE TITLE
tuple member access separated from their tuple

### ISSUE THREAD

**Issue by gilescope** [rust-lang/rustfmt#4899]
Given that tuple member accesses are so short (`.0`) does it seem right for them to be newlined in the way that one would do with an .unwrap() ?

```rust
.call::<NeverNativeValue, fn() -> _>(
				ext,
				&runtime_code,
				"BlockBuilder_apply_extrinsic",
				&i.encode(),
				true,
				None,
			)
			.0
			.unwrap();
```
or
```rust
Some(cache_tx) => self
				.cache
				.0
				.write()
				.transaction_with_ops(tx, cache_tx.cache_ops)
				.on_block_insert(
					parent_block,
					block,
					cache_at,
					if finalized { CacheEntryType::Final } else { CacheEntryType::NonFinal },
				)?
				.into_ops(),
```
I'm not entirely sure what good looks like but personally I'd probably have the tuple member access prefer if possible to be stuck to the tuple. Thoughts? If your happy with the above formatting then feel free to close this out.

**Comment by gilescope** [comment]
(btw on the whole rustfmt is doing a truely magnificent effort. It's really shaping up to be a class act.)

**Comment by calebcartwright** [comment]
> Given that tuple member accesses are so short (.0) does it seem right for them to be newlined in the way that one would do with an .unwrap() ?

rustfmt formats code according to the Rust Style Guide and the snippet provided in the description is governed (in part) by the [rules for chains](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#chains-of-fields-and-method-calls).

This is the correct formatting so I'm going to close.

> (btw on the whole rustfmt is doing a truely magnificent effort. It's really shaping up to be a class act.)

:heart: 

> I'm not entirely sure what good looks like but personally I'd probably have the tuple member access prefer if possible to be stuck to the tuple

One of the core objectives is to remove that subjectivity by having a single spec that all code is formatted against.

Chains are one of the most difficult structures to format due to their inherent complexities and commonly deeply nested usage, so many of the formatting rules for chains in that spec were structured in such a way to count for the myriad edge cases to ensure idempotency, predictability, etc.

A side effect of that consistent wrapping/unwrapping rule set is that there's plenty of cases where some folks would prefer to be able to keep certain pairs on the same line (as well as the reverse) in places where rustfmt splits them/puts them on the same line. It's an area we'd like to offer some improved control over, however, it's not an area we can readily cover with configuration options like we do elsewhere because it's such an open ended subjective topic that  can vary wildly even for a given person in a single codebase.

What we want to get to (some day) is a configuration option that folks can opt into where rustfmt will make a best effort to preserve the developers original chain item line associations. However, we just won't be able to support having rustfmt do the forced reformatting against what would quickly become an unbounded set of chain styles.
