### ISSUE TITLE
Add option to format all files

### ISSUE THREAD

**Issue by dylni** [rust-lang/rustfmt#4977]
It would be helpful for rustfmt to have an option to format all `.rs` files in a crate or all files in a directory.

Some issues exist due to rustfmt being unable to know exactly which files are included, due to `#[path]` attributes ([1](https://github.com/rust-lang/rustfmt/issues/4477)) or macros ([1](https://github.com/rust-lang/rustfmt/issues/3253), [2](https://github.com/rust-lang/rustfmt/issues/4034), [3](https://github.com/rust-lang/rustfmt/issues/3619)). However, usually, all that is needed is for every Rust file to be formatted. If rustfmt had an option to format all files, those issues would be avoided.

This could be combined with the [ignore](https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#ignore) option to exclude some files.

**Comment by calebcartwright** [comment]
Thanks for reaching out but going to close as this has been covered in various prior issues and is duplicative of existing behavior.

`cargo fmt` exists to format all the files in a crate in a way that's aware of crucial information, like edition, which impacts parsing. `rustfmt` formats whatever input is provided to it, either specified files or from stdin, and in the case of files the user has the option to also format files imported by inputs, or not.

We're not going to change that. If for some reason folks want/need to run `rustfmt` instead of `cargo fmt` then they'll need to provide the input files to rustfmt, and there's plenty of existing tools and capabilities for discovering files with a certain extension residing in a directory tree, that can then be piped to rustfmt. We're not going to duplicate those capabilities.

**Comment by dylni** [comment]
@calebcartwright Thank you for the information. That is unfortunate, but it makes sense.

Sorry for not finding existing issues about this. They did not show up in a search.

**Comment by calebcartwright** [comment]
No worries, and thanks again for sharing!
