### ISSUE TITLE
formatting removes part of qualified path inside macro

### ISSUE THREAD

**Issue by jsen-** [rust-lang/rustfmt#5005]
Pretty niche use case, but running `rustfmt` makes the code no longer compile.

```rust
#![feature(more_qualified_paths)]
macro_rules! show {
    ($ty:ty, $ex:expr) => {
        match $ex {
            <$ty>::A(_val) => println!("got a"), // formatting removes <$ty>::
            <$ty>::B => println!("got b"),
        }
    };
}

#[derive(Debug)]
pub enum Enum1 {
    A(u8),
    B,
}

fn main() {
    show!(Enum1, Enum1::B);
}
```

```sh
$ rustfmt --version
rustfmt 1.4.37-nightly (addb4da 2021-09-25)
```

**Comment by calebcartwright** [comment]
Thanks for the report!

We actually just recently addressed this for the struct pattern variant, but obviously need to tackle that for the tuple struct variant too. Should be an easy fix for anyone that wants to work on it, and would be great if anyone wants to get a PR in within the next couple days so that I can pull it into the next release.

Fix would be to pull in the qself field, and then update the corresponding call(s) and fn signature(s) accordingly to take that in and include in the emitted formatting:

https://github.com/rust-lang/rustfmt/blob/cb144c35e7d7151bb4b6ccd9b30a4141959166d1/src/patterns.rs#L229-L232

#4964 was the PR that fixed this for the other variant, and should serve as a good reference

**Comment by jsen-** [comment]
you guys rock 🤟
thank you
