### ISSUE TITLE
Poor TAIT formatting with `version = "Two"`: `+` line breaks are not block indented

### ISSUE THREAD

**Issue by chitoyuu** [rust-lang/rustfmt#5027]
Currently on 1.4.37-nightly (dfc5add 2021-10-13), with `version = "Two"` and all other options left at default, this:

```
pub type Iter<'a, D> = impl DoubleEndedIterator<Item = (SomethingSomethingSomethingLongType<D>)> + ExactSizeIterator + 'a;
```

is formatted to:

```rust
pub type Iter<'a, D> = impl DoubleEndedIterator<Item = (SomethingSomethingSomethingLongType<D>)>
+ ExactSizeIterator
+ 'a;
```

...whereas on stable, the same code is formatted to the more familiar and (subjectively) more pleasing:

```rust
pub type Iter<'a, D> = impl DoubleEndedIterator<Item = (SomethingSomethingSomethingLongType<D>)>
    + ExactSizeIterator
    + 'a;
```

...with block indentation for the broken lines.

**Comment by calebcartwright** [comment]
I can't reproduce this with default behavior, and have to change the default value of the `version` config option to `Two` in order to reproduce.

That is of course something we need to fix, but I need to get some clarity on whether this can actually be produced with all defaults. Can you share your rustfmt config file, and/or share output from running rustfmt in verbose mode?

**Comment by chitoyuu** [comment]
> I can't reproduce this with default behavior, and have to change the default value of the `version` config option to `Two` in order to reproduce.

My rustfmt.toml is a single line `version = "Two"`. When I said "by default" I was having "version 2 default" in mind. I have updated the issue to mention this. Sorry I didn't make it clear enough the first time.
