### ISSUE TITLE
Planned removal of `report_fixme`

### ISSUE THREAD

**Issue by calebcartwright** [rust-lang/rustfmt#5102]
The purpose of this issue is to both communicate our intent to drop the unstable option [`report_fixme`](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#report_fixme), as well as provide a forum for questions to be asked and/or concerns to be raised.

We do not yet have an exact deprecation date planned, but it will most likely occur in early 2022.

While we understand the utility this option provides, we've decided that rustfmt simply is not the right place/tool to provide this capability, and it's not an option that makes sense for us to try to stabilize and maintain/support long term.

If anyone is aware of any other community maintained tools/crates for detecting "FIXME" strings in comments please feel free to post here for broader awareness.

**Comment by orenbenkiki** [comment]
I agree that this functionality does not belong in `rustfmt`. I have been using [cargo-todox](https://github.com/orenbenkiki/cargo-todox) instead of `report_fixme`, which might be something of an overkill (I did it as a way to get started with Rust back in the day). Alternatively people could just run `grep FIXME $(git ls-files)` or something along these lines.
