### ISSUE TITLE
Integration tests do not format

### ISSUE THREAD

**Issue by erayerdin** [rust-lang/rustfmt#5105]
Anything under `src` gets the formatting but it does not work for `tests` directory. To give an example, I have a very, *very* long line, which does not format as below:

```rust
    let assertion = binary.args([
        "bot", "send", "poll", "foo", "--receiver", &env::var("TELEGRAM_RECEIVER").expect("TELEGRAM_RECEIVER environment variable could not be found. Please create .env file and define it.")
    ]);
```

...which should format to multiline but it does not.

It does not work in VSCode. I have also tried it as below and it does not still format:

```bash
cargo fmt
cargo fmt -- tests/
cargo fmt -- tests/my_test.rs
```

***

# Environment

 - Ubuntu 21.04
 - Cargo 1.56.0
 - If relevant, VSCode 1.62.3 with [Rust Extension Pack](https://marketplace.visualstudio.com/items?itemName=jrobsonchase.rust-extension-pack) (incl. Rust Analyzer instead of RLS)

**Comment by calebcartwright** [comment]
Thanks for the report. However, the integration tests piece is a red herring because you're running into the same issue as reported in #3863 which will occur regardless of the target type/file directory location.

Standard workaround advice applies around either:

- create a local for the long string lit
- manually break up the long string lit so that it can be fit within the `max_width` limit
- (if you're able to use nightly) enable `format_strings` to give rustfmt permission to try to break up the long string lit on your behalf
