### ISSUE TITLE
Code becomes very unclear on mix of for loop and iterator combinators

### ISSUE THREAD

**Issue by masklinn** [rust-lang/rustfmt#5148]
The code is basically a longer version of Clippy's [manual flatten](https://rust-lang.github.io/rust-clippy/master/#manual_flatten) example, with the iterable inline. If the `for` line is long enough:
```rust
    let an_item = None;
    let an_other_item = None;

    for mut a_nice_declarative_name in [
        Some("a value"),
        an_item,
        Some("an other value"),
        an_other_item,
        Some("more"),
        Some("stuff"),
        Some("again"),
    ].into_iter().flatten() {
        println!("{}", a_nice_declarative_name);
    }
```
gets reformatted to
```rust
    for mut a_nice_declarative_name in [
        Some("a value"),
        an_item,
        Some("an other value"),
        an_other_item,
        Some("more"),
        Some("stuff"),
        Some("again"),
    ]
    .into_iter()
    .flatten()
    {
        println!("{}", a_nice_declarative_name);
    }
```
the lone block brackets, and methods floating in the middle, feel and read very odd. I actually spent a few seconds wondering why I had put the actual code (whose body is quite a bit more complicated) inside its own block after rustfmt ran on it, interpreting it as a sub-scope rather than what it is (a loop body).

**Comment by calebcartwright** [comment]
Thanks for sharing your perspective but I'm going to close because this is correct, expected formatting per the governing [Style Guide](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#multi-line-elements).

You may be interested in reviewing issues like https://github.com/rust-lang/rustfmt/issues/4306#issuecomment-992053253 which outlines some (non-default) options we're exploring that would give you the flexibility to maintain the type of formatting you'd authored
