### ISSUE TITLE
another left behind trailing whitespace error example

### ISSUE THREAD

**Issue by ZuseZ4** [rust-lang/rustfmt#5161]
Nothing serious, but maybe it helps?
```
cargo-fmt --version
rustfmt 1.4.37-stable (f1edd04 2021-11-29)
```

I've been wondering because rustfmt didn't touch the following line:
```
        assert!(info.params.ret_info.is_some(), "Your function {} is returning something, so please don't set the ret_info of your FncInfo to None!", info.primary_name);
```
so I changed it manually into
```
        assert!(info.params.ret_info.is_some(), 
                "Your function {} is returning something, so please don't set the ret_info of your FncInfo to None!", 
                info.primary_name
        );

```
Afterwards, I got the following error from cargo-fmt:
```
error[internal]: left behind trailing whitespace
  --> /home/zusez4/prog/rust-enzyme/oxide-enzyme/src/verify.rs:22:22:48
   |
22 |         assert!(info.params.ret_info.is_some(), 
   |                                                ^
   |

warning: rustfmt has failed to format. See previous 1 errors.
```
Indeed, when removing the whitespace behind `...is_some(),`, cargo-fmt runs fine again.

**Comment by ted-tanner** [comment]
I saw something similar tonight, but with a blank line.

```
rustfmt --version
rustfmt 1.4.37-stable (f1edd042 2021-11-29)
```

rustfmt fails each time I try to format one particular file.

```
rustfmt src/path/file.rs --edition 2021
error[internal]: left behind trailing whitespace
  --> /the/path/to/my/file/file.rs:77:77:1
   |
77 |             
   | ^^^^^^^^^^^^
   |

warning: rustfmt has failed to format. See previous 1 errors.
```

I delete the line, and rustfmt gives no error. I add the line back (by pressing Enter, not Ctrl + Z), and rustfmt fails.

Here is the code surrounding line 77, for context:

```
69:  move || {
70:     if !&user_data.0.validate_email_address() {
71:         return Err(ServerError::InvalidFormat(Some("Invalid email address")));
72:     }
73:
74:     if let db_utils::PasswordValidity::INVALID(msg) = user_data.0.validate_strong_password() {
75:         return Err(ServerError::InputRejected(Some(msg)));
76:     }
77:    
78:     let db_connection = thread_pool.get().expect("Failed to access thread pool");
79:     db_utils::user::create_user(&db_connection, &user_data)
80:  }
```

It is quite frustrating, to be honest. The only way I can avoid the error is to remove the line (thereby violating the Rust formatting standards).

**Comment by calebcartwright** [comment]
@ZuseZ4 - Thanks for reaching out but going to close as already resolved.

If you have the ability of changing the default value of the `version` config option to `Two` you'll get the desired formatting. If not, then you'll want to break up that long string lit yourself in such a way that it's possible to fit within your max width settings.

Note that the version gate is necessary because the behavior was changed, but rustfmt output is static (outside bugs, progressive support for new syntax, etc.) which prevents us from being able to make that change by default.

**Comment by calebcartwright** [comment]
@ted-tanner - It's certainly helpful when folks try to find existing issues, but that needs to be done with careful attention with rustfmt. rustfmt is an AST driven formatter and there's certain classes of messages/errors (especially the trailing whitespace) that represent common symptoms for completely unrelated issues.

Your snippet in https://github.com/rust-lang/rustfmt/issues/5161#issuecomment-1003257479 is completely unrelated to this issue. It's also difficult to offer any insight without a fully reproducible example. If that's something you'd like us to take a look at then it'd be most helpful if you could open a new issue that includes relevant metadata (your version of rustfmt, your rustfmt config, etc.) and readily usable/reproducible snippets (please elide editor-type content like line number prefixes; the snippets should be directly usable as valid rust code)

> I delete the line, and rustfmt gives no error. I add the line back (by pressing Enter, not Ctrl + Z), and rustfmt fails.
> It is quite frustrating, to be honest. The only way I can avoid the error is to remove the line (thereby violating the Rust formatting standards).

As mentioned, would want to see any follow up discussion shifted to a new, focused issue, but are you sure your editor settings aren't inserting spaces? There's something specific to your context that's causing rustfmt to be unable to format that chain (can't say what that is without a valid input), and in these cases rustfmt just leaves whatever you had there originally. That means that you/your editor are somehow adding spaces which rustfmt is leaving in place and then later mentioning (because it recognizes trailing spaces as an indicator that it failed to format that portion of the AST)
