### ISSUE TITLE
rustfmt breaks code by ignoring tokens in macro arguments

### ISSUE THREAD

**Issue by jendrikw** [rust-lang/rustfmt#5183]
Rust macros get tokens as arguments. `||` and `|` are different tokens and should not be mixed up. This examples code relies on the fact that `|||` inside macro arguments is two tokens: `||` and `|`. Rustfmt changes the whitespace between the bar symbols so the meaning changes.

Before rustfmt:
```rust
macro_rules! m {
    (|| | || | x) => {};
}

fn main() {
    m!(
        |||
        |||
        x
    );
}
```

After rustfmt:
```rust
macro_rules! m {
    (|| | || | x) => {};
}

fn main() {
    m!(|| || || x)
}
```

The code now fails to compile:

```
error: no rules expected the token `||`
 --> src/main.rs:6:11
  |
1 | macro_rules! m {
  | -------------- when calling this macro
...
6 |     m!(|| || || x);
  |           ^^ no rules expected this token in macro call
```

**Comment by calebcartwright** [comment]
Thanks for sharing. tl;dr consider using brace delimiters for your macro calls, or using the skip attribute e.g. `#[rustfmt::skip::macros(m)]`

rustfmt is a formatter of valid rust syntax, while args to macro calls may or may not be, or in some cases like this one, are flavors of both!

Many of our users want rustfmt to also format their macro calls which is a tricky proposition given the above. The tradeoff rustfmt makes is that for calls using paren or bracket delimiters rustfmt will check to see if the args can be parsed as valid rust syntax and if so formats them according to the rules defined for whatever expression/pattern/etc. it was parsed at. However, rustfmt won't attempt to do so for calls that use brace delimiters.

You've used the paren delimiters on the `m` calls here, and those args technically _can_ be parsed and formatted as standard rust code which is why you're seeing the formatting changes.

**Comment by jendrikw** [comment]
> for calls using paren or bracket delimiters rustfmt will check to see if the args can be parsed as valid rust syntax and if so formats them according to the rules defined for whatever expression/pattern/etc

If rustfmt parses `||| |||`, it should parse as 4 tokens `|| | || |`. I don't quite understand how formatting these 4 can produce `|| || ||`.
