### ISSUE TITLE
Support for Horstmann Brace Style

### ISSUE THREAD

**Issue by ReperakDev** [rust-lang/rustfmt#5187]
As far as I'm aware, there's no way to replicate the Horstmann brace style ([Wikipedia](https://en.wikipedia.org/wiki/Indentation_style#Horstmann_style)) using rustfmt.

The motivation behind using this style is mainly combining the advantages of [K&R](https://en.wikipedia.org/wiki/Indentation_style#K&R_style) with [Allman](https://en.wikipedia.org/wiki/Indentation_style#Allman_style).
It doesn't waste a line like Allman style, but keeps the readability of Allman as well (e.g. both opening and closing braces are on the same level).

One advantage for developer productivity includes easily commenting out conditionals to force them to run (Allman also has this):
```rust
//if foo == bar
{   foobar();
}
```

If using spaces for indentation, the amount of spaces for the first statement in a block will have 1 less space than normal, to account for the opening brace.

**Example**
The following:
```rust
fn main() {
    if foo == bar {
        foobar();
    }
}
```
would be transformed into:
```rust
fn main()
{   if foo == bar
    {   foobar();
    }
}
```

**Comment by calebcartwright** [comment]
Thanks for sharing your suggestion! Unfortunately, however, this isn't something I'm willing to consider given our core goals. 

rustfmt exists to reformat according to, and check formatting against, the [Rust Style Guide](https://github.com/rust-dev-tools/fmt-rfcs). rustfmt does of course various config options (e.g. spaces vs tabs) to deal with some more granular, and typically contentious, specifics, but it's definitely not our intention to support the pretty-printer reformatting functionality for any other style.

Closing the issue accordingly

**Comment by ReperakDev** [comment]
Doesn't rustfmt already support Allman style? (`AlwaysNextLine` in `brace_style`)

**Comment by calebcartwright** [comment]
It's not clear to me what the objective is of your follow up question, but it seems more like an implicit attempt to justify your request.

To the specific question, I think the best answer is maybe? I'm not intimately familiar with all the various styles and the associated variants in the material you've referenced (and I have neither the bandwidth nor interest to spend time researching), but it seems to focus on control statements whereas rustfmt's `brace_style` is applied in expression contexts (including non control-flow expressions).

In case it was an indeed attempt to advance for your request, I'd note that the existence of one thing does not provide rationalization for creating something else, nor does the existence of that option & variant make it any easier to implement another. The option exists largely because same vs. next line brace placement is a rather common debate and subjective preference across a variety of languages, and that was something that could be reasonably (though still to this day only partially) implemented and supported.
