### ISSUE TITLE
Is it possible to use rustfmt 2.0 from rustup?

### ISSUE THREAD

**Issue by TennyZhuang** [rust-lang/rustfmt#5189]
How about add a component such as rustfmt-preview?

**Comment by calebcartwright** [comment]
Thanks for your question, but the answer is no on both fronts.

The 2.0 version was never anything more than experimental branch in source control and should be treated as such. It's unlikely to ever become official, and we're not going to go down any official (preview or otherwise) release channels, including rustup, unless that changes.

More info in #5018
