### ISSUE TITLE
Panic when formatting a macro usage with generics

### ISSUE THREAD

**Issue by Samzyre** [rust-lang/rustfmt#5208]
I get a formatter panic when running it on a file with macro usage.
No difference with `rustfmt.toml` settings all commented out.

rustfmt version:
`rustfmt 1.4.38-nightly (5e57faa7 2022-01-19)`

Error:
```
thread 'main' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler\rustc_errors\src\lib.rs:1188:13
```

Code that breaks it:
```rust
// #[rustfmt::skip] // Formatting breaks here without this
impl_widget_basic!(PairTable, 'a, 'b, L, R);
```

The macro in question *(also using macro keyword feature on nightly)*:
```rust
macro impl_widget_basic($i:ident, $b:lifetime $(,$a:tt)*) {
    impl<$b$(,$a)*> WidgetBasic<$b> for $i<$b$(,$a)*> {
        fn block(mut self, block: Block<$b>) -> Self {
            self.block = Some(block);
            self
        }

        fn style(mut self, style: Style) -> Self {
            self.style = style;
            self
        }
    }
}
```

Other uses without generics seem to be fine, though
```rust
impl_widget_basic!(BigText, 'a, 'b); // No problems here
```

**Comment by ytmimi** [comment]
Thanks for submitting this report!

I don't think this is ``rustfmt`` panicking. I mostly think that because of the panic message you included:
``compiler\rustc_errors\src\lib.rs:1188:13``

``rustfmt`` uses the parser defined in the compiler to parse your rust code into an AST, before trying to format it. It appears to me that the panic is actually happening in the compiler. It might be more appropriate to open up this issue in that repo?

**Comment by calebcartwright** [comment]
Thanks for reaching out, but going to close as this is a duplicate report of an upstream issue within the compiler (https://github.com/rust-lang/rust/issues/93282) which has already been resolved. You can update to a newer nightly to pull in the fix
