### ISSUE TITLE
Add configuration option to break function definition before return type

### ISSUE THREAD

**Issue by codeinred** [rust-lang/rustfmt#5211]
Currently, if a function definition is longer than the max_width, rustfmt will break up the function by splitting up the parameters on separate lines.

For example, this function:
```rust
fn read_lines(file: impl AsRef<Path>) -> Result<Lines<BufReader<File>>, ioError> {
    File::open(file).map(|file| io::BufReader::new(file).lines())
}
```
Becomes
```rust
fn read_lines(
    file: impl AsRef<Path>,
) -> Result<Lines<BufReader<File>>, ioError> {
    File::open(file).map(|file| io::BufReader::new(file).lines())
}
```
When formatted with a max_width of 80. Would it be possible to add a config option to insert the break before the return type, so that rustfmt will insert the break before the return type?
```rust
// Proposed format with config option enabled
fn read_lines(file: impl AsRef<Path>) 
    -> Result<Lines<BufReader<File>>, ioError> {
    File::open(file).map(|file| io::BufReader::new(file).lines())
}
```

**Comment by ytmimi** [comment]
Thanks for reaching out.

``rustfmt`` is implemented to follow the [rust style guide](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md), and [here's](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/items.md#function-definitions) the section which describes the proper spacing for functions and how to break them if they don't fit on a single line. Unfortunately, without an amendment to the style guide I don't think ``rustfmt`` would be able to support your requested formatting.

**Comment by calebcartwright** [comment]
Thanks for sharing your idea @codeinred but I concur with @ytmimi and am going to close.

As is the case with any open source project, folks are welcome to submit pull requests, and if anyone were to ever submit a complete, and holistic PR for your feature request we'd certainly give it due consideration. However, it's not something the rustfmt team will ever work on, and I don't want to imply that we're actively encouraging/soliciting contributions by leaving it open because it seems highly unlikely the benefits of such an option would outweigh the drawbacks (though I'd be happy to be proven wrong)
