### ISSUE TITLE
[Question]Why is rustfmt default edition "2015" for "rustfmt.toml" files ?

### ISSUE THREAD

**Issue by rishadbaniya** [rust-lang/rustfmt#5220]
I just wanted to know why rustfmt takes "2015" edition as default edition when no edition is explicitly mentioned on "rustfmt.toml" file or in flag for the "rustfmt". I mean, why old edition and not new edition like "2021" or "2018" as default? Wouldn't it create issues like code with "async" keyword not being formatted unless "2018" edition and above is explicitly used as a flag or in "rustfmt.toml"?

**Comment by calebcartwright** [comment]
Thank you for your question. In short, because `rustc`'s default is still 2015.

`rustfmt` doesn't really do anything with the edition but pass it along to the compiler for parsing. `cargo` aware tools, including `cargo fmt` will pick up the edition from the cargo manifest file, but if you're going to run `rustc` or `rustfmt` directly there are several cases (async included) where you'll need to provide a non-default edition value, just like `cargo` does on your behalf.

Personally, I'd love to change the default in rustfmt as well, but our hands are a bit tied to the default set by `rustc`
