### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Wandalen** [rust-lang/rustfmt#5223]
Where can I find a documentation on internals?

**Comment by ytmimi** [comment]
@Wandalen are there specific areas of the internals that you're interested in? To be honest, I'm not 100% sure if we've put together docs about the internals of ``rustfmt``. @calebcartwright do you know if we've got anything like that?

**Comment by Wandalen** [comment]
Hello @ytmimi. Thanks for the response. Some structs I have found [here](https://doc.rust-lang.org/beta/nightly-rustc/rustc_ast/ast/enum.ExprKind.html). Can I find more documentation somewhere?

I am interested in extending the `rustfmt` to make it support the code style of our company. 

Our code style is similar to the code style of the project [three.js](https://github.com/mrdoob/three.js#usage) For example we need the option to put space inside of parenthesis, like that:
```rust
fields.push( field );
```
Can I add the option? How to name it?

Also, do you have a suggestion [which issue](https://github.com/rust-lang/rustfmt/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) to resolve first to get involved in the development of `rustfmt`?

**Comment by ytmimi** [comment]
> Can I find more documentation somewhere

Maybe [this](https://docs.rs/rustfmt/latest/rustfmt/index.html) is what you're looking for? I'm not sure how up to date those docs are, and I know from working with the codebase that not everything is internally documented. You might also consider using rustdoc to build the docs for the project locally.

> I am interested in extending the rustfmt to make it support the code style of our company.

That's great! One thing to note is that rustfmt's goal is to be a faithful implementation of the [rust style guide](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md). Considering that your company has its own style guide its hard for me to say whether or not you'd be able to add those changes directly to rustfmt. I'd encourage you to hack on a fork of the project to implement your companies code style, and if you'd like to contribute those changes back to rustfmt we'll certainly consider reviewing a PR.

> do you have a suggestion [which issue](https://github.com/rust-lang/rustfmt/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) to resolve first to get involved in the development of rustfmt?

I've only been working on rustfmt for the last several months so a lot of issues pre-date me contributing to the project. Right now I don't have a more concrete recommendation than to take a look at the issues labeled with ``good first issue``, which you've linked to. Fixing any of the issues in the backlog would be a great help 😄

**Comment by calebcartwright** [comment]
Thanks for your interest @Wandalen and for sharing the info @ytmimi.

@Wandalen - there's two core themes here that I want to speak to separately, (a) trying to customize rustfmt to produce you/your company's preferred style and (b) info and contributing to rustfmt.

If you want to contribute to rustfmt that's great and we're happy to help you get started, but if your sole goal is for repurposing rustfmt (a) then I wouldn't be surprised if you decide you no longer to contribute.

As @ytmimi noted, rustfmt's purpose is to implement the Rust Style Guide. It's not out intent, nor are we willing, to let rustfmt be transformed into something that can be used reformat any input to any/every person/company's preferred output.

Similar to other formatters like prettier (JS/TS), black (python), and in many ways gofmt (Go), rustfmt's output is very opinionated and based on the aforementioned Style Guide that was built up over the years via an RFC process, with the goal of having a generally consistent style/look and feel for Rust across codebases.

Code style is obviously a very personal thing, and there were several topics that only had a narrow consensus (e.g. spaces vs. tabs) so rustfmt does provide some configuration options to give users some flexibility. However, every configuration item has a cost, both on rustfmt itself in terms of maintenance, bug surface, etc. and in some ways on users via cognitive load.

While we're generally willing to consider a request/proposal for a new option, we don't accept any/every proposal either. The exaggerated example I typically use is that we're not going to accept a proposal for some new config option that would add 5k lines of code we have to maintain just because it supports some bespoke style which isn't really used in Rust.

> Our code style is similar to the code style of the project [three.js](https://github.com/mrdoob/three.js#usage) For example we need the option to put space inside of parenthesis, like that

In general, I'd strongly recommend that you instead pivot to apply Rust Style to Rust code, and not try force a style from a project in another language. It's definitely not a goal of ours to support having rustfmt output look like anyone's JavaScript style, nor any style in any other language.

You are welcome to open an issue for discussion on an individual config option. I'd actually suggest starting with one or two of those first to see how reasonable it may or may not be. You are also welcome to submit Pull Requests with implementation proposals for new options, and we'll give those due consideration against the factors I previously described. However, if you end up deciding to work on something that's outside our core focus area, you'll need to do so independently because we simply do not have the bandwidth to contribute time/effort to things outside rustfmt's core focus area.


I'm going to close this now but if you're still generally interested in contributing to rustfmt and working on things on our backlog then I'm happy to point you to some material that should be helpful. You can also post contributing-types of questions on Discord as well. However, if you're no longer interested in doing so since it's almost a certainty that rustfmt will never produce your company's preferred style as output, then that's perfectly understandable too!

**Comment by Wandalen** [comment]
@calebcartwright my prime goal is success of the company I work for and secondary contributing to Open Source including `rustfmt` especially if openness and friendliness is part of the culture around the project. Hopefully it is the case. 

Is lack of good documentation an intentional strategic step to keep developers and companies which didn't take part in the forced "consensus" out of the business by complication the process of adding option to support their styles?

**Comment by calebcartwright** [comment]
> Is lack of good documentation an intentional strategic step to keep developers and companies which didn't take part in the forced "consensus" out of the business by complication the process of adding option to support their styles?

I'm rather confused as to why you decided to take this tone in your last response @Wandalen. These types of snarky insinuations aren't helpful, and I'd ask that you refrain from them in the future. I also unequivocally reject the premise of your question.

While documentation can always be improved, I would note that as is standard practice we have a [Contributing.md](https://github.com/rust-lang/rustfmt/blob/master/Contributing.md) file in the project root, which is also [directly linked from the top of the main Readme](https://github.com/rust-lang/rustfmt#rustfmt----). That Contributing document contains various important information for contributors, including a [walk through of the codebase](https://github.com/rust-lang/rustfmt/blob/master/Contributing.md#a-quick-tour-of-rustfmt) as well as direct links to the nightly compiler internal docs, e.g. [rustc_ast](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/ast/index.html), which rustfmt (like many dev tools) relies on heavily amongst other compiler internals. You will also find that [root site](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/index.html) includes the docs for all mods, which **includes** rustfmt as well, e.g. [rustfmt_nightly](https://doc.rust-lang.org/nightly/nightly-rustc/rustfmt_nightly/index.html)

I don't personally think it's necessary (or even helpful for that matter) for new contributors to attempt to read and consume all that material in order to submit a first a PR, but the material exists and is advertised in standard places.

Despite your inquiry being rather vague, folks here have been helpful throughout and tried to get a better understanding of your ask while also providing you some of the same links. Then when it became apparent that your impetus was to customize rustfmt so that it could produce your company's flavor of a style followed JavaScript project, we were transparent with you about that most likely not being possible. I realize that's not what you wanted to hear, but I think it's important that you have the relevant info up front because you/your company may decide that it's easier to not use rustfmt (much less contribute to it) so that you can better maintain your personal style.

Given all the above, I really don't understand why you felt the need to make unfounded accusations of malevolence.

I'll repeat something I said previously to point you back to similar style formatters predominant with their respective languages to take note of the common goals found across major formatters. Automated code formatters do not typically exist in order to allow anyone to be able to enforce any personal style that they have, but instead strive to follow a common style. Despite this goal, some like rustfmt are still heavily configurable, while others like gofmt or prettier have minimal or no configurability whatsoever.

I promise that if you went to the [prettier](https://github.com/prettier/prettier) team and asked them the same question about extending/customizing prettier to support your personal style flavor that you'd get a categorical "no" answer, and that's a formatter for the same language. Despite Rust being a very different language, we've told you "probably not" in the spirit of transparency, but also outlined some steps you could take if you wanted to continue to investigate your options of working with rustfmt.

You're still quite welcome to take those steps if you chose, and again if you're determined to stick with your own style flavor then I'd suggest you first do some analysis to figure out the delta between what's already possible today with existing options and what you'd need. If you decide to continue engaging in dialog here though, I would ask you to be more mindful of how you choose your words going forward.

**Comment by Wandalen** [comment]
Hi @calebcartwright. I don't accuse you but rather asked for confirmation of logical conclusions with which I came up. They are based on what you said, what you did, and what I encountered exploring the project. I have been transparent from the beginning and I hope you don't find that offensive. 

Thank you for your recommendations, it is worth taking them into account. Reading contributing is also useful, although it's a very long document. I suggest adding "where is the documentation" to your QA. 

Regarding respectful tone, I don't find your speculation about the code style I mentioned as an appropriate one. Please don't call our code style JavaScript style and don't assume superiority of your code style over any other. Although I  agree there is an economic benefit from standardization I don't think any code style could be objectively better than all others. As well as I believe openness and friendliness should stay part of the culture around Rust and related projects. And excluding and forcing others rather than inviting them to follow the style contradicts those core values, personally, I so love in Rust community.  

Given all the above, I really hope to find support and understanding.

**Comment by calebcartwright** [comment]
I feel like this thread came to a logical conclusion long ago, and I don't see much utility in continuing dialog here.

It doesn't matter that your prior comment was framed in the form of a question. What you said was unkind, unhelpful, and not in accordance with the type of discourse we have here. There's no point in trying to rationalize it, just don't do it again.

In your subsequent comment you're also now rather bizarrely critiquing me for things which I quite obviously never said, as well as for assumptions I have not made, and certainly never expressed nor implied. I'm not going to engage such fallacies with a direct response.

All we've done is stressed that your stated goal and the goals of this project don't align, and you seem to have taken offense at that being the case and for some reason are incorrectly assuming myriad other explanations. I do not understand why that is, but I'm sorry you feel that way. However, please don't twist nor misrepresent things by putting words into other's mouths.

I don't think there's really anything left that needs to be discussed here. Your questions have been answered. Documentation is readily available within the project and links have additionally been provided inline. And despite your stated goal being contradictory to the goals of this project, we've still given you some specific recommendations on things you can do to see if it might still be possible for you to achieve an acceptable outcome.

Those are the concrete, actionable steps you would need to take next should you decide to continue trying to move forward.

**Comment by Wandalen** [comment]
Thanks!
