### ISSUE TITLE
Trailing comma in enum or-pattern

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rustfmt#5279]
Imagine [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=71f70131a16583ba32e31da19fd77cb3):

```rust
pub fn fmt_me(wrap: Wrap) {
    match wrap {
        Wrap::A(
            LongerName::One
            | LongerName::Two
            | LongerName::Three
            | LongerName::Four
            | LongerName::Five
            | LongerName::Six
            | LongerName::Seven
            | LongerName::Eight
            | LongerName::Nine,
        ) => {}
    }
}
```

The trailing comma after `| LongerName::Nine` is unnesscary and doesn't really fit into the pattern, although it doesn't create a syntax error.

IMHO that code shouldn't have trailing comma. What's your opinion?

**Comment by ytmimi** [comment]
Thanks for submitting the issue and for the PR!

**Comment by calebcartwright** [comment]
> IMHO that code shouldn't have trailing comma. What's your opinion?

This behavior is correct so I'm going to close the PR but will leave the issue open for any follow up discussion. The formatting is dictated by the respective rules in the style guide and doesn't really have anything to do with an or pattern in this case.

Note the relevant rules for [enums](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/items.md#enums), [tuples and tuple structs](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/items.md#tuples-and-tuple-structs), and [calls](https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/expressions.md#multi-line-calls):

(emphases mine)

> Format each variant accordingly as either a struct, **tuple struct**, 

> Write the type list as you would a parameter list to a function.
> Build a tuple or tuple struct as you would call a function.

> If the function call is not small, it would otherwise over-run the max width, or any argument or the callee is multi-line, then the call should be formatted across multiple lines. In this case, each argument should be on its own block-indented line, there should be a newline after the opening parenthesis and before the closing parenthesis, and **there should be a trailing comma**

It's the multi-line nature forcing the multi-line "call" like behavior that necessitates the trailing comma.

We could, technically, produce the behavior you'd prefer via some new config option. However, while that would be straightforward to implement, I'd be highly hesitant to do because it feels _highly_ specific and doing so would essentially open the floodgates of very specific pairings of AST types in specific contexts which could wreak havoc on our config surface, add user-facing complexity, etc.

**Comment by hellow554** [comment]
Hey @calebcartwright, thanks for your reply!

I see a few things here and let me try to convince you otherwise.

The whole point of a trailing comma (IMHO) is to make diffs and line swaps simpler.

w/o trailing:
```diff
@@ -4,6 +4,7 @@ fn main() {
         "short",
         "long string",
         "longer string",
-        "longest string"
+        "longest string",
+        "even longer string"
     ];
 }
```

w/ trailing:
```diff
@@ -5,5 +5,6 @@ fn main() {
         "long string",
         "longer string",
         "longest string",
+        "even longer string",
     ];
 }
```

And for or pattern inside of a match, we currently have this behavoir:
```diff
@@ -28,6 +29,7 @@ pub fn fmt_me_too(wrap: Wrap) {
         | Wrap::A(LongerName::Two)
         | Wrap::A(LongerName::Three)
         | Wrap::A(LongerName::Four)
-        | Wrap::A(LongerName::Five) => {}
+        | Wrap::A(LongerName::Five)
+        | Wrap::A(LongerName::Six) => {}
     }
 }
```

This is not avoidable because of `=>` which needs to be on the same line as the last or case.

But for my case the state of today would be:
```diff
@@ -17,7 +18,8 @@ pub fn fmt_me(wrap: Wrap) {
             | LongerName::Two
             | LongerName::Three
             | LongerName::Four
-            | LongerName::Five,
+            | LongerName::Five
+            | LongerName::Six,
         ) => {}
     }
 }
```

whereas it could be
```diff
@@ -19,6 +19,7 @@ pub fn fmt_me(wrap: Wrap) {
             | LongerName::Three
             | LongerName::Four
             | LongerName::Five
+            | LongerName::Six
         ) => {}
     }
 }
```

and exactly this is my motivation for this issue and the PR.


Also a few things I'd like to mention:

  1. a `,` makes no sense at all in the end of a or pattern inside of the match. Items are not seperated by a `,`, but by a `|` instead. This makes this situation so unique
  2. There was no testcase for this behaviour so far. Also I didn't modify or break any existing tests.
  3. I don't think a new option is necessary here. Either adjust the existing style guide and/or add an exception to this rule where it makes sense, e.g. where a comma is not the seperator of items, but other things. This is already done in other places, e.g. the expression of an `if`:
  ```rust
if long_function_name
        && long_function_name
        && long_function_name
        && long_function_name
        && long_function_name
    {}
```

  doesn't end with a trailing comma. 



I would very much like to see "my style" to be implemented. It might be a niche, but it helps IMHO as for the reasons above.

**Comment by calebcartwright** [comment]
You're conflating a number of things here that may seem subtle but which are fundamentally different constructs from an AST perspective. You're also still too focused on the pattern piece as opposed to the containing tuple which is where the relevant rules come into play. 

Consider the scenario where the tuple for the `A` variant of your `Wrap` enum were modified to require another element:

```rust
pub enum Wrap {
    A(LongerName, usize),
}
```

The comma becomes strictly necessary, regardless of what type of pattern you may have used for the first element or where you may have constructed/deconstructed instances, and subsequent additions can be made without the extra lines in the diff (which you alluded to as the motivation for trailing commas, and yes, that's one of the reasons why the Rust Style Guide prescribes them)

Trailing commas after elements in a collection, including the vector of contained pats in a tuple pat, are valid syntax, often required, and beneficial in line-wrapped cases whereas a trailing comma in all your counter examples (as you noted in one instance) is invalid syntax, including after the conditional expression within an if expression. These are completely orthogonal and it's not a sufficient rationalization to say that the absence those syntactical invalid commas is justification for eliding syntactically valid commas.

It'd be the same as trying to argue that call expressions shouldn't have a trailing a comma because a trailing comma is illegal syntax after the initializer in a local assignment statement.


> @ytmimi brought up a similar and interesting pattern in https://github.com/rust-lang/rustfmt/pull/5280#issuecomment-1082569595

You similarly cannot compare arguments to a macro call against standard Rust constructs outside a macro context. rustfmt's support for macros is very limited, and we absolutely don't want to try to degrade how we format standard Rust code in order to be "consistent" with that limited macro behavior. To be more specific, rustfmt doesn't add/remove tokens, such as commas, in most maccall contexts because doing so can fail to preserve semantics in many cases. If you were to add a comma on the end of that "pattern" in the `matches!` call you would notice the comma is maintained. (the second arg also gets parsed as a binary expression and not an or pattern, but that's another topic entirely).

> I would very much like to see "my style" to be implemented. It might be a niche, but it helps IMHO as for the reasons above.
> I don't think a new option is necessary here. Either adjust the existing style guide and/or add an exception to this rule where it makes sense, e.g. where a comma is not the seperator of items, but other things. 

Sorry, but no, it's not going to happen. I appreciate that's not the outcome you were hoping for, but there's no chance we'll modify rustfmt to explicitly contradict the style guide, and there's no chance of making an unequivocally breaking change to the style guide to bend to a personal preference.

The only possible venues for you to get "your style" would be via config options, either via the existing [trailing_comma option](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#trailing_comma) or via some hypothetical new option I alluded to before.

**Comment by calebcartwright** [comment]
Feel free to add additional comments if you'd like to continue the discussion, but going to close as I don't see any action to be taken (and if we do end up exploring a config option I think that'd be best served in a PR or separate issue more narrowly scoped to the config piece)
