### ISSUE TITLE
cargo installation shows `rustfmt` is deprecated

### ISSUE THREAD

**Issue by georgettica** [rust-lang/rustfmt#5300]
after installing with cargo, the rustfmt shows it's deprecated
```
$ cargo install rustfmt
$ rustfmt
This version of rustfmt is deprecated. Use rustfmt-nightly. Use --force to run deprecated rustfmt.
```

I want to use the rustfmt-nightly but it errors out
```
$ cargo install rustfmt-nightly
...
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> ${HOME}/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.8.0/src/lib.rs:83:37
   |
83 | #![cfg_attr(feature = "may_dangle", feature(dropck_eyepatch))]
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^
```

is that something that is planned to be fixed?

I am not using `rustup` as I installed cargo using `brew` (macos non M1 user)

please let me know how I can provide more input / close in favor of another card

**Comment by ytmimi** [comment]
Hey @georgettica seems like you were able to solve the issue on your own, which is great! Just want to double check the command you used in case this comes up again did you actually run `cargo fmt -- --force`? or did you run

```
cargo install --force -- fmt
```

**Comment by georgettica** [comment]
No, I wasn't able to install the nightly, but I was able to make devs be able use `cargo fmt`
This is on stable rustfmt

**Comment by ytmimi** [comment]
Since I'm using `rustup` to install various components like `rustfmt` i'm not as familiar with using `cargo install`. Appologies if I'm misunderstanding something. If you've got a moment could you describe the steps you took to fix the issue you were running into?

**Comment by georgettica** [comment]
so with cargo you:
```
cargo install rustfmt
# installed the stable and deprecatred
cargo install rustfmt-nightly
# fails but is supposed to install 
```

I think it's also related to me not installing a cargo in a `nightly` fashion

**Comment by calebcartwright** [comment]
Thank you for reaching out but I am going to close as this is very much intentional.

We do not distribute rustfmt through crates.io anymore and haven't for quite some time. The `rustfmt` crate on crates.io is [quite explicitly deprecated](https://crates.io/crates/rustfmt). The `rustfmt-nightly` [crate](https://crates.io/crates/rustfmt-nightly) has been functionally deprecated for well over a year, though I admittedly keep forgetting to explicitly mark it as deprecated.

The overwhelmingly best way to get `rustfmt` onto your system is via rustup, just like all the other official tools, as noted in our [documentation](https://github.com/rust-lang/rustfmt#on-the-stable-toolchain). I would **strongly** encourage you to follow the [standard, recommended](https://www.rust-lang.org/tools/install) route for setting up your machine which is all driven via rustup. It's technically possible to avoid rustup in some scenarios, but doing so is going to make the basics of environment setup unduly complicated.

I cannot speak for the other tools you'll most likely need (clippy, rustdoc, IDE/editor support via RA or RLS, etc.) but the only other ways you could get rustfmt would be to grab one of our pre-built binaries from our [GitHub releases](https://github.com/rust-lang/rustfmt/releases) or to compile rustfmt from source.

As you'll note the GitHub releases are comparatively few and far between, and quite old; you may have issues trying to use them with newer syntax. Attempting to compile rustfmt from source would put you right back into the scenario of needing rustup because you'd need to grab a nightly toolchain from a specific subset and extra components that contain the required bits of the compiler internals that tools like rustfmt need (defined in the [toolchain file in the repo root](https://github.com/rust-lang/rustfmt/blob/master/rust-toolchain)

**Comment by georgettica** [comment]
Ok, I'll see if I can ask the macos community to add rustup to the installation so I can use it.

Thank you for the lengthy response!

**Comment by calebcartwright** [comment]
Sure thing! However, I'm not really sure what you think you need the mac community to do.

Rustup is already readily available and usable on your platform, just follow the aforementioned installation process. Are you trying to avoid downloading rustup as provided by the Rust/Rustup team?

**Comment by georgettica** [comment]
I am trying to install using a versioned and stable installation using brew (maybe that's why it prefers a `stable` release)
