### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by Aunmag** [rust-lang/rustfmt#5304]
There were no rustfmt updates since [Oct 23, 2021](https://github.com/rust-lang/rustfmt/releases/tag/v1.4.38). And I'm kind of worried is everything ok? How does it go?

P.S.: I'm sorry if this issue is not the right form for such a question.

**Comment by calebcartwright** [comment]
It's fine to ask questions here but I'm going to close this. You've made an inference which is not entirely unreasonable, but which is also entirely incorrect. There's been countless (practically speaking) updates to rustfmt since October of last year.

rustfmt is primarily and officially distributed through rustup. That's all driven by the contents of source code, first in this repo where we do active development on rustfmt and then in the main rust-lang/rust repo where we sync our changes because that's where the toolchains are built.

The GitHub releases in this repository, which you've linked to, are not a primary means of distribution and thus do not accurately reflect status, neither in terms of development nor in terms of official releases. We try to use the GitHub releases as periodic snapshots for people that want to grab and pin to a specific pre-built binary, but it's getting increasingly untenable to try to create these snapshots and I'm not sure how much longer we'll continue to do so.

To get a more accurate picture of activity I would instead point you to the commit history on the trunk branch of this repository, as well as the history on the rustfmt directory in rust-lang/rust

https://github.com/rust-lang/rustfmt/commits/master
https://github.com/rust-lang/rust/commits/master/src/tools/rustfmt
