### ISSUE TITLE
error[internal]: left behind trailing whitespace

### ISSUE THREAD

**Issue by sloganking** [rust-lang/rustfmt#5315]
rustfmt fails to format with error message ``error[internal]: left behind trailing whitespace`` when a ``space`` character comes after assignment operator, and what's being assigned is a multi-line string on the next line.

![](https://i.imgur.com/V1wFlPS.png)

**Happens with cargo version:** ``1.60.0``

**Code this happens with:**
https://github.com/sloganking/Structured-commenting-formatter/tree/51459daa4318be0c163c3f40f148073de39342fa

**Commit that caused it:**
https://github.com/sloganking/Structured-commenting-formatter/commit/51459daa4318be0c163c3f40f148073de39342fa

**Comment by ytmimi** [comment]
Thanks for the report.

The issue that you're running into here is that line 18 is longer than the default max width of 100. rustfmt fails to format the multiline string because of this, which leads to the assignment not being rewritten and because rustfmt doesn't rewrite the assignment it also doesn't remove the trailing whitespace from the input text. 

The error message indicates that the input text contained a trailing pace that rustfmt could not remove.

You should be able to format the input if you bump up the `max_width` to a value larger than the length of line 18.

**Comment by VictorBulba** [comment]
Hey!

```rust
fn f() {
    match () { 
        _ => {
            ();
        }
        //
        //,
    }
}
```

Fails with the same error

**Comment by ytmimi** [comment]
@VictorBulba Thanks for reaching out. Since your example happens in the context of a match arm I don't think these two are related, however #4037 seems to outline the same issue you're describing here!

**Comment by ytmimi** [comment]
Going to close this as there's no action we can take at this time. The solution in this case is to either remove the whitespace by hand or bump up the `max_width` so that rustfmt can properly format the code.

**Comment by joroKr21** [comment]
> Going to close this as there's no action we can take at this time. The solution in this case is to either remove the whitespace by hand or bump up the max_width so that rustfmt can properly format the code.

A code formatter should never fail on valid code. That breaks editors downstream that use the formatter e.g. on file save.
