### ISSUE TITLE
slow execution on nexted closures

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rustfmt#5318]
````rust
// Check that this can be compiled in a reasonable time.

// build-pass

fn main() {
    // 96 nested closures
    let x = ();
    || || || || || || || ||
    || || || || || || || ||
    || || || || || || || ||
    || || || || || || || ||

    || || || || || || || ||
    || || || || || || || ||
    || || || || || || || ||
    || || || || || || || ||

    || || || || || || || ||
    || || || || || || || ||
    || || || || || || || ||
    || || || || || || || ||
    [&(), &x];
}
````
this file took more than 4 hours (it's still running) to `--check` on my system.

**Comment by calebcartwright** [comment]
That seems like a fairly pathological input, but for what it's worth this has already been addressed in source (takes ~20 seconds on the machine I'm on at the moment, and it has some very old and weak specs).

There's some paths that have existed historically in rustfmt that can hit some unfortunately exponential runtimes in exceptionally nested expression cases, though that was also something that only generated code would ever hit in practice since humans wouldn't typically write code that way.

The fix is fairly recent and hasn't been released yet, but should be in the next one. As such I'm going to close, but feel free to build rustfmt from source and run it locally if you'd like to confirm yourself.
