### ISSUE TITLE
rustfmt doesn't understand if let chains

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-lang/rustfmt#5333]
See https://github.com/rust-lang/rust/issues/53667, they might be stabilized soon. Currently, rustfmt refuses to make any changes to an if let statement and its contents, silently letting code go unformatted.

**Comment by ytmimi** [comment]
Thanks for the report.

This is related to #5177, and the PR that adds this support (#5203) is intentionally on hold. I don't know if I can articulate it any better than https://github.com/rust-lang/rust/pull/95262#issuecomment-1077692898 and https://github.com/rust-lang/rustfmt/pull/5203#issuecomment-1035843143.

To summarize, there are still some unanswered questions around `let-chain` formatting being discussed on https://github.com/rust-dev-tools/fmt-rfcs/issues/169. It's important that the formatting RFC be resolved so we know what rules to implement in rustfmt because there's a strong desire not to continually introduce breaking formatting changes.

The best way to move things forward is to bring broader awareness to https://github.com/rust-dev-tools/fmt-rfcs/issues/169 and to share your thoughts on the proposal 😁

**Comment by SUPERCILEX** [comment]
Thanks for the explanation!
