### ISSUE TITLE
rustfmt reports `left behind trailing whitespace`

### ISSUE THREAD

**Issue by feds01** [rust-lang/rustfmt#5336]
In the following code snippet that has been extracted from a bigger project:

```rust
pub fn foo() -> () {
    match gen.peek() {
                    Some(token) => gen.error_with_location(
                        baz,
                        
                        Some(from_x(
                            x![&self.wall; TokenKind::Eq, TokenKind::Comma, TokenKind::Delimiter(Delimiter::Brace, false)],
                        )),
                    ),
                }
}
```

`rustfmt` reports that there are left behind trailing whitespace:

```
error[internal]: left behind trailing whitespace
 --> ~/playground/main.rs:5:5:1
  |
5 |                         
  | ^^^^^^^^^^^^^^^^^^^^^^^^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

Removing the empty spaces from the `match` block results in `rustfmt` to report that the sources have been successfully formatted but it looking at the diff it seems that nothing changes.

## Reproducing:
- Use above code snippet
- Use `cargo 1.62.0-nightly (a44758ac8 2022-05-04)` with `rustfmt 1.4.38-nightly (30f38608 2022-05-05)`
- Run `cargo fmt`

**Comment by calebcartwright** [comment]
Thanks for reaching out but I'm going to close as this is a combination of duplicate reports discussed elsewhere (e.g. #8, #3863, etc.).

rustfmt can't handle your `x` macro call (as it can't be parsed and formatted as a typical AST construct), so it in turn leaves the call alone. You've written that call in a long single line which exceeds the max width limits, and that then bubbles up because it's part of a nested argument with a chain (that starts with `gen.error_with_location`). This then hits the behavior of rustfmt leaving the entire chain as you wrote it, including with the trailing whitespace that produces the message.

There's really not much that can be done to "fix" this apart from you manually wrapping your macro call to give rustfmt the freedom to be able to format the chain in the arm body and the containing match expression (you may have to adjust once or twice manually but the result will be idempotent)
