### ISSUE TITLE
It should be possible to run rustfmt _only_ on doc comments

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rustfmt#5345]
There's a new `format_code_in_doc_comments` config which is quite useful and nice.

However, it formats the _entire_ codebase, including non-doc comment code. This can cause challenges since it's quite likely folks may want a separate set of configs for doc comments: chief of which would be line length restrictions. Rustdoc renders code blocks with a pretty large font and typically the code is written with far more wrapping.

It would be nice to be able to run rustfmt twice, once for regular code, once for doc comments, with different settings, perhaps with a `format_code_in_doc_comments_only` flag.

**Comment by calebcartwright** [comment]
This feels a bit like a particular solution to a problem that I'm not sure I fully understand even after glancing through the comments on the upstream PR.

Was the motivating scenario a desire to use a different/shorter width limit for code in doc comments, independent of the overall `max_width` and `comment_width`?

**Comment by calebcartwright** [comment]
Thanks for confirming and clarifying. Though technically possible, I don't think it's going to be practical to try to go down the path of an entirely separate, doc comment only formatting mode (I can elaborate if need be).

What would be more straightforward is a new option that allows for controlling the width limit of code blocks separate from the other two options so that a shorter width limit could be set explicitly for those code blocks, e.g. a new `doc_comment_code_block_width` option or something more succinctly named.

Do you feel like that would provide a sufficient resolution to the need to be able to force wrapping more aggressively in doc code blocks?

**Comment by Manishearth** [comment]
I think so, yes! I don't think the general feature is as necessary

**Comment by calebcartwright** [comment]
Have opened #5359 to track implementation of the discussed option, will keep this separate and open as the articulation of the problem-to-be-solved. Will revisit once the option is available to confirm it will suffice, and close this if so.

**Comment by ytmimi** [comment]
[doc_comment_code_block_width](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#doc_comment_code_block_width) was [added in the v1.5.1 release](https://github.com/rust-lang/rustfmt/blob/master/CHANGELOG.md#added), and should be available on nightly now!

**Comment by calebcartwright** [comment]
Thanks for triaging this issues! However, going to reopen this actually to give the team time to test drive the solution and see whether it actually allows them to address the original problem.

Let us know if/how it's working out for you Manish

**Comment by Manishearth** [comment]
Thanks!

**Comment by Manishearth** [comment]
It works pretty nicely! Setting it to 80 seems quite ideal for us.
