### ISSUE TITLE
/* comment */ inside trait generics gets duplicated

### ISSUE THREAD

**Issue by xhalo32** [rust-lang/rustfmt#5358]
```rust
trait Test</* comment */ T> {}
```

Gets reformatted as

```rust
trait Test</* comment */ T> /* comment */ T> {}
```

Whereas no changes were expected.

Playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=88c36ba8a83e2c01030bbbf95327be6a

Setting `version = Two` has no effect.

```
λ rustfmt --version
rustfmt 1.4.38-stable (7737e0b 2022-04-04)
```

**Comment by calebcartwright** [comment]
Thank you for the report! This feels like a bug with duplicative/overlapping comment recovery that's probably using the wrong span. The bug doesn't occur if there's a where clause present, so I suspect the problem is somewhere around here:

https://github.com/rust-lang/rustfmt/blob/79515f17ed4661da864347c90c76c51f9bf86069/src/items.rs#L1084-L1104

For anyone interested in taking a look, we should probably reduce the area that's being scanned for comments there to something less than the entire span of the item (most likely simply from the end of the where clause's span to the start of the body span)
