### ISSUE TITLE
Rustfmt wrongly alphabatizes raw identifiers in `use` statements

### ISSUE THREAD

**Issue by InsertCreativityHere** [rust-lang/rustfmt#5362]
# Description

I'm writing a toy compiler, and recently split up the elements of my grammar into their own modules.
Unfortunately, there's overlap between the elements and some Rust keywords, so sometimes I need to use raw identifiers:
```
use self::r#enum::*;
use self::interface::*;
use self::struct::*;
```
I would expect these to be sorted alphabetically, _not including the `r#`_
But, rustfmt seems to include it when sorting, and changes this to:
```
use self::interface::*;
use self::r#enum::*;
use self::struct::*;
```

Note that this _doesn't_ happen with modules:
```
mod r#enum;
mod interface;
mod struct;
```
here rustfmt correctly ignores the `r#` prefix when sorting.

I'm open to fixing this, if someone could point me in the right direction! Since it *seems* \*crosses fingers\* like an easy fix.

# Environment

rustfmt 1.4.38-nightly (e0944922 2022-05-31) on macOS Monterey

**Comment by calebcartwright** [comment]
Thanks for reaching out and being willing to work on it!

Fortunately (perhaps), this is one that was actually already reported (see #3791) and fixed in source control a while ago (and #3795).

However, the fix was made on a different branch that hasn't been pulled in yet. The only outstanding issue is that it technically qualifies as a formatting change which we have to gate against, and no one has had the time/motivation to figure out how to apply the gating yet.

Definitely feel free to take a look at the old PR, you may be able to cherry-pick the commit and apply @ytmimi's suggestion from https://github.com/rust-lang/rustfmt/pull/3795#issuecomment-1086893881 to gate the change, and let us know if you have any questions.
