### ISSUE TITLE
rustfmt does not collapse foo::{self}

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/rustfmt#5398]
```rust
use foo::self;
```

is collapsed to:

```rust
use foo;
```

But this:

```rust
use foo::{self};
```

is kept as is.

Used `rustfmt` from master (2022 Jun 22) with `rustfmt.toml` from `rustfmt` repo.

This behavior doesn't look intentional.

**Comment by ytmimi** [comment]
@stepancheg, thanks for reaching out.

I can't find any great documentation on the topic, but the two cases you mention aren't equivalent. The best resource I can link you to are the discussions in #3568, #4681, and https://github.com/rust-lang/rust/issues/60941

A brief summary of the issue is that each import brings different things into scope so converting `use foo::{self};` to `use foo;` could cause compilation problems. rustfmt can't safely make that transformation and leaves the import alone.

**Comment by stepancheg** [comment]
@ytmimi thank you for the explanations!
