### ISSUE TITLE
Regression (poor-formatting) in macros formatting since 1.50

### ISSUE THREAD

**Issue by maxwase** [rust-lang/rustfmt#5419]
Since 1.50 the following macros:
```rust
macro_rules! format_me_wrong {
    ($prefix:ty |$arg1:pat, $arg2:pat_param| $code:expr) => {};
}
```
formats like this:

```rust
fn main() {
    format_me_wrong!(
        bool | _,
        _ | {
            true;
            true;
        }
    );
}

```
instead of this:

```rust
fn main() {
    format_me_wrong!(
        bool | _,  _ | {
            true;
            true;
        }
    );
}
```

The key part is to have a literal before "closure" and 2+ lines after "closure"

**Comment by calebcartwright** [comment]
I'd seen this but hadn't had a chance to respond yet. My assumption was that @maxwase was referring to the Rust 1.50 release and the version of rustfmt that shipped with it, not the recent rustfmt version from a couple weeks ago (rustfmt is versioned independently of the compiler).

I also suspect that this is not a regression at all, but is simply reflective of the limits of formatting args to macro calls, and that if one were to go back to rust 1.49 you'd discover rustfmt actually isn't formatting the call at all (which can be tested by modifying the input to be highly misformatted which should be left as-is by rustfmt).

For context, rustfmt is a formatter of Rust syntax. Args to macro calls aren't always valid Rust syntax strictly speaking. In order to support the desire of our users for rustfmt to provide _some_ formatting for calls, rustfmt will attempt to see if args can be parsed as valid rust syntax, and if they can, then rustfmt applies the corresponding rules. In some cases, args to calls can actually be parsed as valid syntax, but that's not actually what was intended.

In this case, those args can be parsed as binary expressions and are formatted as such. This isn't a regression, and isn't going to change.

As such if you'd like different formatting your options are to change the call delimiters to `{}` or to skip the formatting of the call(s) altogether

**Comment by maxwase** [comment]
> As such if you'd like different formatting your options are to change the call delimiters to `{}` or to skip the formatting of the call(s) altogether

Oh, thanks!

**Comment by calebcartwright** [comment]
I should also add that if you don't want to change the delimiters, then the only way to currently skip would be via attributes applied on each call (https://github.com/rust-lang/rustfmt#tips).

However, we will also be adding a new configuration option in an upcoming release (#5347) which will allow you to designate macro calls to be skipped for formatting from one place in your config file
