### ISSUE TITLE
Skip only comment?

### ISSUE THREAD

**Issue by alexschrod** [rust-lang/rustfmt#5440]
I have this comment that I don't want rustfmt to touch, so I tried putting `#[rustfmt::skip]` on it, like so:
```
#[rustfmt::skip]
/*
    Pointer	Code points	Notes
    1133	U+00CA U+0304	Ê̄ (LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND MACRON)
    1135	U+00CA U+030C	Ê̌ (LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND CARON)
    1164	U+00EA U+0304	ê̄ (LATIN SMALL LETTER E WITH CIRCUMFLEX AND MACRON)
    1166	U+00EA U+030C	ê̌ (LATIN SMALL LETTER E WITH CIRCUMFLEX AND CARON)
 */
const SPECIAL_POINTERS:[u32;4] = [1133,1135,1164,1166];
```
Unfortunately, this also leads to the code line below the comment to be skipped; as you can see, it hasn't fixed up the `:[u32;4]` or added spaces after the commas. However, if I remove the `#[rustfmt::skip]`, the comment gets mangled as the code line gets fixed.

There's an obvious fix here, of course, which is to cut the comment and the `#[rustfmt::skip]` attribute, let rustfmt format the line, and then paste them back. But that only works *right now* and if the line was to be changed in the future, it'd be left untouched by rustfmt again, which is undesirable.

**Comment by calebcartwright** [comment]
> I still think it'd be nice to have a directive that just skipped a comment from being formatted but not any code it was attached to, but I'd understand if you closed this comment as a non-issue.

Agreed with @ytmimi, and also want to add that I understand this ask and it's something we'd be open to considering. However, attributes wouldn't be an appropriate avenue because syntactically it's not the comment that's being attributed, it's the item, expression, etc.

Perhaps some kind of marker within the comment itself could be considered one day, e.g.:

```rust
/* rustfmt::avert-your-eyes
....
```

but even still there'd likely be some edge cases due to rustfmt working with the AST, and not the underlying tokens and characters in the source files
