### ISSUE TITLE
`format_code_in_doc_comments` formats some long line comments to block comments

### ISSUE THREAD

**Issue by pan93412** [rust-lang/rustfmt#5533]
## Meta

- **rustfmt version**: `rustfmt 1.5.1-nightly (b44197ab 2022-09-05)`
- **Minimum reproducible repo**: <https://github.com/pan93412/rustfmt-format-code-in-doc-comments-issue-repro-220906>
- **rustfmt configuration**:
  ```toml
  format_code_in_doc_comments = true
  ```

## Description

After enabling `format_code_in_doc_comments`, rustfmt formats the following line comments to block comments – which is neither a documented nor an expected behavior.

```rust
struct TestStruct {
    position_currency: String, // Currency for position of this contract. If not null, 1 contract = 1 positionCurrency.
    pu: Option<i64>, // Previous event update sequense ("u" of previous message), -1 also means None
}
```

## Expectation

`rustfmt` should not touch this.

```rust
struct TestStruct {
    position_currency: String, // Currency for position of this contract. If not null, 1 contract = 1 positionCurrency.
    pu: Option<i64>, // Previous event update sequense ("u" of previous message), -1 also means None
}
```

## Actual Result

```rust
struct TestStruct {
    position_currency: String, /* Currency for position of this contract. If not null, 1 contract = 1 positionCurrency. */
    pu: Option<i64>, /* Previous event update sequense ("u" of previous message), -1 also means None */
}
```

## Screenshot

![rustfmt with `format_code_in_doc_comments` changes the long comments to block comments](https://user-images.githubusercontent.com/28441561/188550268-b16b2b97-e061-4f18-83cf-606e84c0b864.png)

## Related

#3348

**Comment by ytmimi** [comment]
Confirming I can reproduce this with the latest master 38659ec6ad5f341cf8eb3139725bf695872c6de7.

**Comment by ytmimi** [comment]
I did some digging and It seems that `block_style` is being set to `true` in [`write_list`](https://github.com/rust-lang/rustfmt/blob/38659ec6ad5f341cf8eb3139725bf695872c6de7/src/lists.rs#L260)

https://github.com/rust-lang/rustfmt/blob/38659ec6ad5f341cf8eb3139725bf695872c6de7/src/lists.rs#L447-L461

so when we call `CommentRewrite::new` from [`rewrite_comment_inner`](https://github.com/rust-lang/rustfmt/blob/38659ec6ad5f341cf8eb3139725bf695872c6de7/src/comment.rs#L871), we set things up to write a block comment.

https://github.com/rust-lang/rustfmt/blob/38659ec6ad5f341cf8eb3139725bf695872c6de7/src/comment.rs#L564-L568


For anyone interested in working on this I think there are two avenues to explore in order to address the issue:

1) Investigate how we might update the logic in `write_list` to pass `block_style=false` to `rewrite_comment`. `write_list` is a generic function used throughout the codebase so it might be difficult to make changes there without unintentionally breaking the behavior elsewhere.

2) Take the `is_doc_comment` boolean and the `config.format_code_in_doc_comments()` config value into account to try to move code execution into the `light_rewrite_comment` code path instead of the `rewrite_comment_inner` code path from within [`identify_comment`](https://github.com/rust-lang/rustfmt/blob/38659ec6ad5f341cf8eb3139725bf695872c6de7/src/comment.rs#L269).

https://github.com/rust-lang/rustfmt/blob/38659ec6ad5f341cf8eb3139725bf695872c6de7/src/comment.rs#L368-L382

**Comment by pan93412** [comment]
Maybe I can help this!
