### ISSUE TITLE
imports_granularity = "One" doesn't merge use { } block with other use blocks

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rustfmt#5539]
```Rust
use {
    egui_extras::{Size, TableBuilder},
    egui_sfml::egui::{self, Ui},
};

use crate::{app::App, meta::RegionKey};

use super::window_open::WindowOpen;
```

Rustfmt leaves this code alone, instead of merging everything into a single use.

**Comment by crumblingstatue** [comment]
Another example it doesn't merge:

```Rust
use crate::{meta::region::Region, meta_state::MetaState};

use super::regions_window::RegionsWindow;
```

**Comment by ytmimi** [comment]
It's the space between each group that's causing the issue. Removing the spaces will allow rustfmt to merge the imports into a single use:

run `rustfmt --config=imports_granularity=One` on the following:

**Input**
```rust
use {
    egui_extras::{Size, TableBuilder},
    egui_sfml::egui::{self, Ui},
};
use crate::{app::App, meta::RegionKey};
use super::window_open::WindowOpen;
```

**output**
```rust
use {
    super::window_open::WindowOpen,
    crate::{app::App, meta::RegionKey},
    egui_extras::{Size, TableBuilder},
    egui_sfml::egui::{self, Ui},
};
```

**Comment by ytmimi** [comment]
To be honest I don't know why we don't merge use statements separated by newlines. That's a behavior that pre-dates my time with the project, however I suppose it's possible. [`import_granularity`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_granularity) is an unstable option, so I also suspect we could introduce the change to ignore newlines when `import_granularity=One` is set and we're grouping consecutive use statements.

**Comment by ytmimi** [comment]
For anyone intersted in working on this you'll want to take a look at `walk_reorderable_or_regroupable_items` specifically the `in_same_group` bool defined inside the call to `take_while`. That's what's preventing newline separated values from being considered part of the same group.

https://github.com/rust-lang/rustfmt/blob/38659ec6ad5f341cf8eb3139725bf695872c6de7/src/reorder.rs#L260-L278

Should be enough to check if the `item_kind` passed to `walk_reorderable_or_regroupable_items` is a `ReorderableItemKind::Use` and  the user has set `ImportGranularity::One`

However I have no idea what the behavior is if there are comments separating the groups, and that's something we should add a test for.

```rust
use {
    egui_extras::{Size, TableBuilder},
    egui_sfml::egui::{self, Ui},
};
// Some inline comment
use crate::{app::App, meta::RegionKey};
```

**Comment by calebcartwright** [comment]
Thank you both but I am going to close as this is the expected behavior though perhaps a minor tweak to the documentation for `imports_granularity` would be useful.

The fundamental difference is that `imports_granularity` is all about the granularity of imports within each given user-defined import group and does not apply any modification/merging of those user defined groups. [`group_imports`](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#group_imports) is the option for restructuring, or combining, groups into a single one and works along side various other import-related options, including `imports_granularity`

Try running with `--config group_imports=One,imports_granularity=One` which I suspect is the behavior you are looking for.
