### ISSUE TITLE
Whitespace removal in macro causes error

### ISSUE THREAD

**Issue by SeeSpring** [rust-lang/rustfmt#5561]
Rustfmt removes the space between the ending angle brackets which breaks the macro.
```rust
macro_rules! test {
    (Vec$(<$ty1:ident$(<$ty2:ty>)?>)?) => {};
    ($ty0:ident$(<$ty1:ident$(<$ty2:ty>)?>)?) => {};
}
fn main() {
    test!(Vec<Wrapper<f32> >);
}
```
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=macro_rules!%20test%20%7B%0A%20%20%20%20(Vec%24(%3C%24ty1%3Aident%24(%3C%24ty2%3Aty%3E)%3F%3E)%3F)%20%3D%3E%20%7B%7D%3B%0A%20%20%20%20(%24ty0%3Aident%24(%3C%24ty1%3Aident%24(%3C%24ty2%3Aty%3E)%3F%3E)%3F)%20%3D%3E%20%7B%7D%3B%0A%7D%0Afn%20main()%20%7B%0A%20%20%20%20test!(Vec%3CWrapper%3Cf32%3E%20%3E)%3B%0A%7D%0A)

(also if anyone has a better way to match the first two parts of a type let me know)

**Comment by ytmimi** [comment]
Thanks for the report.

There are two issues here that I don't think we can solve:

* The rustc parser doesn't treat whitespace tokens as significant when parsing tokens into AST nodes so we wouldn't have that information available to us when formatting such nodes in macro contexts.
* rustfmt is trying to remove unecessary whitespace when formatting that specific AST node, and we don't want to change that.

To give a little more detail, when we parse the macro arguments using `parse_macro_args` we internally use the rustc parser, which parses `Vec<Wrapper<f32> >` into a [rustc_ast::ast::Ty](https://doc.rust-lang.org/beta/nightly-rustc/rustc_ast/ast/struct.Ty.html#). 

https://github.com/rust-lang/rustfmt/blob/ef91154250977b3b5d05448dafbca524a1168b47/src/macros.rs#L235-L249

The relevant rewrite code can be found in the [`Rewrite impl for ast::Ty`](https://github.com/rust-lang/rustfmt/blob/ef91154250977b3b5d05448dafbca524a1168b47/src/types.rs#L662)


as a workaround you can write your macro calls using `{}` instead of `()` and rustfmt won't try to format those macros e.g `test!{Vec<Wrapper<f32> >};`
