### ISSUE TITLE
Extra spaces not removed in let-else statements

### ISSUE THREAD

**Issue by adamchalmers** [rust-lang/rustfmt#5585]
I think this is a bug. Consider this program [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5b95e532159689601601faf26d40db3b)

```rust
fn main() {
    let x: Option<i32> = None;
    let Some(y) = x       else {
        return;
    };
    println!("{y}");
}
```

I think the extra spaces on line 3, between `x` and `else`, should be removed by rustfmt. But on current stable they aren't.

**Comment by ytmimi** [comment]
Thanks for reaching out. rustfmt doesn't handle `let-else` formatting because the rules for how it should be formatted are still being discussed in https://github.com/rust-dev-tools/fmt-rfcs/pull/165

You might also want to follow  #4914 to keep track of the implementation on the rustfmt side once the rules have been codified in the `fmt-rfc` linked above.
