### ISSUE TITLE
Format `let_else`/let else

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rustfmt#5587]
It seems like rustfmt doesn't support formatting `let_else`/"let else" constructs right now.

```rust
fn main() {
    let Some(okay) = Some(1) else {
                            let t =             1;
                    return;
    };
}
```

I also couldn't find an existing issue around `let_else` (searched for "let else" and "let_else"), so let me know if this is an existing issue that I wasn't able to find.

**Comment by ytmimi** [comment]
Thanks for reaching out. rustfmt doesn't handle `let-else` formatting because the rules for how it should be formatted are still being discussed in https://github.com/rust-dev-tools/fmt-rfcs/pull/165

You might also want to follow  #4914 to keep track of the implementation on the rustfmt side once the rules have been codified in the `fmt-rfc` linked above.

**Comment by cynecx** [comment]
@ytmimi Oh dang! I was searching for "let else" and "let_else" and not "let-ese". Do you mind adding "let_else" (and "let else") to the title of that issue so other lost minds have it easier finding that issue? :)

**Comment by ytmimi** [comment]
No worries, it can definitely be challenging to sift through the backlog. I struggle to track down issues I know are there all the time 😅

I'm surprised "let else" didn't work. This is what I got when I search for "let else" (2nd result)

<img width="1043" alt="Screen Shot 2022-11-04 at 12 57 18 PM" src="https://user-images.githubusercontent.com/29028348/200032849-b806d4b1-00b7-446d-b0d1-cc0d4e5f08bd.png">
