### ISSUE TITLE
error[internal]: left behind trailing whitespace

### ISSUE THREAD

**Issue by LittleGuest** [rust-lang/rustfmt#5599]
Hi, I'm having a problem with cargo fmt , like this：

```
error[internal]: left behind trailing whitespace
 --> /playground/src/main.rs:5:5:1
  |
5 |         
  | ^^^^^^^^
  |

warning: rustfmt has failed to format. See previous 1 errors.
```

code looks like this:

```rust
fn main() {
    let a = Some(1);
    let Some(a) = a else{
        panic!("none");
        
    };
    println!("{a}");
}
```

rustc 1.65.0
rustfmt 1.5.1-stable (897e3755 2022-11-02)

**Comment by ytmimi** [comment]
Thanks for reaching out. rustfmt doesn't handle `let-else` formatting because the rules for how it should be formatted are still being discussed in https://github.com/rust-dev-tools/fmt-rfcs/pull/165

Because rustfmt doesn't format `let-else` statements the code is left as is by rustfmt, which means the trailing whitespace that exists in the original snippet is also left alone, triggering the internal error that you're seeing. In this case the internal error is rustfmts way of letting you know that there's trailing whitespace in the text of your program that requires manual intervention to remove.

You might also want to follow  #4914 to keep track of the implementation on the rustfmt side once the rules have been codified in the `fmt-rfc` linked above.
