### ISSUE TITLE
Stack overflow when trying to format big files

### ISSUE THREAD

**Issue by StHagel** [rust-lang/rustfmt#5608]
Hey all,
I found out, that you can get a stack overflow error when trying to format very big source files with `rustfmt` on Linux.
It happened to me with a file, that is over 50,000 lines long, around 2 MB in size and the vast majority of lines in this file contain one arithmetic instruction. If needed, I can provide you with an example file, that can reproduce this issue.

A workaround to this is to manually increase the stacksize by doing `ulimit -s 8096` or even `ulimit -s unlimited`.

**Comment by calebcartwright** [comment]
Thanks but I'm going to close. This is a known possibility with more pathological types of inputs, with viable workarounds available and utilized in these more niche cases.

There are some potentially invasive changes we can make it less likely to occur even in these more niche cases, but it's not something that can ever be fully prevented with significantly large inputs so it's not a high priority for us. Closing because this is something being mulled elsewhere and we don't need the issue to track it.

**Comment by ytmimi** [comment]
Got it! is there a discussion you can link to?
