### ISSUE TITLE
Long trait name in `where` clause breaks formatter

### ISSUE THREAD

**Issue by maltekliemann** [rust-lang/rustfmt#5620]
(Try it on the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=68526ce2c0de66e12337536bcd51a9b6).)

A very long trait in a where clause causes rustfmt to ignore the entire `impl` block:

```rust
impl<T> Trait for Struct<T>
where
    T:
        VeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLong
{
    fn some_func()
    {
        // This is not cool but won't be reformatted.
        let something = 1; let other = 2;
    }
}

fn main() {
    // This is not cool but will be reformatted.
    let something = 3; let other = 4;
}
```

This is not just the case if the trait name is very long; it also happens when long `<...<A as B>::C as D>::E...>::Z` constructions are used. The rest of the file is still formatted correctly.

**Comment by ytmimi** [comment]
Thanks for reaching out.

rustfmt is constrained by the `max_width` configuration, which defaults to `100`.  The only real solution here is to bump the `max_width` to some sufficiently high number.

The reason why the `impl` block is left unformatted if we fail to format the `where clause` is because rustfmt operates on the AST of your program, and when it fails to format any part of a given AST node it will refuse to format the entire AST node. In this case the AST node is an [`ast::Impl`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_ast/ast/struct.Impl.html).

Taking a look at the implementation in [`format_impl`](https://github.com/rust-lang/rustfmt/blob/ee2bed96d60fd7e46b1fb868f6a8f27e3a8058d0/src/items.rs#L656), we can see that we return early if we fail to format the `where clause` (**note the `?` operator**):

https://github.com/rust-lang/rustfmt/blob/ee2bed96d60fd7e46b1fb868f6a8f27e3a8058d0/src/items.rs#L694-L705

Similar behavior can be seen when we fail to format the conditional expression in an `if block` (#5583)

**Comment by maltekliemann** [comment]
Thanks for explaining, @ytmimi! Just one question though: Why do you use the `?` operator in this situation? If `rewrite_where_clause` raises an error because it failed to format the `where` clause (due to excessive length, for example), then why don't you just ignore that error and at least format the rest of the `impl` block? Feels like this should be doable if the errors are sufficiently granular.

**Comment by ytmimi** [comment]
> Why do you use the ? operator in this situation?

I can't say for sure since the functionality was implemented long before I joined the project. Some speculation on my part, but maybe it was just easier to implement that way, and possibly it was thought very unlikely that errors would occur. I imagine that long unbroken identifier names that exceed the max width are pretty uncommon.


> If rewrite_where_clause raises an error because it failed to format the where clause (due to excessive length, for example), then why don't you just ignore that error and at least format the rest of the impl block? Feels like this should be doable if the errors are sufficiently granular.

currently all rewrite functions return `Option<String>` instead of `Result<String, Error>`, so we wouldn't know for sure why we failed to format the ast node, and we wouldn't be able to tell how granular the error is. That being said, I also think this is technically possible and we might make this enhancement in the future.
