### ISSUE TITLE
Error on formatting array of tuples with a struct with eighty or more char string and trailing whitespace on any of the other members?

### ISSUE THREAD

**Issue by swarnimarun** [rust-lang/rustfmt#5633]
Yes, the title is,

> Error on formatting array of tuples with a struct with eighty or more char string and trailing whitespace on any of the other members?

### Minimal Example

I got this error boiled down to. (it was an annoyingly fun process lol)

```rust
struct F {
    foo: &'static str,
    bar: u8,
}

fn main() {
    [
        (0, F {
            foo: "foo",
            bar: 0,
        }),
        (0, F {
            foo: "eightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeighty..",
            bar: 0, 
        }),
    ];
}
```

Note: the trailing whitespace after `bar: 0,`

<img width="2235" alt="Screenshot 2022-12-20 at 3 51 07 PM" src="https://user-images.githubusercontent.com/19930870/208645914-20b28efd-6257-4434-a17e-5ab3d56f9b75.png">

[Link to the playground.](https://play.rust-lang.org/)

Not familiar with rustfmt source, if anyone has any ideas suggestions are welcome. I will fix it once I have free time to look at the source.

**Comment by ytmimi** [comment]
Thanks for reaching out!

The good news is there's a fix, but you will need to use the `version = "Two"` config which requires a nightly rustfmt.

You can run `rustfmt --config=version=Two` on the original input to confirm that.

### Version::Two formatting
```rust
struct F {
    foo: &'static str,
    bar: u8,
}

fn main() {
    [
        (0, F { foo: "foo", bar: 0 }),
        (
            0,
            F {
                foo: "eightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeighty..",
                bar: 0,
            },
        ),
    ];
}
```

However, you'll get an error message alerting you to the long string literal if you have `error_on_unformatted=true` set.
```
error[internal]: line formatted, but exceeded maximum width (maximum: 100 (see `max_width` option), found: 104)
  --> <stdin>:12:12:101
   |
12 |                 foo: "eightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeighty..",
   |                                                                                                     ^^^^
   |
   = note: set `error_on_unformatted = false` to suppress the warning against comments or string literals

warning: rustfmt has failed to format. See previous 1 errors.

```

We've recently done some work to try to catalog `v1` vs `v2` differences, and the reason the `v2` code gets formatted can be found when looking into changes made by PR #3556 and the current implementation of `rewrite_string_lit`

https://github.com/rust-lang/rustfmt/blob/ee2bed96d60fd7e46b1fb868f6a8f27e3a8058d0/src/expr.rs#L1201-L1215

More specifically we fail in the `v1` case because we end up calling `wrap_str`, which in this case will return `None` signaling to rustfmt that we failed to format the string literal, and that `None` then bubbles its way up the call stack to prevent formatting the top level [`ast::ExprKind::Array`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_ast/ast/enum.ExprKind.html#variant.Array) node.

**Comment by ytmimi** [comment]
I should also note that if you can't use `version = "Two"` then your best bet to resolve this is to bump the `max_width` to a sufficiently large value. By default it's 100, and for the example that you posted setting the `max_width=105` resolves the issue.

#### `max_width=105`
```rust
struct F {
    foo: &'static str,
    bar: u8,
}

fn main() {
    [
        (0, F { foo: "foo", bar: 0 }),
        (
            0,
            F {
                foo: "eightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeightyeighty..",
                bar: 0,
            },
        ),
    ];
}
```
