### ISSUE TITLE
format_strings does not format long strings with no spaces or punctuation

### ISSUE THREAD

**Issue by road2react** [rust-lang/rustfmt#5640]
When `format_strings = true` and the code provided is

```rs
fn a() {
    let     a = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"                ;
}
```

No formatting is done to the line containing the long string.

**Comment by ytmimi** [comment]
Unfortunately `format_strings=true` can't help here because it's unclear where to insert the break. We don't insert breaks into the middle of words, and there isn't any punctuation or whitespace in the string you listed above.

If you took your example and added whitespace to it
```rust
fn a() {
    let     a = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"                ;
}
```

And then ran rustfmt with `format_strings=true` you'd get:

```rust
fn a() {
    let a = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa \
             aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
}
```

Given that you're already using a nightly rustfmt (since you're using `format_strings=true`) you can  set `version=Two` and this is the formatting you'll get:

```rust
fn a() {
    let a = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
}
``` 

Your other option is to bump the `max_width` to some sufficiently large value.
