### ISSUE TITLE
`feature(non_lifetime_binder)` syntax gets removed

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rustfmt#5721]
the following code:
```rust
#![feature(non_lifetime_binders)]
#![allow(incomplete_features)]

trait Other<U: ?Sized> {}

trait Trait<U> 
where
    for<T> U: Other<T> {}
```
when formatted is:
```rust
#![feature(non_lifetime_binders)]
#![allow(incomplete_features)]

trait Other<U: ?Sized> {}

trait Trait<U>
where
    U: Other<T>,
{
}
```

**Comment by ytmimi** [comment]
Here's the tracking issue for `#![feature(non_lifetime_binders)]` https://github.com/rust-lang/rust/issues/108185,

@calebcartwright I'm not sure if `t-style` needs to be looped in for the experimental syntax or if we can handle a fix for this on our own. Given that our `rust-toolchain` is currently at `nightly-2023-01-24` and this feature landed a month ago, we'd probably need a subtree sync before we could resolve this.

**Comment by calebcartwright** [comment]
We actually coincidentally discussed this at the t-style meeting earlier today, but fortunately this is just a case where rustfmt was operating under the assumption that it would never see a type binder in this particular position vs. there not being formatting rules for how to handle the syntax.

I.e., I don't think there's anything net new at the AST level that we need to derive something for, we probably just have a logic assumption somewhere that needs to be tweaked.

> Given that our rust-toolchain is currently at nightly-2023-01-24 and this feature landed a month ago, we'd probably need a subtree sync before we could resolve this.

If this is particularly problematic for rustc then, assuming a fix is as trivial as I suspect, then I wouldn't mind in this instance letting the fix be applied directly in-tree in r-l/rust, but otherwise yes, to fix here we'd need to do a sync and I think I'm still a few PR reviews out from that (so probably at least 2 weeks)
