### ISSUE TITLE
Request: Drop trailing comma delimiters when inlining single-element collections

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rustfmt#5737]
rustfmt insists on inlining short, single-element collections into one line of text, yet it needlessly preserves any trailing comma (`,`) container element delimiters. As long as rustfmt is going to the bother of inlining single-element collections, it should also remove any trailing comma for the collection.

**Comment by calebcartwright** [comment]
Please provide a code snippet that can be used as input to rustfmt to reproduce the behavior you are describing

**Comment by mcandre** [comment]
And ensure that trailing commas are put back when the collection contains two or more elements.

**Comment by ytmimi** [comment]
@mcandre as mentioned above we need you to provide a code snippet that we can use to verify the issue that you're describing. Without one there's nothing we can do to help, and we'll have to close this issue.

**Comment by calebcartwright** [comment]
I'm going to go ahead and close actually due to the absence of relevant info.

Can certainly reopen if there's a need to do so if/when that info is shared, but without knowing the context we can't shed any light on whether this is correct/expected behavior (as specified by the Style Guide and/or in a macro context), non-default behavior stemming from a configuration option (e.g. https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#trailing_comma), a bug, nor we can articulate a posture on whether a request for net-new behavior would be considered
