### ISSUE TITLE
`format_code_in_doc_comments` does not format `compile_fail` and `ignore` code blocks

### ISSUE THREAD

**Issue by wackbyte** [rust-lang/rustfmt#5747]
With `rustfmt 1.5.2-nightly (88fb1b92 2023-04-10)`:

### Input code
```rs
//! Rust:
//! ```
//! let a: i128
//!     = 100;
//! ```
//! 
//! Compile fail, still rust:
//! ```compile_fail
//! let a: &str
//!     = 100;
//! ```
//! 
//! Ignore, still rust:
//! ```ignore
//! let a: i128
//!     = 100;
//! ```
//! 
//! Text:
//! ```text
//! let a: i128
//!     = 100;
//! ```
```

### Actual result
```rs
//! Rust:
//! ```
//! let a: i128 = 100;
//! ```
//!
//! Compile fail, still rust:
//! ```compile_fail
//! let a: &str
//!     = 100;
//! ```
//!
//! Ignore, still rust:
//! ```ignore
//! let a: i128
//!     = 100;
//! ```
//!
//! Text:
//! ```text
//! let a: i128
//!     = 100;
//! ```
```

### Expected result
The `compile_fail` and `ignore` code blocks should be formatted as well. Rustdoc still highlights them as Rust, so they should be treated as such.

**Comment by wackbyte** [comment]
In addition, under the [current implementation](https://github.com/rust-lang/rustfmt/blob/a3b2bfc2db33ec3bed266404e6391c145e000df0/src/comment.rs#L426), specifying [error numbers for `compile_fail`](https://doc.rust-lang.org/rustdoc/print.html#error-numbers-for-compile-fail-doctests) may cause code to not be formatted.

**Comment by ytmimi** [comment]
Thanks for reaching out.

> In addition, under the [current implementation](https://github.com/rust-lang/rustfmt/blob/a3b2bfc2db33ec3bed266404e6391c145e000df0/src/comment.rs#L426),

You've identified the right place in the code that explains why we're not formatting `ignore`  or `compile_fail` block. That being said, I imagine there's a reason that we're skipping those blocks, however I can't say I know why.

@calebcartwright what are your thoughts? Is the current behavior what we want to stick with?

**Comment by calebcartwright** [comment]
I'm going to close. I recognize that you might want something different in your specific context, but this is indeed intentional from our side and not something we're going to change.

I view `ignore` as being sufficiently self-evident, and the reasoning behind `compile_fail` is fairly straightforward as well. Blocks attributed as such are intended for Rust-wide "skip" in the former, and the latter is explicitly indicating an expected compilation issue. rustfmt _is_ still able to perform its function in a broader set of invalid code than most other tools, but there's plenty of non-compilable that's problematic for rustfmt too. When folks are writing a doctest they explicitly expect to fail to compile, there's a decent chance the contents of that test are also incompatible with other tools, and that's why these are ignored by rustfmt too.

I might be receptive to opening up a user facing option to allow for control over which types should/shouldn't be formatted (provided the current ones remain the default), but that would be an extremely low priority potential enhancement. As such it isn't something we'll likely ever get around to working on ourselves, nor could we even allocate any time review/design discussion any time soon.
