### ISSUE TITLE
Inconsistent empty lines in function arguments with fn_args_layout = "Tall"

### ISSUE THREAD

**Issue by orhantugrul** [rust-lang/rustfmt#5763]
When using the `fn_args_layout` configuration set to `Tall`, there seems to be an inconsistency in the number of empty lines added between the function arguments.

For example, consider the following code snippet:

```rust
fn print_sum_of<
    T: Add<Output = T> + Display + Copy + From<U>,
    U: Add<Output = U> + Display + Copy,
>(
    left: T,
    right: U,
) {
    let result = left + T::from(right);
    println!("{} + {} = {}", left, right, result);
}
```

Here, there is an extra empty line before the `left` parameter, and another empty line after the `right` parameter. This does not seem consistent with the `Tall` configuration.

I expected like:

```rust
fn print_sum_of<
    T: Add<Output = T> + Display + Copy + From<U>,
    U: Add<Output = U> + Display + Copy,
>(left: T, right: U) {
    let result = left + T::from(right);
    println!("{} + {} = {}", left, right, result);
}
```

Could we consider adjusting the rustfmt code to ensure consistent empty lines between function arguments with the `fn_args_layout` configuration set to `Tall`?

Thank you! 🦀

**Comment by ytmimi** [comment]
Thanks for reaching out!

I'm not sure what version of rustfmt you're using, but `fn_args_layout` has been renamed to `fn_params_layout` to better reflect that it controls the layout of parameters in function signatures. You can still use `fn_args_layout` for now, but just wanted to mention that it's been deprecated.

`Tall` will format everything on a single line when possible and if vertical formating is required, everything will be formatted vertically, so the current behavior is correct and I don't think we'll change that.

In order to mix both vertical and horizontal layouts you probably want to use the `Compressed` variant. Using `Compressed` on your input produces:

```rust
fn print_sum_of<
    T: Add<Output = T> + Display + Copy + From<U>,
    U: Add<Output = U> + Display + Copy,
>(
    left: T, right: U,
) {
    let result = left + T::from(right);
    println!("{} + {} = {}", left, right, result);
}
```

**Comment by ytmimi** [comment]
We may consider adding another variant for `fn_params_layout` in the future, but it's unlikely that the rustfmt team would work on this directly.
