### ISSUE TITLE
rustfmt fails to format (due to quote?)

### ISSUE THREAD

**Issue by deepink-mas** [rust-lang/rustfmt#5840]
I was doing the [proc macro workshop](https://github.com/dtolnay/proc-macro-workshop#derive-macro-derivebuilder) and wrote some code that rustfmt (1.5.2, which comes with rust 1.70.0) does not want to format (see long line at end):

```rust
use proc_macro::TokenStream;
use proc_macro2::{Ident, Span};
use quote::quote;
use syn::Data::Struct;
use syn::Fields::Named;

#[proc_macro_derive(Builder)]
pub fn derive(input: TokenStream) -> TokenStream {
    let input = syn::parse_macro_input!(input as syn::DeriveInput);
    let name = input.ident;
    let builder = Ident::new(&format!("{name}Builder"), Span::call_site());
    let fields = match &input.data {
        Struct(d) => match &d.fields {
            Named(f) => &f.named,
            _ => unimplemented!(),
        },
        _ => unimplemented!(),
    };
    let (field_id, field_ty): (Vec<_>, Vec<_>) = fields
        .iter()
        .map(|f| (f.ident.as_ref().unwrap(), &f.ty))
        .unzip();
    let field_string = field_id.iter().map(|id| id.to_string());

    let expanded = quote! {
        pub struct #builder {
            #( #field_id: Option<#field_ty> ),*
        }

        impl #name {
            fn builder() -> #builder {
                #builder {
                    #( #field_id: None ),*
                }
            }
        }

        impl #builder {
            #(fn #field_id(&mut self, #field_id: #field_ty) -> &mut Self {
                self.#field_id = Some(#field_id);
                self
            })*

            fn build(&mut self) -> Result<#name, Box<dyn ::std::error::Error>> {
                Ok(#name {
                    #(#field_id: self.#field_id.take().ok_or_else(|| format!("field `{}` not yet initialized", #field_string))? ),*
                })
            }
        }
    };

    expanded.into()
}
```

**Comment by ytmimi** [comment]
@deepink-mas thanks for reaching out.  It's a little unclear what's not getting formatted. Are you expecting the `quote!{ ... }` call to be formatted?

**Comment by calebcartwright** [comment]
Thanks for reaching out, but I'm going to close this.

As Yacin noted above it's very intentional that rustfmt doesn't touch macros that use brace delim. Even if you were to switch to another delim rustfmt would be unable to format the arg contents because they cannot be fully parsed as valid rust code, a [key condition in order to be able to format](https://doc.rust-lang.org/nightly/style-guide/expressions.html#macro-uses).

If someone can propose a fully deterministic approach for handling `quote!` then I'd certainly be willing to consider pulling in support, so would encourage subscribing to #3406
