### ISSUE TITLE
rustfmt silently gives up on formatting expressions after `if let` if some literal is too long

### ISSUE THREAD

**Issue by bernardosulzbach** [rust-lang/rustfmt#5858]
I have minified my real code as much as I could and isolated the cause as a string literal within an `if let` expression that, when combined with the indentation of the block, goes beyond the maximum width.

```rust
fn f_ok_because_the_literal_is_short() {
    if let Ok(_) = try_something(a.map(|a_i| match a_i.try_more() {
            Some(d) => d,
        None => g("Hi!"),
    })) {
        commit();
    }
}
```

gets formatted and the `Some(d)` arm gets unindented, as I expect. However,

```rust
fn f_not_ok_because_the_literal_is_long() {
    if let Ok(_) = try_something(a.map(|a_i| match a_i.try_more() {
            Some(d) => d,
        None => {
            g("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
        }
    })) {
        commit();
    }
}
```

does not get any changes.

I find this quite bad, as a single offending line ends up causing surrounding code—even code preceding it—to not get formatted.

Ideally, this would be fixed. However, temporarily, it would be great if I could somehow tell `rustfmt` to fail hard (returning non-zero) when this happens. I would rather know that code hasn't been formatted than find it changing without explanation later down the line when someone shortens a `panic!` string several lines below it.

**Comment by bernardosulzbach** [comment]
I see that `rustfmt` nightly has

- [`error_on_line_overflow`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#error_on_line_overflow) and
- [`error_on_unformatted`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#error_on_unformatted)

that I think will do what I wanted as a temporary workaround.

However, `error_on_unformatted` is not triggered in the abovementioned case. Is there some other option that would be triggered when the expression is not formatted?

**Comment by ytmimi** [comment]
@bernardosulzbach thanks for reaching out. I think the issue here is that the call to `a.map`, which leads me to believe this is a duplicate of #3863.

You may need to set both `error_on_ine_overflow` and `error_on_unformatted`. running rustfmt on your input with the following `rustfmt.toml`

```toml
error_on_line_overflow = true
error_on_unformatted = true
version = "Two"
```

I get this output:

```
error[internal]: line formatted, but exceeded maximum width (maximum: 100 (see `max_width` option), found: 140)
 --> <stdin>:5:5:101
  |
5 |             g("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
  |                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: set `error_on_unformatted = false` to suppress the warning against comments or string literals

warning: rustfmt has failed to format. See previous 1 errors.
```

Hope that helps. I'm going to close this as a duplicate.

**Comment by bernardosulzbach** [comment]
@ytmimi thanks for replying. It still fails after removing the chain. I included the modified version below.

```rust
fn f_not_ok_because_g_is_long() {
    if let Ok(_) = match a.try_more() {
            Some(d) => d,
        None => {
            g("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
        }
    } {
        commit();
    }
}
```

However, it now does unindent the `Some` arm if, and only if, I use the `version = "Two"` option.

I think this might be what was described in [this comment](https://github.com/rust-lang/rustfmt/issues/3863#issuecomment-1487787896), which, at least according to [this other comment](https://github.com/rust-lang/rustfmt/issues/3863#issuecomment-1487818713), is a separate issue from #3863. However, as pointed out in [this older comment](https://github.com/rust-lang/rustfmt/issues/3863#issuecomment-986343312), it seems like it will never be fixed.

**Comment by calebcartwright** [comment]
The original report was indeed a duplicate of #3863, and information was shared about the available options that support making this a hard failure so I concur with the closure of this issue.

Similarly, the guidance from #3863 is applicable here in that the underlying problem is the long string lit which you'd either need to manually format across multiple lines, or give rustfmt permission to do so (by setting  `format_strings` to `true` - https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#format_strings).

rustfmt is a pretty-printer style formatter which means it works with the AST that rustc produces; rustfmt doesn't directly work with your input files. This means that when there's a case like this where it's impossible to derive the formatting for one AST node, it can conceptually "cascade up" to an ancestor/parent AST node because it's not uncommon for formatters to need know how all the child nodes will be formatted in order to properly apply the rules for the ancestor/parent.

> I think this might be what was described in https://github.com/rust-lang/rustfmt/issues/3863#issuecomment-1487787896, which, at least according to https://github.com/rust-lang/rustfmt/issues/3863#issuecomment-1487818713, is a separate issue from https://github.com/rust-lang/rustfmt/issues/3863. However, as pointed out in https://github.com/rust-lang/rustfmt/issues/3863#issuecomment-986343312, it seems like it will never be fixed.

Correct, different root cause issue, very similar symptoms. However, I'm not sure what makes you think it will "never be fixed", as I think that's belied by the fact that it already is fixed and just gated.

It's currently gated because Rustfmt has formatting stability guarantees that limit the ability to intentionally change or apply new formatting behavior such that it modifies the output from prior versions of Rustfmt.

When you set `version=Two`, the equivalent of `style_edition=2024` you're opting in to the next formatting mode/version of Rustfmt where such changes can be applied, as the edition-based mechanism is how formatting will evolve over time.

**Comment by bernardosulzbach** [comment]
@calebcartwright I think what was left then was a misunderstanding on my part of how strong the stability guarantees of rustfmt were.

Just to be absolutely clear, I'm now only talking about the [match-only report](https://github.com/rust-lang/rustfmt/issues/5858#issuecomment-1646967263), as I trust you that the original one is just https://github.com/rust-lang/rustfmt/issues/3863.

> I'm not sure what makes you think it will "never be fixed", as I think that's belied by the fact that it already is fixed and just gated.

You agree that version Two (or edition 2024) _fixes_ it, but will still deliberately not make this the output without version Two? Is code that a given rustfmt edition left unformatted supposed to be left unformatted in that edition forever?

**Comment by calebcartwright** [comment]
> @calebcartwright I think what was left then was a misunderstanding on my part of how strong the stability guarantees of rustfmt were.

I think this is accurate

> You agree that version Two (or edition 2024) fixes it

Not to get too pedantic, but actually I don't. I should've used different wording instead of reusing your phrasing. It is very much intentional that when rustfmt cannot format code according to _all_ rules that it simply re-emits whatever was there in the first place and defers to the programmer to fix it.

Again, that's intentional, and that's the expected behavior regardless of whether it's what certain users would _prefer_. 

The unstable `version=Two` option (which will become `style_edition=2024` in the near future) and the associated formatting behavior are themselves unstable and still subject to change. Some aspects of that unstable formatting include different behavior wherein rustfmt may semi-ignore the max_width rule for impossibly long string lits or comments and continue formatting anyway.

This is not a "fix", but is instead a different potential decision for formatting moving forward. 

> Is code that a given rustfmt edition left unformatted supposed to be left unformatted in that edition forever?

Again nuance matters. The Rust ecosystem takes stability very seriously, and that holds true with Rustfmt as well. In cases where Rustfmt has made a deliberate decision about formatting behavior, future versions of Rustfmt cannot **change** that decision outside a Style Edition boundary, and that includes cases where Rustfmt explicitly decided to defer formatting to the programmer, which is precisely what's happened here.
