### ISSUE TITLE
Error when formatting `if let` with `&&`

### ISSUE THREAD

**Issue by momvart** [rust-lang/rustfmt#5863]
If we chain multiple `if let` blocks into a single one with `&&`, `rustfmt` fails to format or gives
```
error[internal]: left behind trailing whitespace
```

Example:
```rust
fn main() {
    let x = Some(10);
    let y = None;

    if let Some(x) = x 
&& let Some(y) = y {
        println!("Hi");
    }
}
```

Version: `1.6.0-nightly (2023-07-27 500647f)`

**Comment by xxchan** [comment]
This is because unstable feature `let-chains` is not formatted (WIP in https://github.com/rust-lang/rustfmt/pull/5203).

You need to manually format it, and remove the trailing spaces 
<img width="246" alt="image" src="https://github.com/rust-lang/rustfmt/assets/37948597/d501273c-ffc6-4cdf-abc0-98a02f132894">

**Comment by momvart** [comment]
I thought it should be a WIP but couldn't remember the feature name :).

**Comment by momvart** [comment]
Duplicate of #5177
