### ISSUE TITLE
Strange linebreaks introduced in if-let expressions with let_chains

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustfmt#5946]
I haven't found a self-contained example of this yet, but [this commit](https://github.com/rust-lang/miri/pull/3136/commits/0d6360de959d5f7b8cb56fc86cff165d223ac3e8) demonstrates the problem: rustfmt changes
```rust
                if let Ok(name) = str::from_utf8(name) && is_dyn_sym(name) {
                    let ptr = this.fn_ptr(FnVal::Other(DynSym::from_str(name)));
                    this.write_pointer(ptr, dest)?;
                } else {
                    this.write_null(dest)?;
                }
```
to
```rust
                if let Ok(name) = str::from_utf8(name)
                    && is_dyn_sym(name)
                {
                    let ptr = this.fn_ptr(FnVal::Other(DynSym::from_str(name)));
                    this.write_pointer(ptr, dest)?;
                } else {
                    this.write_null(dest)?;
                }
```
Which looks worse due to splitting the `if` over multiple lines, and which looks like a bug since in the original code, this line was actually shorter than the next one, so it is clearly below the threshold for breaking long lines. I've never seen normal `if` behave like that, so it's probably something specific to `if let`, maybe specific to `let_chains` even.

This is a recent regression, until recently rustfmt didn't change our formatting here.

**Comment by ytmimi** [comment]
This isn't a regression. rustfmt wasn't formatting things at all before, and just left the let-chain unformatted. Support for let-chains was added in https://github.com/rust-lang/rustfmt/pull/5910, and those changes were synced with `r-l/rust` a little while ago https://github.com/rust-lang/rust/pull/117066. Formatting was implemented following the rules outlined in https://github.com/rust-lang/rust/pull/110568.

Given that let-chains are still unstable the formatting rules haven't been fully decided, but we wanted to get something implemented in rustfmt sooner rather than later. The formatting is subject to change, and if you have thoughts on the formatting rules I think it would be best to reach out to @rust-lang/style
