### ISSUE TITLE
How to use rustfmt programmatically?

### ISSUE THREAD

**Issue by loynoir** [rust-lang/rustfmt#5955]
https://crates.io/crates/rustfmt

> almost 6 years ago

> This version of rustfmt is deprecated. Use [rustfmt-nightly](https://crates.io/crates/rustfmt-nightly).

https://crates.io/crates/rustfmt-nightly

>  about 3 years ago

> rustfmt-nightly = "1.4.21"

But source code now `1.7.0`.

https://github.com/rust-lang/rustfmt/blob/37489e43b6e692f48f5c2b7218e5177382af9a25/Cargo.toml#L4

Related

https://github.com/rust-lang/rustfmt/issues/1534

Question

- What happened to these two crates?

- Or, is CI somehow silent fail to publish crates?

- Or, is `rustfmt-nightly` deprecated without update crates deprecation?

- And how to use rustfmt nowadays?

**Comment by ytmimi** [comment]
To the best of my knowledge rustfmt isn't intended to be used as a library. We no longer distribute rustfmt via crates.io, and the only official distribution channel for rustfmt is via rustup. @calebcartwright please let me know if I've missed anything or if you can provide @loynoir with more information on this.

**Comment by calebcartwright** [comment]
> How to use rustfmt programmatically?

In short, don't.

Apologies for any confusion those crates may have caused. Sometime last year we were having discussions about cleaning up some old crates that were published from rust-lang/* repos, but I think that fizzled out (I never originally had access to either of those crates, unsure what the current access status is).

I don't want to overburden with too much detail, but in years past rustfmt used a different model for leveraging the compiler's internals for capabilities like parsing, so that rustfmt could focus on the actual formatting.

That consumption model did allow for us to provide a relatively minimally constrained path for utilizing rustfmt as a library, but it came at some pretty severe costs to the primary rustfmt userbase (e.g. it often caused fatal errors for users running `cargo fmt` or `rustfmt` against files that had relatively old syntax because that consumption model lagged far behind rustc itself).

So we decided some time back to switch rustfmt to follow the same model for consuming the compiler internals that other dev tools (like clippy, miri, etc.) utilize which resolved many of those nasty experience, but also made consuming rustfmt as a library very cumbersome and painful.

It's technically possible to do so via a git dependency on this repo, but we don't support that in any shape or form, breaking changes can happen at any point, and doing so introduces a number of requirements upon consumers/users of any app that's using rustfmt as a library.
