### ISSUE TITLE
Internal error: left behind trailing whitespace

### ISSUE THREAD

**Issue by hmac** [rust-lang/rustfmt#5956]
Running rustfmt on the following code:

```rust
fn a() {
    b.c(|| {
            if let d = e {
            } else if let f = g {
                } else {
                    h!(?iiiiiiii.jjjjjjjjj,
                       kkkkk, llllllllllllllllllllllll, mmmmmmmmmmmmmmmmmmmmmmmmmm, nnnnnnnnnnnnnnnnnnnnnnnn,
                    );
                }
            
        })
}
```

results in this error:

```
error[internal]: left behind trailing whitespace
  --> /private/var/folders/p8/c86yrh3j3k37yc797f405p8r0000gn/T/tmp.YzrSqVZyw1/test.rs:10:10:1
   |
10 |
   | ^^^^^^^^^^^^
   |

warning: rustfmt has failed to format. See previous 1 errors.
```

```
rustfmt 1.6.0-stable (5680fa18 2023-08-23)
```

The snippet is reduced from a real world example - it seems sensitive to line length, hence the long variable names.

**Comment by ytmimi** [comment]
@hmac the snippet you posted contains trailing whitespace. Unfortunately rustfmt is unable to format the macro because `?iiiiiiii.jjjjjjjjj` can't be parsed as valid rust syntax. Failing to format the macro has a cascading effect that ultimately triggers #3863, meaning the closure body for `c(|| { ..})` is never formatted, and rustfmt warns you that there was trailing whitespace in the input snippet that it was unable to remove.

If you remove the `?` from `?iiiiiiii.jjjjjjjjj` then rustfmt is able to parse `iiiiiiii.jjjjjjjjj` and is therefore able to format the code as intended. I tested this with `rustfmt 1.6.0-nightly (1c05d50c 2023-10-21)`.

**Input**

```rust
fn a() {
    b.c(|| {
            if let d = e {
            } else if let f = g {
                } else {
                    h!(iiiiiiii.jjjjjjjjj,
                       kkkkk, llllllllllllllllllllllll, mmmmmmmmmmmmmmmmmmmmmmmmmm, nnnnnnnnnnnnnnnnnnnnnnnn,
                    );
                }
            
        })
}
```

**Input**

```rust
fn a() {
    b.c(|| {
        if let d = e {
        } else if let f = g {
        } else {
            h!(
                iiiiiiii.jjjjjjjjj,
                kkkkk,
                llllllllllllllllllllllll,
                mmmmmmmmmmmmmmmmmmmmmmmmmm,
                nnnnnnnnnnnnnnnnnnnnnnnn,
            );
        }
    })
}
```

Unfortunately there's not much we can about this particular issue. macros are allowed to contain any valid rust tokens, but the only way for rustfmt to format a macro is if rustfmt can parse the arguments as valid rust syntax, which in this case it can't. In these cases you'll need to format those macros by hand to make sure that they stay within the `max_width` bound.

**Comment by hmac** [comment]
@ytmimi interesting, thanks for the explanation! In the real world version of this code, the macro was [info](https://docs.rs/tracing/latest/tracing/macro.info.html) from the tracing crate. It certainly makes sense that rustfmt can't do much with macros that use non-rust syntax.

**Comment by joshburkart** [comment]
Can't `rustfmt` point to the line that is actually preventing formatting? This type of thing happens frequently for me and I have to haphazardly delete chunks of code to figure out what is actually tripping up `rustfmt`.

**Comment by ytmimi** [comment]
@joshburkart there are some challenges around pinpointing the actual line that prevents formatting. In the future I'm hopeful that we'll be able to provide better feedback about formatting failures to end users.
