### ISSUE TITLE
rustfmt will fail if the end of line is a comma and a space

### ISSUE THREAD

**Issue by pfwang80s** [rust-lang/rustfmt#5985]
after deleting that space, rustfmt works.

```
$cargo fmt -v
[custom-build (2021)] "xx.rs"
[lib (2021)] "oo.rs"
rustfmt --edition 2021 xx.rs oo.rs
error[internal]: left behind trailing whitespace
   --> xxoo.rs:659:659:63
    |
659 |                                 code: WRITE_OPERATION_IGNORED,
    |                                                               ^
    |

warning: rustfmt has failed to format. See previous 1 errors.
```

**Comment by ytmimi** [comment]
@pfwang80s Thanks for reaching out.

Without a sample code snippet there's very little the rustfmt team can do to help. I see you're using a custom build of rustfmt. Please provide a rustfmt version where we can reproduce the issue as well as a list of any rustfmt configurations you might be using, thanks.

**Comment by pfwang80s** [comment]
I've tried with the latest stable version, and it reproduced:
```
$rustfmt --version
rustfmt 1.6.0-stable (a28077b2 2023-12-04)

$cargo fmt -v
[custom-build (2021)] "xx.rs"
[lib (2021)] "xx.rs"
rustfmt --edition 2021 xx.rs xx.rs
error[internal]: left behind trailing whitespace
   --> xx.rs:659:659:63
    |
659 |                                 code: WRITE_OPERATION_IGNORED,
    |                                                               ^
    |

warning: rustfmt has failed to format. See previous 1 errors.
```

**Comment by pfwang80s** [comment]
I can't reproduce the issue with a simple code snippet, what should I do to provide more info? hope this helps:
<img width="1070" alt="image" src="https://github.com/rust-lang/rustfmt/assets/21698832/b9bcab97-717b-4442-aa45-2913e15005e6">

**Comment by ytmimi** [comment]
@pfwang80s I appreciate you sharing the image. The issue is that there's a trailing space in your source code that rustfmt is unable to remove. It looks like you're in a deeply nested context and the `message` field is likely longer than the `max_width`, therfore rustfmt is unable to reformat the code.

You can try the following:
* increasing the `max_width` to some sufficiently large value.
* refactoring the code (something like this)
   ```
    let message = formate!(..)
    return Ok(Error { code: WRITE_OPERATION_IGNORED, message })
   ```
* if you're using a nightly version of rustfmt you can try setting `version=Two` and using `format_strings=true`.
