### ISSUE TITLE
rustfmt sometimes refuses to format_code_in_doc_comments

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/rustfmt#6014]
The minimal example I could find:

```
/// ```
/// use buck::types::TargetLabel;
///
///
/// use buck::types::TargetPattern;
///
///
///
///
///
///
/// assert!(!TargetPattern::new("foo//bar/...").is_specific_target());
/// ```
fn is_specific_target() {
}

/// ```
/// use buck::types::TargetLabel;
///
///
/// use buck::types::TargetPattern;
///
///
///
///
///
///
///
/// assert!(!
///     TargetPattern::new("foo//bar/...").matches(&TargetLabel::new("foo//moo/bar/baz:qux")),
/// );
/// ```
fn matches() {
}
```

```
rustfmt +nightly --config format_code_in_doc_comments=true
```

Outputs:

```
/// ```
/// use buck::types::TargetLabel;
///
/// use buck::types::TargetPattern;
///
/// assert!(!TargetPattern::new("foo//bar/...").is_specific_target());
/// ```
fn is_specific_target() {}

/// ```
/// use buck::types::TargetLabel;
///
///
/// use buck::types::TargetPattern;
///
///
///
///
///
///
///
/// assert!(!
///     TargetPattern::new("foo//bar/...").matches(&TargetLabel::new("foo//moo/bar/baz:qux")),
/// );
/// ```
fn matches() {}
```

So, first comment is reformatted, and the second is completely skipped. Something in that `assert!` prevents formatting.

```
rustfmt +nightly --version
rustfmt 1.7.0-nightly (ca663b06 2024-01-08)
```

**Comment by ytmimi** [comment]
This seems related to https://github.com/rust-lang/rustfmt/issues/5531. Specifically this makes me think of https://github.com/rust-lang/rustfmt/issues/5531#issuecomment-1345152743.

For now, linking the tracking issue for `format_code_in_doc_comments` #3348

**Comment by ytmimi** [comment]
I suspect this has the same underlying issue as #5531.

Taking a look at https://github.com/rust-lang/rustfmt/issues/5531#issuecomment-1345152743. I've explained that rustfmt isn't taking the doc comment opener into account. Furthermore, when rewriting macros rustfmt doesn't remove trailing commas.

rustfmt would love to produce this output, but it's 101 characters long
```
/// assert!(!TargetPattern::new("foo//bar/...").matches(&TargetLabel::new("foo//moo/bar/baz:qux")),);
```
and because it exceeds the max_width rustfmt can't reformat the code block. If you remove the trailing comma:

```rust
/// ```
/// use buck::types::TargetLabel;
///
///
/// use buck::types::TargetPattern;
///
///
///
///
///
///
///
/// assert!(!
///     TargetPattern::new("foo//bar/...").matches(&TargetLabel::new("foo//moo/bar/baz:qux")) 
/// );
/// ```
fn matches() {}
```

You'll get:
```rust
/// ```
/// use buck::types::TargetLabel;
///
/// use buck::types::TargetPattern;
///
/// assert!(!TargetPattern::new("foo//bar/...").matches(&TargetLabel::new("foo//moo/bar/baz:qux")));
/// ```
fn matches() {}
```

Additionally, I got code formatting to work when I set `doc_comment_code_block_width=99`, which further leads me to believe that this is a width related issue similar to https://github.com/rust-lang/rustfmt/issues/5531.
