### ISSUE TITLE
Formatting not working inside std::thread_local! {}

### ISSUE THREAD

**Issue by mzurs** [rust-lang/rustfmt#6133]
I recently encountered an issue while formatting variables inside thread_local! macro, but before that formatter is working fine. 
Also, I am unable to import pub static variables to other modules.

```rust
use std::cell::RefCell;
thread_local! {
    pub static FOO: RefCell<u32> = RefCell::new(1);

    static BAR: RefCell<f32> = RefCell::new(1.0);
}

FOO.with(|foo| assert_eq!(*foo.borrow(), 1));
BAR.with(|bar| assert_eq!(*bar.borrow(), 1.0));
```

**Comment by ytmimi** [comment]
@mzurs Thanks for reaching out. Could you provide more detail on what the issue is by including a snippet of code before and after formatting as well as how you expected the code to be formatted? Is formatting preventing you from compiling your program? Also, what version of rustfmt are you using now and what version of rustfmt were you using when things worked fine? Are you using any rustfmt configurations?

Could you elaborate on this point too 👇🏼. I'm not sure I understand how formatting would impact this.
> Also, I am unable to import pub static variables to other modules.

**Comment by mzurs** [comment]
- I can compile my program
- The problem is formatting is not working inside thread_local! macro, such as multiple variables are not aligned on default formatting. Also on hover to variable doesn't show any definitions, etc. But formatting works outside macro.
- The public variables I defined inside macro are not able to show when tried to call in other modules like IntelliSense is not working. Besides this, the program compiles successfully.
-  I don't know what version I used before, but right now I am using `rustfmt 1.7.0-stable (82e1608 2023-12-21)`

**Comment by ytmimi** [comment]
intelliSense issues are likely a language server problem. I'm not sure what tool you're using (rust-analyzer maybe?), but you should report those issues separately.

Also, rustfmt doesn't apply any formatting to macros that use braces`{}`. You'll want to use `()` or `[]` to have rustfmt try to format your macro calls.

To the best of my knowledge your example is already properly formatted:

```rust
thread_local! {
    pub static FOO: RefCell<u32> = RefCell::new(1);

    static BAR: RefCell<f32> = RefCell::new(1.0);
}
```
