### ISSUE TITLE
Trailing comma of a closure-like macro is deleted when the macro requires it

### ISSUE THREAD

**Issue by kkysen** [rust-lang/rustfmt#6228]
`rustfmt` deletes the trailing comma of a closure-like macro invocation even though the macro requires the trailing comma to compile.  For example, with

```rust
macro_rules! m {
    (|$($up_var:ident,)*| $body:block) => {};
}

fn f() {
    m!(|x,| {});
}
```

`rustfmt` tries to apply this change:

```diff
 fn f() {
-    m!(|x,| {});
+    m!(|x| {});
 }
```

But this change would not compile.

In this case of the macro, the trailing comma isn't needed; it could be rewritten to not require it.  But for something like this,

```rust
macro_rules! m {
    (|$($up_var:ident: $up_var_ty:ty$( = $up_var_val:expr)?,)*| $body:block) => {};
}
```

the trailing comma is necessary since `|` cannot come after a `:expr`.

`rustfmt` doesn't usually seem to format the code within a macro invocation (and doesn't otherwise for this use case, like wrapping long lines), except now it's reformatting things such that the code won't compile anymore.

**Comment by ytmimi** [comment]
This is a tough one. rustfmt doesn't have context about the macro definition when rewriting the macro call so it doesn't know that the trailing comma is actually required, and because the body of the macro parses as a closure rustfmt is going to format this as a closure.

Great to see that you can modify the macro definition to make the comma optional, but if you're using nightly rustfmt you can also consider setting the [`skip_macro_invocations`](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#skip_macro_invocations) config in your rustfmt.toml.
