### ISSUE TITLE
[feature request] Configuration support for different naming scehemes

### ISSUE THREAD

**Issue by sarpuser** [rust-lang/rustfmt#6367]
I would like an option to change the naming scheme in rustfmt. I would like to use loweCamelCase in my variable, function and method names, and use UpperCamelCase in module names.

**Comment by calebcartwright** [comment]
Thanks for reaching out but I am going to close this as it's not a feature we will develop and not one we'd be willing to support because it's too far outside of scope for this project and because in practice it wouldn't work and would cause breakage.

rustfmt does not and cannot provide IDE-like features that do project wide renaming. In the inner dev loop, rustfmt is often run on a single file or even on a subset of a file (just the parts that were changed), especially as part of the commonly used editor/ide format-on-save features.

rustfmt could do this in a very local context, but if it were to e.g. rename a function in a file it would not have the relevant information required to update the associated call sites and thus the rename would break things since the old function names would no longer resolve.
