### ISSUE TITLE
Rustfmt fix not live

### ISSUE THREAD

**Issue by ajewellamz** [rust-lang/rustfmt#6406]
I was eagerly awaiting the Rust 1.83.0 release, anticipating that it would include my fix for https://github.com/rust-lang/rustfmt/issues/6333 (https://github.com/rust-lang/rustfmt/pull/6375).

Unfortunately, that fix is in `https://github.com/rust-lang/rustfmt/commits/master/`, but does not seem to be in `https://github.com/rust-lang/rust/tree/master/src/tools/rustfmt`

How are these two projects related?
When might my fix go live?
Our CI is made rather difficult if rustfmt panics.

**Comment by ytmimi** [comment]
This repo, `https://github.com/rust-lang/rustfmt` is a git subtree of `https://github.com/rust-lang/rust/tree/master/src/tools/rustfmt`. rustfmt is maintained and developed here, and when the team is ready to cut a new release we sync any changes made here back with `https://github.com/rust-lang/rust/tree/master/src/tools/rustfmt` so that they can enter rust's regular release cycle.

I don't know when we're planning to do the next sync, but my guess would be relatively soon since there are still a few outstanding things the team wants to get in for the Rust 2024 edition.
