### ISSUE TITLE
'error[internal]: left behind trailing whitespace' after closure argument list

### ISSUE THREAD

**Issue by Tastaturtaste** [rust-lang/rustfmt#6423]
As the title says, the following code leads to an internal error:
```
fn main() {
    Some(1).map(|id| 
    // Some comment explaining what I am doing
    id + id);
}
```
Link to playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0714c35f8e91a1bb365a8059fa532329
The exact error message:

> error[internal]: left behind trailing whitespace
 --> /playground/src/main.rs:2:2:21
&nbsp;&nbsp;&nbsp;|
2&nbsp;|     Some(1).map(|id| 
&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
&nbsp;&nbsp;&nbsp;|

rustfmt version: 1.8.0-stable

Alternative: This also happens with a linebreak before the second `id` in the addition
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b12719274b196887bbd5691c063a173f

On a cursory skim the only duplicate I found was https://github.com/rust-lang/rustfmt/issues/2896, which is closed and locked without any resolution. Honestly I am a bit taken aback by the fact this bug from 2018 still seems to be around. I also noticed there are quite a few issues for this error caused by a wide variety of (valid) code patterns. Is there any path forward to fixing these? Is there guidance available if I wanted to try and fix this? Maybe it is already known what would have to be changed?

**Comment by ytmimi** [comment]
Thanks for the report, but this one is a duplicate #4855. The issue here is that the snippet contains trailing whitespace and rustfmt isn't expecting to find a comment between the closure parameters and the expression in the brace-less closures. In order to not drop the comment rustfmt leaves the closure unfromatted, which means the trailing space is preserved. You can add braces to the closure or manually remove the trailing space. 

>  I also noticed there are quite a few issues for this error caused by a wide variety of (valid) code patterns. Is there any path forward to fixing these?

The `error[internal]: left behind trailing whitespace` is a generic error and can happen for a number of reasons. The vast majority of cases reported involve code snippets like this one that already contain trailing whitespace that rustfmt has trouble removing.
